{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-redis/0.3.0.3/prompt-cache-redis-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-cache-redis",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.3.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.3.jar",
          "size": 18571,
          "sha512": "95caa4ae035cb2e76d623cb9dde6b55745a13a8b157adbbc9503853643d0f24a077dd8f8eb42ca956ebfd301ac9a3a1f4a1202dbd5f9d1f8110cc2a7209b1e92",
          "sha256": "f8fdce7aac6b067fc8ea17f69ad6ccde4fd17032d38defab3d440514637ae57b",
          "sha1": "f806e1ce7e0032ac7b9640c675cd4a2359d20a31",
          "md5": "71554925199051e245c699ed6fd770bd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.3.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.3.jar",
          "size": 18571,
          "sha512": "95caa4ae035cb2e76d623cb9dde6b55745a13a8b157adbbc9503853643d0f24a077dd8f8eb42ca956ebfd301ac9a3a1f4a1202dbd5f9d1f8110cc2a7209b1e92",
          "sha256": "f8fdce7aac6b067fc8ea17f69ad6ccde4fd17032d38defab3d440514637ae57b",
          "sha1": "f806e1ce7e0032ac7b9640c675cd4a2359d20a31",
          "md5": "71554925199051e245c699ed6fd770bd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.3-sources.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.3-sources.jar",
          "size": 3026,
          "sha512": "f05e22eff9f0abd76db04cd5f374599fcf2cc9aa9cc1a10daa89b593dc634cfb2ae69fae06446466bbedd9619c79241614e6f77888a07396042220d46e31f492",
          "sha256": "c9684cbc1d850747a00bdcaf3c5d4755eeeb170204f6f48c3d7e8765178ca6d5",
          "sha1": "ce4cc57ec800eb1932568b1d9979907dd561ac29",
          "md5": "8d6f6b7f434e64840e118577df1a4d15"
        }
      ]
    }
  ]
}
