{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-tokenizer/0.3.0.1/agents-features-tokenizer-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-tokenizer",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.1.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.1.jar",
          "size": 10521,
          "sha512": "fe881ad065d4917a04eccba617acc529f7384fb43d682a751cfd1a42d9769222d6cc783cbd695eca5143449ebbe1639b45e24e58bba5d3d7bbab89dca31a5f69",
          "sha256": "17638066a93dbcb3c1ec82639155dd4c3a29d577cbe886be349f8ab146c90543",
          "sha1": "514acf20eb33d5c68eaeb746af9fefec32d4dbda",
          "md5": "b827a6a2ec8a649d0bd3f8ba8943099d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.1.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.1.jar",
          "size": 10521,
          "sha512": "fe881ad065d4917a04eccba617acc529f7384fb43d682a751cfd1a42d9769222d6cc783cbd695eca5143449ebbe1639b45e24e58bba5d3d7bbab89dca31a5f69",
          "sha256": "17638066a93dbcb3c1ec82639155dd4c3a29d577cbe886be349f8ab146c90543",
          "sha1": "514acf20eb33d5c68eaeb746af9fefec32d4dbda",
          "md5": "b827a6a2ec8a649d0bd3f8ba8943099d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.1-sources.jar",
          "size": 4408,
          "sha512": "971fd1dcbbf34e351e5973cce924aa7af2fbfb01872a7476a60547b7c51cddc73f5bdbf0dfc86d203a6fc62c18894d33dfe7ad4bba33e7dc2178b0d773d45b73",
          "sha256": "f4a8dba2f14c54d1ee0842b49bfd48a93017528e79727bbf5b74304dd0d41c21",
          "sha1": "ca5e50b9cdd1b782ff14f94f3e93c081f4fc4220",
          "md5": "52b3d625bed4a02e0aafba87682b43d5"
        }
      ]
    }
  ]
}
