{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-model/0.3.0.1/prompt-executor-model-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-model",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.1.jar",
          "url": "prompt-executor-model-jvm-0.3.0.1.jar",
          "size": 8141,
          "sha512": "367364691b86f248220acb2225341b4f950a22d94141f6a0aeb1e2212ed0832f67e9303cbdbefc6187aa361665f4d7b65aceefcef74b64f6e529a4f0cb1e1032",
          "sha256": "8d81393467494b8e2fd71ee94044a288fd264232c42ad27bec46ee0bc3ec838e",
          "sha1": "6501a28eae6fb5e63fd61477fe3cf4595049f3b4",
          "md5": "ed87fbfd6d6ebd46cd4ec8fa5cb46073"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.1.jar",
          "url": "prompt-executor-model-jvm-0.3.0.1.jar",
          "size": 8141,
          "sha512": "367364691b86f248220acb2225341b4f950a22d94141f6a0aeb1e2212ed0832f67e9303cbdbefc6187aa361665f4d7b65aceefcef74b64f6e529a4f0cb1e1032",
          "sha256": "8d81393467494b8e2fd71ee94044a288fd264232c42ad27bec46ee0bc3ec838e",
          "sha1": "6501a28eae6fb5e63fd61477fe3cf4595049f3b4",
          "md5": "ed87fbfd6d6ebd46cd4ec8fa5cb46073"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-model-jvm-0.3.0.1-sources.jar",
          "size": 3514,
          "sha512": "16b0e0a6912cd480510b84e491f3fff08d119d9f89c91c53bc46351d4f42b736f5286e6408220b7f96b45d09ec61d0fe8f056138fd222a7ede0396131573af50",
          "sha256": "2a9769c146eac511a329e8c581ae4c3da804cefacd34bc99a51c1cc2b4aaa5bf",
          "sha1": "2fc5a4e0bd3ba88a22b192cb807d74809ebc089e",
          "md5": "1fff4c6fda3d72f3132461a2bd5425e0"
        }
      ]
    }
  ]
}
