{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-event-handler/0.3.0.3/agents-features-event-handler-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-features-event-handler",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-wasm-js-0.3.0.3.klib",
          "url": "agents-features-event-handler-wasm-js-0.3.0.3.klib",
          "size": 35869,
          "sha512": "74d518cf0218d021bb336147e759ff8f5d0a7b8d4cc8b8b5b70a661c05fb039690fe45acedeb570fd019e22fa99356c1bf0421cfa321153a8c8df766039b54f2",
          "sha256": "a7e873e718fb92da3c798e9916b6cd7f0f0ee64371b080e1a758b8c31fe413df",
          "sha1": "c9ce6ebe2856cd8bf7c6804aa4f31e13fe1560cc",
          "md5": "05fda78c0270889e123b268c5a8e8630"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-wasm-js-0.3.0.3.klib",
          "url": "agents-features-event-handler-wasm-js-0.3.0.3.klib",
          "size": 35869,
          "sha512": "74d518cf0218d021bb336147e759ff8f5d0a7b8d4cc8b8b5b70a661c05fb039690fe45acedeb570fd019e22fa99356c1bf0421cfa321153a8c8df766039b54f2",
          "sha256": "a7e873e718fb92da3c798e9916b6cd7f0f0ee64371b080e1a758b8c31fe413df",
          "sha1": "c9ce6ebe2856cd8bf7c6804aa4f31e13fe1560cc",
          "md5": "05fda78c0270889e123b268c5a8e8630"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-features-event-handler-wasm-js-0.3.0.3-sources.jar",
          "url": "agents-features-event-handler-wasm-js-0.3.0.3-sources.jar",
          "size": 8434,
          "sha512": "a654b29e6be6b215cb6327190e03f05e0be7b6b2bb62a1bad29f1d5e6c7356b0d95e7bfddb893d6b03ec69bb18f4cd753e001a38ba93ec66ae740cc9aaab0763",
          "sha256": "92a4655f88281d04dd0e3e2144029bda7e159da76dd07aa31da05d20a4bd28ec",
          "sha1": "d6152389d166e92c27ca36db6361d24b0a51afed",
          "md5": "e7e14b954f2355755d7d614722a7acfb"
        }
      ]
    }
  ]
}
