{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-llms/0.3.0.2/prompt-executor-llms-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-executor-llms",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.2.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.2.jar",
          "size": 24152,
          "sha512": "0b9a255aec5cc69fb62744fe04a70dbe6f0707e6fd40fbf57922333054d40ce8bd0f7c1adb40e60a0b79b065c7c96017f6dacdbd769c7de153a4e4d0826b8100",
          "sha256": "d83e6fbd5db757bc687fb7092c9626461d48193b74080d5923c2a9c81627f280",
          "sha1": "9d9ddecd13b3926344f4415de02f0a308a29e923",
          "md5": "a3b891cdaf88e517ef52ecc2b8bde7df"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.2.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.2.jar",
          "size": 24152,
          "sha512": "0b9a255aec5cc69fb62744fe04a70dbe6f0707e6fd40fbf57922333054d40ce8bd0f7c1adb40e60a0b79b065c7c96017f6dacdbd769c7de153a4e4d0826b8100",
          "sha256": "d83e6fbd5db757bc687fb7092c9626461d48193b74080d5923c2a9c81627f280",
          "sha1": "9d9ddecd13b3926344f4415de02f0a308a29e923",
          "md5": "a3b891cdaf88e517ef52ecc2b8bde7df"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.2-sources.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.2-sources.jar",
          "size": 4662,
          "sha512": "a2abccd591a749f639d52684fbc65a7b96f8a0c1c214ae427f0ac87759e2e83b13beed6cbbd4561d96ab91dfa66c9a1a47e0bbe5c63f51a7c5209e0e6b8716c6",
          "sha256": "4e770f73bfb17387fa9e05bdc70731a08c3edde3741e2a12a7de7e097f810725",
          "sha1": "e8449b0d6bfa6915d7002b94fa833b675ddeb23e",
          "md5": "5427be1e4d7344e38e3c534142e91e13"
        }
      ]
    }
  ]
}
