{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-debugger/0.3.0.1/agents-features-debugger-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-debugger",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.1.jar",
          "url": "agents-features-debugger-jvm-0.3.0.1.jar",
          "size": 40097,
          "sha512": "53ea6c93bbbfb81b0617ad28f6c2b7a7554b3c0488bde606198f3c0d8dc12a05d3d1092097ca75d8b5abda74e1a18015c94db79638c71b712c87b91de2b3ad89",
          "sha256": "7ae8c3c88532148db65e103330e6ef04916f94c4bce19dbb9f197c7ad9b9875b",
          "sha1": "7b4e05085aad65f310a19561a11f1cf2cf76a8e8",
          "md5": "587d60ea42730a4f3d5c62bf93f009ad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.1.jar",
          "url": "agents-features-debugger-jvm-0.3.0.1.jar",
          "size": 40097,
          "sha512": "53ea6c93bbbfb81b0617ad28f6c2b7a7554b3c0488bde606198f3c0d8dc12a05d3d1092097ca75d8b5abda74e1a18015c94db79638c71b712c87b91de2b3ad89",
          "sha256": "7ae8c3c88532148db65e103330e6ef04916f94c4bce19dbb9f197c7ad9b9875b",
          "sha1": "7b4e05085aad65f310a19561a11f1cf2cf76a8e8",
          "md5": "587d60ea42730a4f3d5c62bf93f009ad"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-debugger-jvm-0.3.0.1-sources.jar",
          "size": 7023,
          "sha512": "5dc2afba255c6b20c5ef4f439fc42ab379e82c73fe64c5a626e0d6a08db014a22151a622ec2a61926d133b5e6eeceb1fc575bd7b0254c32668ada5e3a1044581",
          "sha256": "8220f7a766e96e9077393e7054d4d4d7858a79f21d46c9d8ad582b68930b054b",
          "sha1": "ddd2f5ef0a82df38ef51e06e88cdfe7584cd7d41",
          "md5": "2872ec13c1db303e6b83643968219a92"
        }
      ]
    }
  ]
}
