{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-cached/0.3.0.4/prompt-executor-cached-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-cached",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-cached-wasm-js-0.3.0.4.klib",
          "size": 12674,
          "sha512": "ef6b4eb5158219b4aadb2586eb597e580c16bf96391356d6ef51695b4bd23e92c6f42a294fe078a3527a094b43818f55cce10044cdf42abf6c2aca7bc92cc063",
          "sha256": "dbda5a15a3144047d7e62ae00157952b2ffd3474da3a5d6ad7e222d9a1ad1b68",
          "sha1": "e121fdf32dac50ca4a1b085cb54bafaec6e7f12b",
          "md5": "656ced2691b462b5331b2263ee9107a8"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-cached-wasm-js-0.3.0.4.klib",
          "size": 12674,
          "sha512": "ef6b4eb5158219b4aadb2586eb597e580c16bf96391356d6ef51695b4bd23e92c6f42a294fe078a3527a094b43818f55cce10044cdf42abf6c2aca7bc92cc063",
          "sha256": "dbda5a15a3144047d7e62ae00157952b2ffd3474da3a5d6ad7e222d9a1ad1b68",
          "sha1": "e121fdf32dac50ca4a1b085cb54bafaec6e7f12b",
          "md5": "656ced2691b462b5331b2263ee9107a8"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-executor-cached-wasm-js-0.3.0.4-sources.jar",
          "url": "prompt-executor-cached-wasm-js-0.3.0.4-sources.jar",
          "size": 2987,
          "sha512": "83fb175f7c5495efd1d75b37fdad7e535cf4b6f811457abddcffd72acc454df23b2f7f5de2b86209a3bfaccf5728baf1024629be687ce09870323cc926c504c1",
          "sha256": "2afedb0e077a9c559c6eefe9819c4c7479c1aaeb6728083a112a5d2eea90b035",
          "sha1": "7e59a6e29654ab3bbe8e5d6655a036588c4ce23c",
          "md5": "cdd8a853879b856cfdd0a954821f1362"
        }
      ]
    }
  ]
}
