{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-tokenizer/0.3.0.2/prompt-tokenizer-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-tokenizer",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.2.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.2.jar",
          "size": 12351,
          "sha512": "07457ea13e3c5a814fec7e1c8c30228f13729d764272c1f7fe288e7222a3c5bbed7a96b42a0d794aab5675a64a5b4135241260810c5e49e5e77e4a45392b0c7e",
          "sha256": "68f93245d6e789c341acc99ee2f33ebd9b6fcb45f7270f1901a61a9c08084a61",
          "sha1": "4164a58640be8d41ea27a85252a5a2ea5abecdb2",
          "md5": "e209275843aead0b8979ce1d56529d64"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.2.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.2.jar",
          "size": 12351,
          "sha512": "07457ea13e3c5a814fec7e1c8c30228f13729d764272c1f7fe288e7222a3c5bbed7a96b42a0d794aab5675a64a5b4135241260810c5e49e5e77e4a45392b0c7e",
          "sha256": "68f93245d6e789c341acc99ee2f33ebd9b6fcb45f7270f1901a61a9c08084a61",
          "sha1": "4164a58640be8d41ea27a85252a5a2ea5abecdb2",
          "md5": "e209275843aead0b8979ce1d56529d64"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.2-sources.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.2-sources.jar",
          "size": 5324,
          "sha512": "9f20b03ab6292e425bc851b11683b9cc6ce0dddc3d6b6b4b042350ed5486fae56b2c116309542261cfa4869e16b5437b411d2d6b4318f65747484d3538ad780a",
          "sha256": "2dc6d3700773b4af3f73e9246fdce6d96535ffeb1534ae1d7c0410fe314453bb",
          "sha1": "4e09855b24b57f5baa052bb8ae81407de6f91891",
          "md5": "f8a904bee7024e89c1166a9ba9c72e34"
        }
      ]
    }
  ]
}
