{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-structure",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-metadata-0.3.0.4.jar",
          "url": "prompt-structure-0.3.0.4.jar",
          "size": 15341,
          "sha512": "088e29ba9ee2c3dfcb21abeb05112e604c5ca8d648c35cdf275ea26cccb139e798149471ad3489fad4864d80f8efe2f6dde08d8669ac0dc2a6d4f8e2c12365d6",
          "sha256": "ba0c7b3c17fe7fa4fb72581acc19599111f4ad70d77d892fae2a2b025df53ce8",
          "sha1": "d2529cb5e911921840c3df16e9b44cf3b83fd1dd",
          "md5": "3d63e1522a2f49f514a4bf4a6b900a11"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-structure-kotlin-0.3.0.4-sources.jar",
          "url": "prompt-structure-0.3.0.4-sources.jar",
          "size": 27083,
          "sha512": "5250c66d20748c0b806880f3bcadd10974d9fce61b8170c456beb544c28b4c99d625e52e20cf528ee112d777c668ef9b927cf9b287681b93b34c8de1da6d1545",
          "sha256": "ea31e982ba60a38f96019e99d6f2a722a314af16a605d1f4bc51761110633d6a",
          "sha1": "aa01e369cc1be7f8d1ddf432020ec37b319b1e48",
          "md5": "ac7eebd2009db0043d906d30f7ddfc99"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-js/0.3.0.4/prompt-structure-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-js/0.3.0.4/prompt-structure-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-js/0.3.0.4/prompt-structure-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-structure-jvm/0.3.0.4/prompt-structure-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-structure-jvm/0.3.0.4/prompt-structure-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-structure-jvm/0.3.0.4/prompt-structure-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-wasm-js/0.3.0.4/prompt-structure-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-wasm-js/0.3.0.4/prompt-structure-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-structure-wasm-js/0.3.0.4/prompt-structure-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-structure-wasm-js",
        "version": "0.3.0.4"
      }
    }
  ]
}
