{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-clients/0.3.0.4/prompt-executor-clients-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-clients",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-clients-wasm-js-0.3.0.4.klib",
          "size": 10375,
          "sha512": "84b6f338425b20793bda07fce27ae4807efdc83006c99f5332975fa0c4e5c3bdaf0a59890935e59e9e9e20b640e9335074e12ec2c3c5ef3195cce6adefadffdd",
          "sha256": "319550690d41a5d1dc152b01543a63224ec3888e8766e7abc3213b682b3fb5c8",
          "sha1": "47b77aa49512fc8bb9b3642028a797d160a38386",
          "md5": "dd646de924fcf55fcd7858f9751a2bab"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-clients-wasm-js-0.3.0.4.klib",
          "size": 10375,
          "sha512": "84b6f338425b20793bda07fce27ae4807efdc83006c99f5332975fa0c4e5c3bdaf0a59890935e59e9e9e20b640e9335074e12ec2c3c5ef3195cce6adefadffdd",
          "sha256": "319550690d41a5d1dc152b01543a63224ec3888e8766e7abc3213b682b3fb5c8",
          "sha1": "47b77aa49512fc8bb9b3642028a797d160a38386",
          "md5": "dd646de924fcf55fcd7858f9751a2bab"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-executor-clients-wasm-js-0.3.0.4-sources.jar",
          "url": "prompt-executor-clients-wasm-js-0.3.0.4-sources.jar",
          "size": 4120,
          "sha512": "b80e745e87e6e2428a6ea4a7d6d4a8f4d07f97ae4cfd5e4db5c8ffee462488811f147550f5944466967470b2465c737843c7f0e631929579fee2b574644f24c6",
          "sha256": "09854c5f38280755c271810c08c7185302b9d6335ab431da7a76bbb34625ec2c",
          "sha1": "95f21fd5197ac0ede003b47fdd194126ea0a5fb3",
          "md5": "a70b31f0a2829a2bf8581f02ff98ab95"
        }
      ]
    }
  ]
}
