{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-cache-files",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-metadata-0.3.0.2.jar",
          "url": "prompt-cache-files-0.3.0.2.jar",
          "size": 742,
          "sha512": "f19b08bc6b59b7c9f8b1d48d7478e2179a119b36ae3a9620f8aeb9ab73f585da9ba245d803a8d1eea235653f4edd58a4021cf692b2bda5197e50793fbabd129e",
          "sha256": "3f1f0a9e5b9893d113807830ed9c073e1443a652cff0d4356f00cf391aa547eb",
          "sha1": "5334919d972ee8b32b2f303b0e7e4a26f44c4833",
          "md5": "fa5f2a480ff21d9d7dc7ec02926cb736"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-cache-files-kotlin-0.3.0.2-sources.jar",
          "url": "prompt-cache-files-0.3.0.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-js/0.3.0.2/prompt-cache-files-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-js/0.3.0.2/prompt-cache-files-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-js/0.3.0.2/prompt-cache-files-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-cache-files-jvm/0.3.0.2/prompt-cache-files-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-cache-files-jvm/0.3.0.2/prompt-cache-files-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-cache-files-jvm/0.3.0.2/prompt-cache-files-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-wasm-js/0.3.0.2/prompt-cache-files-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-wasm-js/0.3.0.2/prompt-cache-files-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-cache-files-wasm-js/0.3.0.2/prompt-cache-files-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "prompt-cache-files-wasm-js",
        "version": "0.3.0.2"
      }
    }
  ]
}
