{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-tools/0.3.0.2/agents-tools-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-tools",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-wasm-js-0.3.0.2.klib",
          "url": "agents-tools-wasm-js-0.3.0.2.klib",
          "size": 59992,
          "sha512": "bfbe4a9c1d680dd5c6c04a858912866aaf53a44a325f91fafe53ba01967153280012ac70a8d95967b01d2eb13c45ca78c125d7c54073fd5e4b5f3915fe5da80f",
          "sha256": "1915402ac88221e9f6c4ae12f832d192cd82d45f37aaed7e589c172cf39b58e2",
          "sha1": "ff1edb7b730c8f8adca92f770db33c98f34a821c",
          "md5": "533830f9756a4f83cf71255a0e2d93eb"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-wasm-js-0.3.0.2.klib",
          "url": "agents-tools-wasm-js-0.3.0.2.klib",
          "size": 59992,
          "sha512": "bfbe4a9c1d680dd5c6c04a858912866aaf53a44a325f91fafe53ba01967153280012ac70a8d95967b01d2eb13c45ca78c125d7c54073fd5e4b5f3915fe5da80f",
          "sha256": "1915402ac88221e9f6c4ae12f832d192cd82d45f37aaed7e589c172cf39b58e2",
          "sha1": "ff1edb7b730c8f8adca92f770db33c98f34a821c",
          "md5": "533830f9756a4f83cf71255a0e2d93eb"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-tools-wasm-js-0.3.0.2-sources.jar",
          "url": "agents-tools-wasm-js-0.3.0.2-sources.jar",
          "size": 13742,
          "sha512": "e2a231dbece19c5b08198ed82adbd4319af0a9b21183b7f5187b1e986bc0ad128768ab215756de48b9c1a53e13b41a8465a6d63e77ab4577e3bd25db9c46e8b1",
          "sha256": "1eb52535c8cf5e3227fe5fb4d5b13cc3134c3c1c6aaa4f4cdfd65ffd99d233d8",
          "sha1": "db0d9085ba34fc983456704d7e524377710cccfe",
          "md5": "3df497359ac76300dae97067eabcdb6e"
        }
      ]
    }
  ]
}
