{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-ext/0.3.0.2/agents-ext-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-ext",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-wasm-js-0.3.0.2.klib",
          "url": "agents-ext-wasm-js-0.3.0.2.klib",
          "size": 59447,
          "sha512": "08a35730f0343428c5639c39bfab60c7d7489d533386ffaa1de470c22cd3a04c45c1434d1ab61e84dbf7bafde8949234ebd7861cdba861bd346a0dd07ecdb3e2",
          "sha256": "201ac207d69d445e74ec8150221322189c997a7241ae1d9addbde95b77a01994",
          "sha1": "a42a6492dba1ca1357f8e131506c8f30be5de8da",
          "md5": "0f5ad5215fd838987ef74b4851b88b89"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-wasm-js-0.3.0.2.klib",
          "url": "agents-ext-wasm-js-0.3.0.2.klib",
          "size": 59447,
          "sha512": "08a35730f0343428c5639c39bfab60c7d7489d533386ffaa1de470c22cd3a04c45c1434d1ab61e84dbf7bafde8949234ebd7861cdba861bd346a0dd07ecdb3e2",
          "sha256": "201ac207d69d445e74ec8150221322189c997a7241ae1d9addbde95b77a01994",
          "sha1": "a42a6492dba1ca1357f8e131506c8f30be5de8da",
          "md5": "0f5ad5215fd838987ef74b4851b88b89"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-ext-wasm-js-0.3.0.2-sources.jar",
          "url": "agents-ext-wasm-js-0.3.0.2-sources.jar",
          "size": 15660,
          "sha512": "d595d7273d7f55ffae4f6431b05057446610ef1cd669bf6df2207b6c135cd1e8def4450f90b71c8348c274614a914f787579848de16192cfc28ed81c879f1c38",
          "sha256": "022362051cc88c5d1d4303b9ff0601c3d8078c6222d0266e6c3080527246bdd3",
          "sha1": "d8614bf76dc191e67761ac9b0213f066d9b80460",
          "md5": "6cd796ed1435b716c8251eac651905a3"
        }
      ]
    }
  ]
}
