{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-mcp/0.3.0.2/agents-mcp-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-mcp",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "io.modelcontextprotocol",
          "module": "kotlin-sdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-mcp-jvm-0.3.0.2.jar",
          "url": "agents-mcp-jvm-0.3.0.2.jar",
          "size": 42257,
          "sha512": "6a56bcbb027152dbd32684622c64b8cd91778beb28e367a37312f338cb49118b1f039ec611743eb1fbd7937ec50942eab9235f1c9ad6000a48a79aaf18d768e8",
          "sha256": "e7618bf79c2e51dbd8c813107cc26ddd10df8be6462d95722cd24b84706a13a3",
          "sha1": "2c5ffe77a447c1a741ceddf1a508bdecafce5251",
          "md5": "279d698cb0d08b45365b66c9f4bafdcd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "io.modelcontextprotocol",
          "module": "kotlin-sdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "agents-mcp-jvm-0.3.0.2.jar",
          "url": "agents-mcp-jvm-0.3.0.2.jar",
          "size": 42257,
          "sha512": "6a56bcbb027152dbd32684622c64b8cd91778beb28e367a37312f338cb49118b1f039ec611743eb1fbd7937ec50942eab9235f1c9ad6000a48a79aaf18d768e8",
          "sha256": "e7618bf79c2e51dbd8c813107cc26ddd10df8be6462d95722cd24b84706a13a3",
          "sha1": "2c5ffe77a447c1a741ceddf1a508bdecafce5251",
          "md5": "279d698cb0d08b45365b66c9f4bafdcd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-mcp-jvm-0.3.0.2-sources.jar",
          "url": "agents-mcp-jvm-0.3.0.2-sources.jar",
          "size": 8790,
          "sha512": "e81418fdc6c72abffcd937ea44901f65055e8394316b1dcc5dbb44faf7f762cc5612f3706473e486f8f32c6d21e6e05b9e1e9c777de4bc631192cad84065a8e0",
          "sha256": "e12fc32edcec412e91b4e1ec8cc1ecb62a76d4a53d35ec8c39593166ed6cf8d3",
          "sha1": "2fc0c3c36fecfebcb08664d27a8ab187a1af16a0",
          "md5": "60f447174f8ece08487031f082be9a6a"
        }
      ]
    }
  ]
}
