{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-bedrock-client/0.3.0.4/prompt-executor-bedrock-client-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-bedrock-client",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.4.jar",
          "size": 290673,
          "sha512": "bf0b12c9a8a1df853aaf09d93b6664c36a1e4a81fcf55b5780033fcc3012fd25fedc6fc329bd81588429fd374433c9edf5adf5a79ff80491c20ab09afbc553bc",
          "sha256": "a39bb4a4fcf6db27f72dc485d15b2a7b1774cbebb5e26d745f7c78d349f78b30",
          "sha1": "fbc15408fda1eabe5115226aa38c531c6d36ee00",
          "md5": "00858a5aac3bd8cf84cb14088d16d97c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "bedrockruntime",
          "version": {
            "requires": "1.4.119"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.4.jar",
          "size": 290673,
          "sha512": "bf0b12c9a8a1df853aaf09d93b6664c36a1e4a81fcf55b5780033fcc3012fd25fedc6fc329bd81588429fd374433c9edf5adf5a79ff80491c20ab09afbc553bc",
          "sha256": "a39bb4a4fcf6db27f72dc485d15b2a7b1774cbebb5e26d745f7c78d349f78b30",
          "sha1": "fbc15408fda1eabe5115226aa38c531c6d36ee00",
          "md5": "00858a5aac3bd8cf84cb14088d16d97c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.4-sources.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.4-sources.jar",
          "size": 21720,
          "sha512": "9491a6d22dbb050efc7c66dd6556b4b1c1966c44eb025cf8ec7459f3c35683c2542ee5c314ef771081cdb6fa5411e259627b3bd273f1a68f0383db6f5f46cb2c",
          "sha256": "6f6760b0034fe7d0a45718664d16df8414ef65470134e82b428ab4859618de73",
          "sha1": "122e4131eb414dc1162c07c1f4f21c428dfec868",
          "md5": "59bf77a0e01412f82fade43bc23b0278"
        }
      ]
    }
  ]
}
