{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-files/0.3.0.3/prompt-cache-files-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-cache-files",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.3.jar",
          "url": "prompt-cache-files-jvm-0.3.0.3.jar",
          "size": 18446,
          "sha512": "ddb2ec070858e746e52d2d3a8a74ca7def0ff321ddce18bdc25e06ec7c4fb558f93434e7e18d86734f8df140b57c3d02d89b2571694a61980edde1d87977f12c",
          "sha256": "eaa6622c3a509d6cf822ea049de2b8ec1bf7b29e136702f5f31e587b57b7d5d5",
          "sha1": "7eb2d4cca2a7f2bd2842e1b5ae43295f2073fb3b",
          "md5": "6c330804c142de9a8139e2a0d7f4b84b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.3.jar",
          "url": "prompt-cache-files-jvm-0.3.0.3.jar",
          "size": 18446,
          "sha512": "ddb2ec070858e746e52d2d3a8a74ca7def0ff321ddce18bdc25e06ec7c4fb558f93434e7e18d86734f8df140b57c3d02d89b2571694a61980edde1d87977f12c",
          "sha256": "eaa6622c3a509d6cf822ea049de2b8ec1bf7b29e136702f5f31e587b57b7d5d5",
          "sha1": "7eb2d4cca2a7f2bd2842e1b5ae43295f2073fb3b",
          "md5": "6c330804c142de9a8139e2a0d7f4b84b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.3-sources.jar",
          "url": "prompt-cache-files-jvm-0.3.0.3-sources.jar",
          "size": 2970,
          "sha512": "225e701a8d054eb310e1f54889e8e68fdcb0aaf51e702409a08c8162aafefdff3698b29b2da15a9a9bfd484569ac06dbc1f7d291735abd98ca8ffe1074ce00ad",
          "sha256": "24caa2d9e7873d46b6f06398ea09dc2d9fb7e061fa6f3e12a20947d60b5737e2",
          "sha1": "8feee901ecb03e2ac8da3c1ead9a9076a3eb1a66",
          "md5": "2fe549439e3f4bc97428a3f378038020"
        }
      ]
    }
  ]
}
