{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.2/prompt-markdown-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.2.jar",
          "url": "prompt-markdown-jvm-0.3.0.2.jar",
          "size": 13470,
          "sha512": "9eb8ec7fa74d1f139290d9b3761588e131b5222c73c48b21a51dab4dcbe1d98961311dda5fd7ef0580016c7048381cefbb962ce973023c2c26928dca1eed674c",
          "sha256": "003c6270d12292825ce1fd3e2085d8f367f6e9e8f332301c822f96d447d67e75",
          "sha1": "8e5ce4d32750ecb2fcd6f578f2295363e9563ff7",
          "md5": "ebfe31a3f542c75b891616a33e98d26d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.2.jar",
          "url": "prompt-markdown-jvm-0.3.0.2.jar",
          "size": 13470,
          "sha512": "9eb8ec7fa74d1f139290d9b3761588e131b5222c73c48b21a51dab4dcbe1d98961311dda5fd7ef0580016c7048381cefbb962ce973023c2c26928dca1eed674c",
          "sha256": "003c6270d12292825ce1fd3e2085d8f367f6e9e8f332301c822f96d447d67e75",
          "sha1": "8e5ce4d32750ecb2fcd6f578f2295363e9563ff7",
          "md5": "ebfe31a3f542c75b891616a33e98d26d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.2-sources.jar",
          "url": "prompt-markdown-jvm-0.3.0.2-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
