{
  "formatVersion": "1.1",
  "component": {
    "url": "../../embeddings-base/0.3.0.1/embeddings-base-0.3.0.1.module",
    "group": "ai.koog",
    "module": "embeddings-base",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.1.jar",
          "url": "embeddings-base-jvm-0.3.0.1.jar",
          "size": 9722,
          "sha512": "067881b37972d211d8986072cc6dd27a2540d7f768641f85f9cf922ef03b82eaee927fdf55c9b13a2d0c9f1a89971e70581768e67c43e087578ce5b6b7624bce",
          "sha256": "5d45d5916ffe26b4eb113cde28ee24e6dc2381be9326b55af9835185a59efcd2",
          "sha1": "b127d252293a4babc678ecf85111920a6971791a",
          "md5": "93fadd1e3b3f2b20b54342078363fc84"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.1.jar",
          "url": "embeddings-base-jvm-0.3.0.1.jar",
          "size": 9722,
          "sha512": "067881b37972d211d8986072cc6dd27a2540d7f768641f85f9cf922ef03b82eaee927fdf55c9b13a2d0c9f1a89971e70581768e67c43e087578ce5b6b7624bce",
          "sha256": "5d45d5916ffe26b4eb113cde28ee24e6dc2381be9326b55af9835185a59efcd2",
          "sha1": "b127d252293a4babc678ecf85111920a6971791a",
          "md5": "93fadd1e3b3f2b20b54342078363fc84"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.1-sources.jar",
          "url": "embeddings-base-jvm-0.3.0.1-sources.jar",
          "size": 2866,
          "sha512": "e81dfdb729687f3ad3e8fa95ff68071a2110bcc0cac9b1ccc7b540294c7b727b6a5a936d6a30ecaf2e00271cae521bc83fee28d3a603cd293aea42993299e10b",
          "sha256": "fb733ac421cc959291dd802d0a4f62ea02d187d38b6ba657d53a3f4bc3c7199d",
          "sha1": "2aec73c029fe70e9c2cbb65df91fc875ab28280e",
          "md5": "a47ba90ec1994339e340b7926f4e5bef"
        }
      ]
    }
  ]
}
