{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-redis/0.3.0.4/prompt-cache-redis-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-cache-redis",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.4.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.4.jar",
          "size": 18571,
          "sha512": "03bb9e214b1edb2cb43191efc99ebb295f0aa8fad5e61cb749676544c149fd2434eb29517afe9c7060237eb0e093e2ef5203e5e1a0da6de5f0ae972b4d80ac3f",
          "sha256": "f9da31baa695242b89bd4e500947f9eb4f46f9c707137b61e1c098ff93ecce2d",
          "sha1": "bb8e1f96a7d5cb7ee64626e3ffc1b9bf2b42ddf1",
          "md5": "e2c06e7eedbe627cee7ceb8355437137"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.4.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.4.jar",
          "size": 18571,
          "sha512": "03bb9e214b1edb2cb43191efc99ebb295f0aa8fad5e61cb749676544c149fd2434eb29517afe9c7060237eb0e093e2ef5203e5e1a0da6de5f0ae972b4d80ac3f",
          "sha256": "f9da31baa695242b89bd4e500947f9eb4f46f9c707137b61e1c098ff93ecce2d",
          "sha1": "bb8e1f96a7d5cb7ee64626e3ffc1b9bf2b42ddf1",
          "md5": "e2c06e7eedbe627cee7ceb8355437137"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.4-sources.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.4-sources.jar",
          "size": 3026,
          "sha512": "f05e22eff9f0abd76db04cd5f374599fcf2cc9aa9cc1a10daa89b593dc634cfb2ae69fae06446466bbedd9619c79241614e6f77888a07396042220d46e31f492",
          "sha256": "c9684cbc1d850747a00bdcaf3c5d4755eeeb170204f6f48c3d7e8765178ca6d5",
          "sha1": "ce4cc57ec800eb1932568b1d9979907dd561ac29",
          "md5": "8d6f6b7f434e64840e118577df1a4d15"
        }
      ]
    }
  ]
}
