{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-ktor/0.3.0.2/koog-ktor-0.3.0.2.module",
    "group": "ai.koog",
    "module": "koog-ktor",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-js-0.3.0.2.klib",
          "url": "koog-ktor-js-0.3.0.2.klib",
          "size": 63637,
          "sha512": "11bb994d58c6fa89e8db922152c0bf8dcb1fe7edb54e408e2facb4e3b8b02a9821de2d7bceaee9ded3ec0a627de72725b2054b8eabeb7a75de3b8c1569927e47",
          "sha256": "4a18655f83f66aa878774df8e29d556eecb364d1dc518944329eb1e84152ace7",
          "sha1": "55fcf4ff45d3507240bce258a0e5b537ea2bd42f",
          "md5": "e9395f3b02091f90bccc82ad1043940f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-js-0.3.0.2.klib",
          "url": "koog-ktor-js-0.3.0.2.klib",
          "size": 63637,
          "sha512": "11bb994d58c6fa89e8db922152c0bf8dcb1fe7edb54e408e2facb4e3b8b02a9821de2d7bceaee9ded3ec0a627de72725b2054b8eabeb7a75de3b8c1569927e47",
          "sha256": "4a18655f83f66aa878774df8e29d556eecb364d1dc518944329eb1e84152ace7",
          "sha1": "55fcf4ff45d3507240bce258a0e5b537ea2bd42f",
          "md5": "e9395f3b02091f90bccc82ad1043940f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "koog-ktor-js-0.3.0.2-sources.jar",
          "url": "koog-ktor-js-0.3.0.2-sources.jar",
          "size": 16262,
          "sha512": "2b313098ebf3357d0e5055778254f003d44043a33a79937908b0a7e13ad9fc6e4265721ed2fff119822ef6f75bdb9e52b12b6df9e5154b73cae4cbf85c9a2518",
          "sha256": "7ee8c56285c7bb7f39a5a6b5de3d3b2a58c116eaaa292138fb67228fcde6fd5b",
          "sha1": "592ff0c04c09553735b6d84b4aebffd5ce4b5a12",
          "md5": "c922462cb1a1512646ea7e43cdbc418f"
        }
      ]
    }
  ]
}
