{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-snapshot/0.3.0.4/agents-features-snapshot-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-features-snapshot",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.4.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.4.jar",
          "size": 57654,
          "sha512": "aaa3763477abae43a8c430943a17920044964531a4eb8cce976e8cc7487a4b03b6d89a016eebe22894a145f3efde42a3749719714b7eaea4ec02bb1f78222c73",
          "sha256": "bfc65148b812adbe5b376adbbfbaeb88d29718b84fd4dbd185d9af6fc8543172",
          "sha1": "b10bff24bff2488839ce7ffc2230aa6db984095a",
          "md5": "7faaae160da274da7d7134d2154a86d8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.4.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.4.jar",
          "size": 57654,
          "sha512": "aaa3763477abae43a8c430943a17920044964531a4eb8cce976e8cc7487a4b03b6d89a016eebe22894a145f3efde42a3749719714b7eaea4ec02bb1f78222c73",
          "sha256": "bfc65148b812adbe5b376adbbfbaeb88d29718b84fd4dbd185d9af6fc8543172",
          "sha1": "b10bff24bff2488839ce7ffc2230aa6db984095a",
          "md5": "7faaae160da274da7d7134d2154a86d8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.4-sources.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.4-sources.jar",
          "size": 11197,
          "sha512": "2003e6fe0cad57845d79b981e1c2934dbd6acd6f29b14f8391004f1dda3858399d7d6bd307fbf2db98f8c68a58131c46eef1944cc3f861c8897ffca2aa7605c4",
          "sha256": "98314cf24bce5f5e05a1260175af747987a48e04f9fbd4973b9dd92d02a8b5a8",
          "sha1": "7f856949d85590a48a6f787cb4da52fa2de74578",
          "md5": "b56a49d290cc1679eb4b590fbec6de18"
        }
      ]
    }
  ]
}
