{
  "formatVersion": "1.1",
  "component": {
    "url": "../../embeddings-base/0.3.0.3/embeddings-base-0.3.0.3.module",
    "group": "ai.koog",
    "module": "embeddings-base",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-js-0.3.0.3.klib",
          "url": "embeddings-base-js-0.3.0.3.klib",
          "size": 13948,
          "sha512": "d77c868457aba0933191b8788b0b65d507a55d045fcc5f69dbf9d885808c0f77ab4e681a8b5e81a71d60516d4b4a82420c3547c884b45b86ee865e990072e65d",
          "sha256": "e1be97beabf0e9bcf8df7055f6613d42d47434dd373b395579c2405dd0e7f6c4",
          "sha1": "9798b6670a98b44b2c50895aa33adccc93563df1",
          "md5": "3825919ace03669072961d7edfbc6808"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-js-0.3.0.3.klib",
          "url": "embeddings-base-js-0.3.0.3.klib",
          "size": 13948,
          "sha512": "d77c868457aba0933191b8788b0b65d507a55d045fcc5f69dbf9d885808c0f77ab4e681a8b5e81a71d60516d4b4a82420c3547c884b45b86ee865e990072e65d",
          "sha256": "e1be97beabf0e9bcf8df7055f6613d42d47434dd373b395579c2405dd0e7f6c4",
          "sha1": "9798b6670a98b44b2c50895aa33adccc93563df1",
          "md5": "3825919ace03669072961d7edfbc6808"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "embeddings-base-js-0.3.0.3-sources.jar",
          "url": "embeddings-base-js-0.3.0.3-sources.jar",
          "size": 2866,
          "sha512": "e81dfdb729687f3ad3e8fa95ff68071a2110bcc0cac9b1ccc7b540294c7b727b6a5a936d6a30ecaf2e00271cae521bc83fee28d3a603cd293aea42993299e10b",
          "sha256": "fb733ac421cc959291dd802d0a4f62ea02d187d38b6ba657d53a3f4bc3c7199d",
          "sha1": "2aec73c029fe70e9c2cbb65df91fc875ab28280e",
          "md5": "a47ba90ec1994339e340b7926f4e5bef"
        }
      ]
    }
  ]
}
