{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-xml",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-metadata-0.3.0.1.jar",
          "url": "prompt-xml-0.3.0.1.jar",
          "size": 2685,
          "sha512": "f5ae2e096f109bcff3f91c1340bbf0018e238431728025760d10b8f7210e9652ea24202bbb9a8034c895aefc776932becb3e4073a3311cb4cb4df06c2721dda7",
          "sha256": "0408bf68e4c7d99e5a93d67b7fbb1f87f99362a8cf26929b76d1b2f11ce91f92",
          "sha1": "699619981e7001ffde597af11a04b1fb8537ee36",
          "md5": "c1f4158ba8968a505515b84b82cee8da"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-xml-kotlin-0.3.0.1-sources.jar",
          "url": "prompt-xml-0.3.0.1-sources.jar",
          "size": 2531,
          "sha512": "6d51a670528f215f3a2f2d83286b0acb452bc655ab3095ffc7c65db8fe4ff68360f451c4336d3c6413501b42fc02c771dc76fb51d7b9621c0530c87594688f9b",
          "sha256": "3abed046ad0da624dbd5c4682df923ea37f0bbb8a7498887ce7c61cb9ba92146",
          "sha1": "80e54d1333b6ecc149680e54aba3ba202f8146b3",
          "md5": "11c9dcc6cf24a6e053fd0390dbd9fb86"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-js/0.3.0.1/prompt-xml-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-js/0.3.0.1/prompt-xml-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-js/0.3.0.1/prompt-xml-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-xml-jvm/0.3.0.1/prompt-xml-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-xml-jvm/0.3.0.1/prompt-xml-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-xml-jvm/0.3.0.1/prompt-xml-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-wasm-js/0.3.0.1/prompt-xml-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-wasm-js/0.3.0.1/prompt-xml-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-xml-wasm-js/0.3.0.1/prompt-xml-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-xml-wasm-js",
        "version": "0.3.0.1"
      }
    }
  ]
}
