{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-redis/0.3.0.2/prompt-cache-redis-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-cache-redis",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.2.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.2.jar",
          "size": 18571,
          "sha512": "fb342f7711c3cd459b73d97c49ecebded298d65ae48b8911078e3af2c372afabaad9e2e824092cef0bf7df3baab4a70ca0290a35fe1d80e1c17a30031f715e1a",
          "sha256": "5a1faa86596b9d1b545bd7f589d04353b6ec28ad2456243e6cb6d7c18fea7f04",
          "sha1": "7082fca7792f85ddad08a7f886c0d347d5beb0d7",
          "md5": "6f141ea4adb986cedb2009f9ffaedf9b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.2.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.2.jar",
          "size": 18571,
          "sha512": "fb342f7711c3cd459b73d97c49ecebded298d65ae48b8911078e3af2c372afabaad9e2e824092cef0bf7df3baab4a70ca0290a35fe1d80e1c17a30031f715e1a",
          "sha256": "5a1faa86596b9d1b545bd7f589d04353b6ec28ad2456243e6cb6d7c18fea7f04",
          "sha1": "7082fca7792f85ddad08a7f886c0d347d5beb0d7",
          "md5": "6f141ea4adb986cedb2009f9ffaedf9b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.2-sources.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.2-sources.jar",
          "size": 3026,
          "sha512": "f05e22eff9f0abd76db04cd5f374599fcf2cc9aa9cc1a10daa89b593dc634cfb2ae69fae06446466bbedd9619c79241614e6f77888a07396042220d46e31f492",
          "sha256": "c9684cbc1d850747a00bdcaf3c5d4755eeeb170204f6f48c3d7e8765178ca6d5",
          "sha1": "ce4cc57ec800eb1932568b1d9979907dd561ac29",
          "md5": "8d6f6b7f434e64840e118577df1a4d15"
        }
      ]
    }
  ]
}
