{
  "formatVersion": "1.1",
  "component": {
    "url": "../../vector-storage/0.3.0.2/vector-storage-0.3.0.2.module",
    "group": "ai.koog",
    "module": "vector-storage",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.2.jar",
          "url": "vector-storage-jvm-0.3.0.2.jar",
          "size": 53335,
          "sha512": "16f25ee9067d3687409cef30abd7f852a2781ff86f530bd5396939ca66534f02f4258ff310f488c055bdd8c9c8c316f586e7945d36e75a8adb3084068b79154d",
          "sha256": "656e5197c759be6c8285c0c41bf67e34e16e2d585e7f231e37db25c011ad50a4",
          "sha1": "94c50e844377cde86987564a09cbd44b79b9a9be",
          "md5": "9b83c91726ba15e01ae248c932362673"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.2.jar",
          "url": "vector-storage-jvm-0.3.0.2.jar",
          "size": 53335,
          "sha512": "16f25ee9067d3687409cef30abd7f852a2781ff86f530bd5396939ca66534f02f4258ff310f488c055bdd8c9c8c316f586e7945d36e75a8adb3084068b79154d",
          "sha256": "656e5197c759be6c8285c0c41bf67e34e16e2d585e7f231e37db25c011ad50a4",
          "sha1": "94c50e844377cde86987564a09cbd44b79b9a9be",
          "md5": "9b83c91726ba15e01ae248c932362673"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.2-sources.jar",
          "url": "vector-storage-jvm-0.3.0.2-sources.jar",
          "size": 9535,
          "sha512": "642543700c43474042857bc9e43c898519697815245213a476671dfeca8c8eed6f977b2079d4069d903ed08e25deca7b90c051b227696ab15f8213419d1b70c6",
          "sha256": "32ce7d7b209bb9b9444351e44a212bb9c081c8f7224e9b7094c774c331cebc95",
          "sha1": "589ba1df5e485fa3c2b15a2a983e471fd3eb734e",
          "md5": "fd7a65689a0264a649b0400125653678"
        }
      ]
    }
  ]
}
