{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-files/0.3.0.1/prompt-cache-files-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-cache-files",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.1.jar",
          "url": "prompt-cache-files-jvm-0.3.0.1.jar",
          "size": 18446,
          "sha512": "5ea3a3e2c520dfe4e9f13a6d1285c1fe961c044cd38e02786d0e8774b76b078f99f76342b093cfe438e722f763c17bf8679d137aeaaff33fe9101aefe16e8fcc",
          "sha256": "38f281321d188d58562e64641208edf10fb0f2cf9e2b948ee8780c4b244c2397",
          "sha1": "353afd8aa144c006009fdf0b5a32600540159da4",
          "md5": "31ee30c805b8302d0c0641e8031e6eeb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.1.jar",
          "url": "prompt-cache-files-jvm-0.3.0.1.jar",
          "size": 18446,
          "sha512": "5ea3a3e2c520dfe4e9f13a6d1285c1fe961c044cd38e02786d0e8774b76b078f99f76342b093cfe438e722f763c17bf8679d137aeaaff33fe9101aefe16e8fcc",
          "sha256": "38f281321d188d58562e64641208edf10fb0f2cf9e2b948ee8780c4b244c2397",
          "sha1": "353afd8aa144c006009fdf0b5a32600540159da4",
          "md5": "31ee30c805b8302d0c0641e8031e6eeb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.1-sources.jar",
          "url": "prompt-cache-files-jvm-0.3.0.1-sources.jar",
          "size": 2970,
          "sha512": "225e701a8d054eb310e1f54889e8e68fdcb0aaf51e702409a08c8162aafefdff3698b29b2da15a9a9bfd484569ac06dbc1f7d291735abd98ca8ffe1074ce00ad",
          "sha256": "24caa2d9e7873d46b6f06398ea09dc2d9fb7e061fa6f3e12a20947d60b5737e2",
          "sha1": "8feee901ecb03e2ac8da3c1ead9a9076a3eb1a66",
          "md5": "2fe549439e3f4bc97428a3f378038020"
        }
      ]
    }
  ]
}
