{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-debugger/0.3.0.4/agents-features-debugger-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-features-debugger",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.4.jar",
          "url": "agents-features-debugger-jvm-0.3.0.4.jar",
          "size": 40097,
          "sha512": "4b1879b04168c84ade356c9ebf38e8893c8d3a48bdab38bea9fa978bb6168b362d49b95965996b874cbe6253c7301266ac797b2bae6c3102e013c319502ec688",
          "sha256": "6132d8ed4c3a972bea51d77a9db84fb4aeb9e0e20be8e03dc182866690c1c248",
          "sha1": "e8c5f3367055e9402e8c1f2ff8abeda3b8ee395b",
          "md5": "7b63271786a3d3f8e7197d4553f05752"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.4.jar",
          "url": "agents-features-debugger-jvm-0.3.0.4.jar",
          "size": 40097,
          "sha512": "4b1879b04168c84ade356c9ebf38e8893c8d3a48bdab38bea9fa978bb6168b362d49b95965996b874cbe6253c7301266ac797b2bae6c3102e013c319502ec688",
          "sha256": "6132d8ed4c3a972bea51d77a9db84fb4aeb9e0e20be8e03dc182866690c1c248",
          "sha1": "e8c5f3367055e9402e8c1f2ff8abeda3b8ee395b",
          "md5": "7b63271786a3d3f8e7197d4553f05752"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.4-sources.jar",
          "url": "agents-features-debugger-jvm-0.3.0.4-sources.jar",
          "size": 7023,
          "sha512": "5dc2afba255c6b20c5ef4f439fc42ab379e82c73fe64c5a626e0d6a08db014a22151a622ec2a61926d133b5e6eeceb1fc575bd7b0254c32668ada5e3a1044581",
          "sha256": "8220f7a766e96e9077393e7054d4d4d7858a79f21d46c9d8ad582b68930b054b",
          "sha1": "ddd2f5ef0a82df38ef51e06e88cdfe7584cd7d41",
          "md5": "2872ec13c1db303e6b83643968219a92"
        }
      ]
    }
  ]
}
