{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-openai-client/0.3.0.1/prompt-executor-openai-client-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-openai-client",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-js-0.3.0.1.klib",
          "url": "prompt-executor-openai-client-js-0.3.0.1.klib",
          "size": 204765,
          "sha512": "e52fbb0dceb04472b9747fbc54848ca5a9b45e55fbfb5ad9ebab3be5466a8e02b07c5597505179e3f556960ac49072c8338b88f7cc03698da71dc8bd49c6fd64",
          "sha256": "85663fe7e634686ba8121cabf8466745a941ff864cd5056127016517d804fc23",
          "sha1": "9f0977c4dfdf0a48ff30d1745dd5fbaa9889d2e5",
          "md5": "190149192e40ea6040a5a103eb25a61e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-js-0.3.0.1.klib",
          "url": "prompt-executor-openai-client-js-0.3.0.1.klib",
          "size": 204765,
          "sha512": "e52fbb0dceb04472b9747fbc54848ca5a9b45e55fbfb5ad9ebab3be5466a8e02b07c5597505179e3f556960ac49072c8338b88f7cc03698da71dc8bd49c6fd64",
          "sha256": "85663fe7e634686ba8121cabf8466745a941ff864cd5056127016517d804fc23",
          "sha1": "9f0977c4dfdf0a48ff30d1745dd5fbaa9889d2e5",
          "md5": "190149192e40ea6040a5a103eb25a61e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-executor-openai-client-js-0.3.0.1-sources.jar",
          "url": "prompt-executor-openai-client-js-0.3.0.1-sources.jar",
          "size": 20550,
          "sha512": "eb207455e0c11a904a85bc4567c06cae93de3a17c5046ffe95655b85c4de9f2223741f14793cebd1371d80bd6fc72ca205d85fab909cfe10f8a7bb0ff0f16a5e",
          "sha256": "d0fed419aa2f8cde848a4d225fdffc7885caf690740968b3fcfdea652ff84a90",
          "sha1": "e77d4b843dcfed216631a3d44b410b43d623b88f",
          "md5": "4604dee07dbc0e7e46f4e01503ef01bd"
        }
      ]
    }
  ]
}
