{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-tools/0.3.0.1/agents-tools-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-tools",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-js-0.3.0.1.klib",
          "url": "agents-tools-js-0.3.0.1.klib",
          "size": 60388,
          "sha512": "eb349e091ef79589f3048821f3fe509949f218d7e52d480edb49204a8eb19f359a64c0ed59ad337da517ada1f8bbebc60ec7b293928fba1e673cf8337a7f3052",
          "sha256": "c597116c0e696b724c0b7ed4b7ebb90b9b0e966decd866debeb357b4073a9ab6",
          "sha1": "bf7d11084af6a15720f9e0d66777cbc12588c6c0",
          "md5": "9e369b5d7b831c6e67eee6633e67be39"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-js-0.3.0.1.klib",
          "url": "agents-tools-js-0.3.0.1.klib",
          "size": 60388,
          "sha512": "eb349e091ef79589f3048821f3fe509949f218d7e52d480edb49204a8eb19f359a64c0ed59ad337da517ada1f8bbebc60ec7b293928fba1e673cf8337a7f3052",
          "sha256": "c597116c0e696b724c0b7ed4b7ebb90b9b0e966decd866debeb357b4073a9ab6",
          "sha1": "bf7d11084af6a15720f9e0d66777cbc12588c6c0",
          "md5": "9e369b5d7b831c6e67eee6633e67be39"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "agents-tools-js-0.3.0.1-sources.jar",
          "url": "agents-tools-js-0.3.0.1-sources.jar",
          "size": 13742,
          "sha512": "e2a231dbece19c5b08198ed82adbd4319af0a9b21183b7f5187b1e986bc0ad128768ab215756de48b9c1a53e13b41a8465a6d63e77ab4577e3bd25db9c46e8b1",
          "sha256": "1eb52535c8cf5e3227fe5fb4d5b13cc3134c3c1c6aaa4f4cdfd65ffd99d233d8",
          "sha1": "db0d9085ba34fc983456704d7e524377710cccfe",
          "md5": "3df497359ac76300dae97067eabcdb6e"
        }
      ]
    }
  ]
}
