{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-tokenizer/0.3.0.4/agents-features-tokenizer-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-features-tokenizer",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-js-0.3.0.4.klib",
          "url": "agents-features-tokenizer-js-0.3.0.4.klib",
          "size": 9470,
          "sha512": "4b595fa875687f464679fb91150f2fc9de96ee4031f3dc7f878171d19c9039e36f8924100ff6b491691ea3dca548b08970a961ab3aed84b891049c0a0ea396aa",
          "sha256": "ffba12693036abca26e8c17c71ebbba28f747728e2be8152193477b3df8f0f53",
          "sha1": "0b36f567a9eb65a9848119faa851cb05e6d4f032",
          "md5": "8ddaaee205c28717cdccf62e325e4ab6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-js-0.3.0.4.klib",
          "url": "agents-features-tokenizer-js-0.3.0.4.klib",
          "size": 9470,
          "sha512": "4b595fa875687f464679fb91150f2fc9de96ee4031f3dc7f878171d19c9039e36f8924100ff6b491691ea3dca548b08970a961ab3aed84b891049c0a0ea396aa",
          "sha256": "ffba12693036abca26e8c17c71ebbba28f747728e2be8152193477b3df8f0f53",
          "sha1": "0b36f567a9eb65a9848119faa851cb05e6d4f032",
          "md5": "8ddaaee205c28717cdccf62e325e4ab6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "agents-features-tokenizer-js-0.3.0.4-sources.jar",
          "url": "agents-features-tokenizer-js-0.3.0.4-sources.jar",
          "size": 4408,
          "sha512": "971fd1dcbbf34e351e5973cce924aa7af2fbfb01872a7476a60547b7c51cddc73f5bdbf0dfc86d203a6fc62c18894d33dfe7ad4bba33e7dc2178b0d773d45b73",
          "sha256": "f4a8dba2f14c54d1ee0842b49bfd48a93017528e79727bbf5b74304dd0d41c21",
          "sha1": "ca5e50b9cdd1b782ff14f94f3e93c081f4fc4220",
          "md5": "52b3d625bed4a02e0aafba87682b43d5"
        }
      ]
    }
  ]
}
