{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-opentelemetry/0.3.0.1/agents-features-opentelemetry-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-opentelemetry",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-bom",
          "version": {
            "requires": "1.51.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk"
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-opentelemetry-jvm-0.3.0.1.jar",
          "url": "agents-features-opentelemetry-jvm-0.3.0.1.jar",
          "size": 234078,
          "sha512": "058c2ae1bc713ca0f74b7ba99f04e09fc2841aff953361da75056574fbd512c0e20bf333235fc1090b72777eebf38b7cd51e35c631e723f91c9d0b31ff3ba5fe",
          "sha256": "11ce518f536c17f79eafc11e739864782b6dceed047705d283206afcf4b2fd3e",
          "sha1": "26ac18cb48f24cc7924ee90fd550fe4bc1e73e66",
          "md5": "6787b9701bb7505a441cbed39805b8ed"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-bom",
          "version": {
            "requires": "1.51.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk"
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp"
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-logging"
        }
      ],
      "files": [
        {
          "name": "agents-features-opentelemetry-jvm-0.3.0.1.jar",
          "url": "agents-features-opentelemetry-jvm-0.3.0.1.jar",
          "size": 234078,
          "sha512": "058c2ae1bc713ca0f74b7ba99f04e09fc2841aff953361da75056574fbd512c0e20bf333235fc1090b72777eebf38b7cd51e35c631e723f91c9d0b31ff3ba5fe",
          "sha256": "11ce518f536c17f79eafc11e739864782b6dceed047705d283206afcf4b2fd3e",
          "sha1": "26ac18cb48f24cc7924ee90fd550fe4bc1e73e66",
          "md5": "6787b9701bb7505a441cbed39805b8ed"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-opentelemetry-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-opentelemetry-jvm-0.3.0.1-sources.jar",
          "size": 34459,
          "sha512": "e81e08e1fdba0ec975c91f1d1c19733f4e28d5e1e6e396272787b042d829f545fcc18e38d196f4339c051af798cba308d1d2f8227efb131b2443199d9d00cecf",
          "sha256": "30e8ad4d4678e424095f1608da1242bc96f1e79a1d1c2ef711819453ad1a4202",
          "sha1": "7187650008d9ac0d20f624e76c1ac61d0248d632",
          "md5": "03107b2f99a4e8edb6d8009e79abd325"
        }
      ]
    }
  ]
}
