{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-ktor/0.3.0.2/koog-ktor-0.3.0.2.module",
    "group": "ai.koog",
    "module": "koog-ktor",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.2.jar",
          "url": "koog-ktor-jvm-0.3.0.2.jar",
          "size": 67495,
          "sha512": "f3804ced661c49209aa76df695dc1ef456e35d12d18c798ba7eab3d0a426b692649a510fff2dbbc38c1691b03df41f8314f5a96dfa1ef2ec918c3db4d35b8bc3",
          "sha256": "ce2176d8c6197b7238fc56e2c2a638a22da9606930f5eab3efbe0d9327a60f28",
          "sha1": "eb50cffb07f903272b5dadfd75a511c2be3fc179",
          "md5": "a47fb83acebe2db5f81ec974edd115fa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.2.jar",
          "url": "koog-ktor-jvm-0.3.0.2.jar",
          "size": 67495,
          "sha512": "f3804ced661c49209aa76df695dc1ef456e35d12d18c798ba7eab3d0a426b692649a510fff2dbbc38c1691b03df41f8314f5a96dfa1ef2ec918c3db4d35b8bc3",
          "sha256": "ce2176d8c6197b7238fc56e2c2a638a22da9606930f5eab3efbe0d9327a60f28",
          "sha1": "eb50cffb07f903272b5dadfd75a511c2be3fc179",
          "md5": "a47fb83acebe2db5f81ec974edd115fa"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.2-sources.jar",
          "url": "koog-ktor-jvm-0.3.0.2-sources.jar",
          "size": 18184,
          "sha512": "2ce30654581889b1de588c32e98bf110656e94af8ee24ab7e6dd69cfe1bb7853b0c4bb8b6acdce99bd9c17912f7947d09712d9f4e73cc69b70180a2fb3557f96",
          "sha256": "bec4ade9a93f5da6d32b87975a041c4e3f3d58b321a39fec98e1c8ac6122aae3",
          "sha1": "c4e18eed216dfcb529d1c29b1a5c3a265d40b825",
          "md5": "8c588c83735ca65e5b5ac4641b817b33"
        }
      ]
    }
  ]
}
