{
  "formatVersion": "1.1",
  "component": {
    "url": "../../embeddings-base/0.3.0.2/embeddings-base-0.3.0.2.module",
    "group": "ai.koog",
    "module": "embeddings-base",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.2.jar",
          "url": "embeddings-base-jvm-0.3.0.2.jar",
          "size": 9722,
          "sha512": "716f0ea187058964706edee531104dcbf027cd6bebb681ba48149c35a0ef28540a1e4a02a9bb336d58b735572ca0fc86c5141537552f01d6eb2255c684a739a1",
          "sha256": "862acd9cdc9a3641abb557e545dd8204544dbbc032f802a869fe6368a0015aac",
          "sha1": "32671076177093e0c49722c67fc16975058d5252",
          "md5": "e096849699ed1323f8546e47dd987ea9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.2.jar",
          "url": "embeddings-base-jvm-0.3.0.2.jar",
          "size": 9722,
          "sha512": "716f0ea187058964706edee531104dcbf027cd6bebb681ba48149c35a0ef28540a1e4a02a9bb336d58b735572ca0fc86c5141537552f01d6eb2255c684a739a1",
          "sha256": "862acd9cdc9a3641abb557e545dd8204544dbbc032f802a869fe6368a0015aac",
          "sha1": "32671076177093e0c49722c67fc16975058d5252",
          "md5": "e096849699ed1323f8546e47dd987ea9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "embeddings-base-jvm-0.3.0.2-sources.jar",
          "url": "embeddings-base-jvm-0.3.0.2-sources.jar",
          "size": 2866,
          "sha512": "e81dfdb729687f3ad3e8fa95ff68071a2110bcc0cac9b1ccc7b540294c7b727b6a5a936d6a30ecaf2e00271cae521bc83fee28d3a603cd293aea42993299e10b",
          "sha256": "fb733ac421cc959291dd802d0a4f62ea02d187d38b6ba657d53a3f4bc3c7199d",
          "sha1": "2aec73c029fe70e9c2cbb65df91fc875ab28280e",
          "md5": "a47ba90ec1994339e340b7926f4e5bef"
        }
      ]
    }
  ]
}
