{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-llms-all/0.3.0.4/prompt-executor-llms-all-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-llms-all",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-all-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-llms-all-wasm-js-0.3.0.4.klib",
          "size": 6766,
          "sha512": "c8a6cc8e09f7fe5af4e5c49bcdd463da9829b5cb34a39260d9cb3b4b60827ebf32ea005ba56276095d1b6a17ab5b314e59bb3d8a63056af51e8ad5ac6e9c0688",
          "sha256": "1473283ce2e9994c25eedd22a5e1b759b9a261a61e7a4c8edda5eb84c5cae531",
          "sha1": "af20760c96f2d6e4ad03a86a150a547c13a88dcb",
          "md5": "b787cbb5736e0c14b3f3528ec6ab2f33"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-all-wasm-js-0.3.0.4.klib",
          "url": "prompt-executor-llms-all-wasm-js-0.3.0.4.klib",
          "size": 6766,
          "sha512": "c8a6cc8e09f7fe5af4e5c49bcdd463da9829b5cb34a39260d9cb3b4b60827ebf32ea005ba56276095d1b6a17ab5b314e59bb3d8a63056af51e8ad5ac6e9c0688",
          "sha256": "1473283ce2e9994c25eedd22a5e1b759b9a261a61e7a4c8edda5eb84c5cae531",
          "sha1": "af20760c96f2d6e4ad03a86a150a547c13a88dcb",
          "md5": "b787cbb5736e0c14b3f3528ec6ab2f33"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-executor-llms-all-wasm-js-0.3.0.4-sources.jar",
          "url": "prompt-executor-llms-all-wasm-js-0.3.0.4-sources.jar",
          "size": 2670,
          "sha512": "9c576d6b3cb228f62ef406cd79002175a06556b116c16e4fd932841750c8fc474bdd27d09f2d0907bf8dff68b323eed1f338eebf15bf86a0bd2af41fe1662461",
          "sha256": "825cc2d23d6ed22ccdf40d0df3a956e791044ae908e9c5c6393bf396623acb32",
          "sha1": "a407a4b895a240d6b0a108be748e4c2b57c7f615",
          "md5": "cd5c0d58c81b75be66157aa3c5ca2bff"
        }
      ]
    }
  ]
}
