{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-ktor/0.3.0.4/koog-ktor-0.3.0.4.module",
    "group": "ai.koog",
    "module": "koog-ktor",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.4.jar",
          "url": "koog-ktor-jvm-0.3.0.4.jar",
          "size": 67495,
          "sha512": "3188f8e21fb6ff35aae7e8c4d0a67f9e9443afa6b4f7f3865c2e7d9ea30fd70ee4cb1c733827e3f1d7e3e797959bb73d20a36fd6dcd5222a65628d156d31fe8f",
          "sha256": "197bdb294b3be6dbbb1a957e0c5030f93291b0a6f2ef39c69cee20dcb34216cb",
          "sha1": "76bc3d04860c4d8b7f175add52de642ab8ac4316",
          "md5": "b44983d646c8186c39476b25261f3ff3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.4.jar",
          "url": "koog-ktor-jvm-0.3.0.4.jar",
          "size": 67495,
          "sha512": "3188f8e21fb6ff35aae7e8c4d0a67f9e9443afa6b4f7f3865c2e7d9ea30fd70ee4cb1c733827e3f1d7e3e797959bb73d20a36fd6dcd5222a65628d156d31fe8f",
          "sha256": "197bdb294b3be6dbbb1a957e0c5030f93291b0a6f2ef39c69cee20dcb34216cb",
          "sha1": "76bc3d04860c4d8b7f175add52de642ab8ac4316",
          "md5": "b44983d646c8186c39476b25261f3ff3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.4-sources.jar",
          "url": "koog-ktor-jvm-0.3.0.4-sources.jar",
          "size": 18184,
          "sha512": "2ce30654581889b1de588c32e98bf110656e94af8ee24ab7e6dd69cfe1bb7853b0c4bb8b6acdce99bd9c17912f7947d09712d9f4e73cc69b70180a2fb3557f96",
          "sha256": "bec4ade9a93f5da6d32b87975a041c4e3f3d58b321a39fec98e1c8ac6122aae3",
          "sha1": "c4e18eed216dfcb529d1c29b1a5c3a265d40b825",
          "md5": "8c588c83735ca65e5b5ac4641b817b33"
        }
      ]
    }
  ]
}
