{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-llms/0.3.0.1/prompt-executor-llms-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-llms",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-wasm-js-0.3.0.1.klib",
          "url": "prompt-executor-llms-wasm-js-0.3.0.1.klib",
          "size": 16419,
          "sha512": "9bfa91688e13d6aab9575a5332240ca1cd7febfdd3e41421d4da82d4673f6386a188955ac88b5c0e09409a18e431faf845f4d83ef8cbbc28e8aa367040b0c541",
          "sha256": "14058778f720b71124650958f748d02ec9cf75a1fcbf4de386ac2c1585f523d7",
          "sha1": "a0c97be95fa39b5946142f9499e6b6d07a1d47f0",
          "md5": "b359e087c9dec5d9821b33d9c2b9c731"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-wasm-js-0.3.0.1.klib",
          "url": "prompt-executor-llms-wasm-js-0.3.0.1.klib",
          "size": 16419,
          "sha512": "9bfa91688e13d6aab9575a5332240ca1cd7febfdd3e41421d4da82d4673f6386a188955ac88b5c0e09409a18e431faf845f4d83ef8cbbc28e8aa367040b0c541",
          "sha256": "14058778f720b71124650958f748d02ec9cf75a1fcbf4de386ac2c1585f523d7",
          "sha1": "a0c97be95fa39b5946142f9499e6b6d07a1d47f0",
          "md5": "b359e087c9dec5d9821b33d9c2b9c731"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-executor-llms-wasm-js-0.3.0.1-sources.jar",
          "url": "prompt-executor-llms-wasm-js-0.3.0.1-sources.jar",
          "size": 4662,
          "sha512": "a2abccd591a749f639d52684fbc65a7b96f8a0c1c214ae427f0ac87759e2e83b13beed6cbbd4561d96ab91dfa66c9a1a47e0bbe5c63f51a7c5209e0e6b8716c6",
          "sha256": "4e770f73bfb17387fa9e05bdc70731a08c3edde3741e2a12a7de7e097f810725",
          "sha1": "e8449b0d6bfa6915d7002b94fa833b675ddeb23e",
          "md5": "5427be1e4d7344e38e3c534142e91e13"
        }
      ]
    }
  ]
}
