{
  "formatVersion": "1.1",
  "component": {
    "url": "../../vector-storage/0.3.0.3/vector-storage-0.3.0.3.module",
    "group": "ai.koog",
    "module": "vector-storage",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.3.jar",
          "url": "vector-storage-jvm-0.3.0.3.jar",
          "size": 53333,
          "sha512": "d6521f9c8d8fd00cc683427bc56ab8e04c177beafd37c0623a700e6f6d5b4a482173fab976f7f440513d4bbebf7c7d208b823eba169179f6bcd355fa64ca402a",
          "sha256": "8d5a27961158564af5ee96043453597f99113e42f98adf1041c6766efee56830",
          "sha1": "e4ee1d22200154587fb65cbec9497bd3f18c6c47",
          "md5": "2f9b5f62639fdece4c604d30228a5fcf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.3.jar",
          "url": "vector-storage-jvm-0.3.0.3.jar",
          "size": 53333,
          "sha512": "d6521f9c8d8fd00cc683427bc56ab8e04c177beafd37c0623a700e6f6d5b4a482173fab976f7f440513d4bbebf7c7d208b823eba169179f6bcd355fa64ca402a",
          "sha256": "8d5a27961158564af5ee96043453597f99113e42f98adf1041c6766efee56830",
          "sha1": "e4ee1d22200154587fb65cbec9497bd3f18c6c47",
          "md5": "2f9b5f62639fdece4c604d30228a5fcf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.3-sources.jar",
          "url": "vector-storage-jvm-0.3.0.3-sources.jar",
          "size": 9535,
          "sha512": "642543700c43474042857bc9e43c898519697815245213a476671dfeca8c8eed6f977b2079d4069d903ed08e25deca7b90c051b227696ab15f8213419d1b70c6",
          "sha256": "32ce7d7b209bb9b9444351e44a212bb9c081c8f7224e9b7094c774c331cebc95",
          "sha1": "589ba1df5e485fa3c2b15a2a983e471fd3eb734e",
          "md5": "fd7a65689a0264a649b0400125653678"
        }
      ]
    }
  ]
}
