{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-utils/0.3.0.3/agents-utils-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-utils",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-wasm-js-0.3.0.3.klib",
          "url": "agents-utils-wasm-js-0.3.0.3.klib",
          "size": 5072,
          "sha512": "37d72d082ba3394fafee50162de9e5e059995241526bb4fdc3679f464e0aa97efdf62a0722d379cc37feacd768acce6c93fd16f0d360ba84a5d815851ac3ecd4",
          "sha256": "af49a2ac089e837cde4c4178534964363624aa04892e94fa535465188d156133",
          "sha1": "4f6abd7ac49e691979e891f6b59ca026db1e006d",
          "md5": "968be5bc599e40e05be7aaf07e2a20c4"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-wasm-js-0.3.0.3.klib",
          "url": "agents-utils-wasm-js-0.3.0.3.klib",
          "size": 5072,
          "sha512": "37d72d082ba3394fafee50162de9e5e059995241526bb4fdc3679f464e0aa97efdf62a0722d379cc37feacd768acce6c93fd16f0d360ba84a5d815851ac3ecd4",
          "sha256": "af49a2ac089e837cde4c4178534964363624aa04892e94fa535465188d156133",
          "sha1": "4f6abd7ac49e691979e891f6b59ca026db1e006d",
          "md5": "968be5bc599e40e05be7aaf07e2a20c4"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-utils-wasm-js-0.3.0.3-sources.jar",
          "url": "agents-utils-wasm-js-0.3.0.3-sources.jar",
          "size": 3021,
          "sha512": "267adec89b3d0805d12b391371cc89a0c94907aedf94adbf27294a9a4d176d6add7b61a559992df2f4c488ac912b88f2a1c151ee534520aacbff9aa1f98306dd",
          "sha256": "4ca5721836e4e7a0561b4b1800736cb3e9724d60febf6efa20b3e712fbd4d7ea",
          "sha1": "a21f3a61b2b1e94c963cab1a351eed86728401fe",
          "md5": "a3f8ba761f8cf157110f19927cd8575e"
        }
      ]
    }
  ]
}
