{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-model/0.3.0.1/prompt-model-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-model",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-model-js-0.3.0.1.klib",
          "url": "prompt-model-js-0.3.0.1.klib",
          "size": 148188,
          "sha512": "828e858716d2d7396c1504963eba79449ce1e97d6a2f47ccb10f2b475ba3142dccc765cb75a25ffc3a2095b73edbc274c4f9ff8fa49945a1967a8b6507781f94",
          "sha256": "6c9fbd30c6a341a310c6a56ed31a2979aaca182ed5707bf6f6cceb85acd1a2fa",
          "sha1": "81acd94d5d65bb265a32e8130827f6933de1bbad",
          "md5": "af6f3a05d57f1303d2afd5e7c8784594"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-model-js-0.3.0.1.klib",
          "url": "prompt-model-js-0.3.0.1.klib",
          "size": 148188,
          "sha512": "828e858716d2d7396c1504963eba79449ce1e97d6a2f47ccb10f2b475ba3142dccc765cb75a25ffc3a2095b73edbc274c4f9ff8fa49945a1967a8b6507781f94",
          "sha256": "6c9fbd30c6a341a310c6a56ed31a2979aaca182ed5707bf6f6cceb85acd1a2fa",
          "sha1": "81acd94d5d65bb265a32e8130827f6933de1bbad",
          "md5": "af6f3a05d57f1303d2afd5e7c8784594"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-model-js-0.3.0.1-sources.jar",
          "url": "prompt-model-js-0.3.0.1-sources.jar",
          "size": 23155,
          "sha512": "4fb60df4474fc8703f047ea4db25124816fa04b6d76e26f896b69518933837680e323e80244a6a6502861f90e1fe67db43827e0299aab733163645a5a523221a",
          "sha256": "89c8cd95a871324e1479da14338271fb0a2988273b418ddb15fe98b3661371ad",
          "sha1": "658cd777d8ce3b4aacc0f7f45f13ef1206e29bc2",
          "md5": "018220825a68820ac0cd76ea2a88065f"
        }
      ]
    }
  ]
}
