{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-bedrock-client/0.3.0.2/prompt-executor-bedrock-client-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-executor-bedrock-client",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.2.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.2.jar",
          "size": 290673,
          "sha512": "83244def05875a4835a234a31cafbddb130cbb83a7848ca222947835aaa4e5b5ce8b10680640931f110a2831b02579c65b179e30ef3f83284c3d0471d807b785",
          "sha256": "25b772d1f78f7e0c9c45db3f35ce38c4d6fb7d0a7cd6fedcb6ba3ff240d3d03f",
          "sha1": "5a6b1cc766b914fd9ff747a68d98fb2b5085e534",
          "md5": "4f138a1c1d037bce5a86e98526804f12"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "bedrockruntime",
          "version": {
            "requires": "1.4.119"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.2.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.2.jar",
          "size": 290673,
          "sha512": "83244def05875a4835a234a31cafbddb130cbb83a7848ca222947835aaa4e5b5ce8b10680640931f110a2831b02579c65b179e30ef3f83284c3d0471d807b785",
          "sha256": "25b772d1f78f7e0c9c45db3f35ce38c4d6fb7d0a7cd6fedcb6ba3ff240d3d03f",
          "sha1": "5a6b1cc766b914fd9ff747a68d98fb2b5085e534",
          "md5": "4f138a1c1d037bce5a86e98526804f12"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.2-sources.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.2-sources.jar",
          "size": 21720,
          "sha512": "9491a6d22dbb050efc7c66dd6556b4b1c1966c44eb025cf8ec7459f3c35683c2542ee5c314ef771081cdb6fa5411e259627b3bd273f1a68f0383db6f5f46cb2c",
          "sha256": "6f6760b0034fe7d0a45718664d16df8414ef65470134e82b428ab4859618de73",
          "sha1": "122e4131eb414dc1162c07c1f4f21c428dfec868",
          "md5": "59bf77a0e01412f82fade43bc23b0278"
        }
      ]
    }
  ]
}
