{
  "formatVersion": "1.1",
  "component": {
    "url": "../../vector-storage/0.3.0.3/vector-storage-0.3.0.3.module",
    "group": "ai.koog",
    "module": "vector-storage",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-wasm-js-0.3.0.3.klib",
          "url": "vector-storage-wasm-js-0.3.0.3.klib",
          "size": 22812,
          "sha512": "599ea9955084f9208e40110a4286b3246c6e3ba357b8e242e8aa8d08a7a1b3b6d36b09df95356cd9571c3819bc5616699336e96ac32e8bf288723ce93e4c445f",
          "sha256": "aef6072276fe46b2221c5806820e9d3f1a66663acba4fc56113b30bfe9b3e351",
          "sha1": "439ba8ad77fc0b57af638c8ca3949fe552e01866",
          "md5": "789849c8bdd249921c6470f88252070f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-wasm-js-0.3.0.3.klib",
          "url": "vector-storage-wasm-js-0.3.0.3.klib",
          "size": 22812,
          "sha512": "599ea9955084f9208e40110a4286b3246c6e3ba357b8e242e8aa8d08a7a1b3b6d36b09df95356cd9571c3819bc5616699336e96ac32e8bf288723ce93e4c445f",
          "sha256": "aef6072276fe46b2221c5806820e9d3f1a66663acba4fc56113b30bfe9b3e351",
          "sha1": "439ba8ad77fc0b57af638c8ca3949fe552e01866",
          "md5": "789849c8bdd249921c6470f88252070f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "vector-storage-wasm-js-0.3.0.3-sources.jar",
          "url": "vector-storage-wasm-js-0.3.0.3-sources.jar",
          "size": 7072,
          "sha512": "1b28750be2afefc93e809c213033148788137c74ef0784bc0b03612d6e099e60d1a58b9bf9516fbfad2c0a2fe89896b893340bcbf259ea8e69f24c35fc0e0395",
          "sha256": "843db04f564a52c041a1f994b116d092da20adea251fd0f4f5e3d9c579efc180",
          "sha1": "6dfdb9ea71a91879c8e8a8f80e8910607f3ca0ed",
          "md5": "4b4f8219b256e8c804e0a2e2ba953695"
        }
      ]
    }
  ]
}
