{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-llms/0.3.0.1/prompt-executor-llms-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-llms",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.1.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.1.jar",
          "size": 24152,
          "sha512": "1194f64fc82373f373c93d68d4336212f1ba852b70bf4d0f3571bf408825b3362d3eac60dd88678d7aab5eea75d65c182cabf8157a1e2b4206814682b95db141",
          "sha256": "b7334c8e793ec6f48ba8013876d8e11f374c90d30ce23d57ad6c5e525b331a19",
          "sha1": "2a36e1c1dc2e6ed52063560f43fb3ddce5d72c5e",
          "md5": "8b24b47fd364a57e5ed12e2ce1294409"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.1.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.1.jar",
          "size": 24152,
          "sha512": "1194f64fc82373f373c93d68d4336212f1ba852b70bf4d0f3571bf408825b3362d3eac60dd88678d7aab5eea75d65c182cabf8157a1e2b4206814682b95db141",
          "sha256": "b7334c8e793ec6f48ba8013876d8e11f374c90d30ce23d57ad6c5e525b331a19",
          "sha1": "2a36e1c1dc2e6ed52063560f43fb3ddce5d72c5e",
          "md5": "8b24b47fd364a57e5ed12e2ce1294409"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-llms-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-llms-jvm-0.3.0.1-sources.jar",
          "size": 4662,
          "sha512": "a2abccd591a749f639d52684fbc65a7b96f8a0c1c214ae427f0ac87759e2e83b13beed6cbbd4561d96ab91dfa66c9a1a47e0bbe5c63f51a7c5209e0e6b8716c6",
          "sha256": "4e770f73bfb17387fa9e05bdc70731a08c3edde3741e2a12a7de7e097f810725",
          "sha1": "e8449b0d6bfa6915d7002b94fa833b675ddeb23e",
          "md5": "5427be1e4d7344e38e3c534142e91e13"
        }
      ]
    }
  ]
}
