{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-core/0.3.0.4/agents-core-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-core",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-core-wasm-js-0.3.0.4.klib",
          "url": "agents-core-wasm-js-0.3.0.4.klib",
          "size": 584578,
          "sha512": "edd2bffaabfdc1fd5227e015fc90b3f397c8e2b4e5f89152a77bb67265dabb1aa34bcca31a089bd69c4c91ea965cdb2ee63ea5d00afd1d096ba95d77a0e00748",
          "sha256": "b8d2045ec39a58b4ca1582fd8a6d89f8b071f65f2f41c84ce8749347613f414c",
          "sha1": "2476926a8df7444fe2396897e052a9aee71d4d1c",
          "md5": "b6a7a1fb3f363d204c4cde5d19d80013"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "agents-core-wasm-js-0.3.0.4.klib",
          "url": "agents-core-wasm-js-0.3.0.4.klib",
          "size": 584578,
          "sha512": "edd2bffaabfdc1fd5227e015fc90b3f397c8e2b4e5f89152a77bb67265dabb1aa34bcca31a089bd69c4c91ea965cdb2ee63ea5d00afd1d096ba95d77a0e00748",
          "sha256": "b8d2045ec39a58b4ca1582fd8a6d89f8b071f65f2f41c84ce8749347613f414c",
          "sha1": "2476926a8df7444fe2396897e052a9aee71d4d1c",
          "md5": "b6a7a1fb3f363d204c4cde5d19d80013"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-core-wasm-js-0.3.0.4-sources.jar",
          "url": "agents-core-wasm-js-0.3.0.4-sources.jar",
          "size": 167421,
          "sha512": "4bd73cca6b9c5a0a53ea82da37827b40f02cb82115bf399e5dfbd90bf555ebd09f0cb0b167d17ea096b316dacc849505677e6e0eaa94773c2ef4eb537b51a5b1",
          "sha256": "c3c298e6cb55527240e78debac760fd2e155e45e86ed4ad4d28fcfa515266764",
          "sha1": "b5ee1293083dbbb653a1a34bf02c61ec768a9da9",
          "md5": "491066777f62b2313b9078e5e62d789e"
        }
      ]
    }
  ]
}
