{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-test/0.3.0.3/agents-test-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-test",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-test-jvm-0.3.0.3.jar",
          "url": "agents-test-jvm-0.3.0.3.jar",
          "size": 159032,
          "sha512": "5558ce96f1aa1bc912bb7756591495dfb8ed874e63b47b999ff16eb72a3cc65d5c7ae33a6d5c9deae8abf515098ca952157f003ef3b4045358254481748e69db",
          "sha256": "b4e1d88ef438f6ae28084f1033f01b5edabd18620e4a6dd150cacfb6367a07cd",
          "sha1": "cfb9a2aaff1a4e79d5feabd68601a8ac7d552024",
          "md5": "86d3f1025527c89f7bfd4c903598a524"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-test-jvm-0.3.0.3.jar",
          "url": "agents-test-jvm-0.3.0.3.jar",
          "size": 159032,
          "sha512": "5558ce96f1aa1bc912bb7756591495dfb8ed874e63b47b999ff16eb72a3cc65d5c7ae33a6d5c9deae8abf515098ca952157f003ef3b4045358254481748e69db",
          "sha256": "b4e1d88ef438f6ae28084f1033f01b5edabd18620e4a6dd150cacfb6367a07cd",
          "sha1": "cfb9a2aaff1a4e79d5feabd68601a8ac7d552024",
          "md5": "86d3f1025527c89f7bfd4c903598a524"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-test-jvm-0.3.0.3-sources.jar",
          "url": "agents-test-jvm-0.3.0.3-sources.jar",
          "size": 37981,
          "sha512": "83eeb08644f31b04a16eccf9672273b2229c67ab6f85932db184fbfa67dc7cf23bf1050d74f211cbc781da31068e1fb8a9d852c45c74c857df1e02bd881e6fbe",
          "sha256": "9caf661e8651e8028463fb92efa31ed9398f35fd614d1e41fab4984d704e548a",
          "sha1": "c8e273daee8cfc59aba23f10f8a72ccff263ac97",
          "md5": "6af396a09e4b999954a43027cd332e0d"
        }
      ]
    }
  ]
}
