{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-llm/0.3.0.2/prompt-llm-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-llm",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-js-0.3.0.2.klib",
          "url": "prompt-llm-js-0.3.0.2.klib",
          "size": 38050,
          "sha512": "f28108072ac74147a442b10a8f0f9de1c6960cb1089226728950c2e4f169b62cc352170e478869a1b75095af7f3ec77919b922ee9504043c56d322b00279f8df",
          "sha256": "a1c66190a9d781df85aeb86784ce9d6aeebe6f928a546766cea1bc2adc1594a6",
          "sha1": "3aa5da31e336ed964cde9bb980778f8a97c4de6b",
          "md5": "0ce06da827efae46168d7955e039cfcc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-js-0.3.0.2.klib",
          "url": "prompt-llm-js-0.3.0.2.klib",
          "size": 38050,
          "sha512": "f28108072ac74147a442b10a8f0f9de1c6960cb1089226728950c2e4f169b62cc352170e478869a1b75095af7f3ec77919b922ee9504043c56d322b00279f8df",
          "sha256": "a1c66190a9d781df85aeb86784ce9d6aeebe6f928a546766cea1bc2adc1594a6",
          "sha1": "3aa5da31e336ed964cde9bb980778f8a97c4de6b",
          "md5": "0ce06da827efae46168d7955e039cfcc"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-llm-js-0.3.0.2-sources.jar",
          "url": "prompt-llm-js-0.3.0.2-sources.jar",
          "size": 7949,
          "sha512": "95b7ed253fb29721ddcd8d9a17792358fbf450ca9f2c0a57f7631e2f70bd68bd7213f6f2cdaabedea05a003bed32773c6b42e859b058cdfb5fc94f1609f35b9d",
          "sha256": "342e888aa7c5a5f0390ea59bcd8766053e8e041c297bb485adc9318c6d9cebd4",
          "sha1": "e33009c5bec30b7904c11964aae41de29ae291ab",
          "md5": "a6b582c3713406a2053a0079f19d4fd1"
        }
      ]
    }
  ]
}
