{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-event-handler/0.3.0.1/agents-features-event-handler-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-event-handler",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.1.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.1.jar",
          "size": 129784,
          "sha512": "186b9a19a1d23ba7dfc848ac6d305806fb77dc79681b6bbd470fcd32d9748677287e47d089a3a8b41d2fd3b2180880c00256ebd27b74b263b61f999dfc564147",
          "sha256": "aa2a436f908be7d39444cf07687c3eb325a10d6ec2410820b5da33483942c892",
          "sha1": "ca067d73154e02835f8bef8bf794e25e09c1c8b3",
          "md5": "adf95eade28afbb397ba2c9c16c3de8a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.1.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.1.jar",
          "size": 129784,
          "sha512": "186b9a19a1d23ba7dfc848ac6d305806fb77dc79681b6bbd470fcd32d9748677287e47d089a3a8b41d2fd3b2180880c00256ebd27b74b263b61f999dfc564147",
          "sha256": "aa2a436f908be7d39444cf07687c3eb325a10d6ec2410820b5da33483942c892",
          "sha1": "ca067d73154e02835f8bef8bf794e25e09c1c8b3",
          "md5": "adf95eade28afbb397ba2c9c16c3de8a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.1-sources.jar",
          "size": 8434,
          "sha512": "a654b29e6be6b215cb6327190e03f05e0be7b6b2bb62a1bad29f1d5e6c7356b0d95e7bfddb893d6b03ec69bb18f4cd753e001a38ba93ec66ae740cc9aaab0763",
          "sha256": "92a4655f88281d04dd0e3e2144029bda7e159da76dd07aa31da05d20a4bd28ec",
          "sha1": "d6152389d166e92c27ca36db6361d24b0a51afed",
          "md5": "e7e14b954f2355755d7d614722a7acfb"
        }
      ]
    }
  ]
}
