{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rag-base/0.3.0.3/rag-base-0.3.0.3.module",
    "group": "ai.koog",
    "module": "rag-base",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-js-0.3.0.3.klib",
          "url": "rag-base-js-0.3.0.3.klib",
          "size": 62555,
          "sha512": "d8ccc58580966fe856be8e59032718482a1e868486b18d1ca39b50fb5dbc8f117d0a52c447d9a557c7579efe1410efb7640204627e22aafbb09eec22780f986d",
          "sha256": "71b038a9a6d6b301157f55f8c1c4182208bafa1dc5e12c48d6b3d9977fe72605",
          "sha1": "46db7933b15523f14d7e551b10c2b659c743b8e1",
          "md5": "71dcc3ebb166e3290c910e866f74c576"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-js-0.3.0.3.klib",
          "url": "rag-base-js-0.3.0.3.klib",
          "size": 62555,
          "sha512": "d8ccc58580966fe856be8e59032718482a1e868486b18d1ca39b50fb5dbc8f117d0a52c447d9a557c7579efe1410efb7640204627e22aafbb09eec22780f986d",
          "sha256": "71b038a9a6d6b301157f55f8c1c4182208bafa1dc5e12c48d6b3d9977fe72605",
          "sha1": "46db7933b15523f14d7e551b10c2b659c743b8e1",
          "md5": "71dcc3ebb166e3290c910e866f74c576"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "rag-base-js-0.3.0.3-sources.jar",
          "url": "rag-base-js-0.3.0.3-sources.jar",
          "size": 17585,
          "sha512": "bd56de8af7061bf8ab7c9186b03d4d2a71a0687554f22fe3d2038147785d76d1a792ff8a066b86abb9a5b1afb058c6d96496252d0ae81d63e4d6d41a118a17c2",
          "sha256": "69533d8d5e6c0e08c81fcf8e7d84a21177aad3e7d40c66de3335419fdfe3d656",
          "sha1": "482e17c8bb8042c664a7bc5b153ae06a63ac9b16",
          "md5": "d092141bacf38f14ebf5349d68860d89"
        }
      ]
    }
  ]
}
