{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-clients/0.3.0.3/prompt-executor-clients-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-executor-clients",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.3.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.3.jar",
          "size": 10601,
          "sha512": "c9d37fd3b6ac3be9eb5b4fdf797ac1d916403121e5562e6a93051ee61de5b4cbaa26ecfc0fd0a6f7e15d164fe8f12eb71b79e523239b3b39b2ad1437c5130dcf",
          "sha256": "662100d8d7c762be440e835c391ba7f2709bc1676249591a970caec64f8c5548",
          "sha1": "a73f4603f2a5d5c77dff49ffc9511bc65765df3e",
          "md5": "ae408bf8931d4f7c5fd5b8e15d81ecf6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.3.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.3.jar",
          "size": 10601,
          "sha512": "c9d37fd3b6ac3be9eb5b4fdf797ac1d916403121e5562e6a93051ee61de5b4cbaa26ecfc0fd0a6f7e15d164fe8f12eb71b79e523239b3b39b2ad1437c5130dcf",
          "sha256": "662100d8d7c762be440e835c391ba7f2709bc1676249591a970caec64f8c5548",
          "sha1": "a73f4603f2a5d5c77dff49ffc9511bc65765df3e",
          "md5": "ae408bf8931d4f7c5fd5b8e15d81ecf6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.3-sources.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.3-sources.jar",
          "size": 5674,
          "sha512": "6d62a79cbe627934a4a90e04c5296326ccca92506e50406b27e660006af69dbf0573be5ed3b3612b6f36d573e411533896b542db67f7da99e6a733b17fc7f4d6",
          "sha256": "237aa52cf7dfed42175b31f6191105db97b283d3cdac2168af95993e42d92846",
          "sha1": "f489eeeeba1511db3f3740ff7d193365be875176",
          "md5": "496b1fc79cd5722c972328adb1ead6ae"
        }
      ]
    }
  ]
}
