{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-metadata-0.3.0.1.jar",
          "url": "prompt-markdown-0.3.0.1.jar",
          "size": 3015,
          "sha512": "3e70e7897e60b10e22102cfe471d52953002a85b505c1cf8712a8d21e1b127a8175d1bc86edfec6424bf85616dd6831e72b40e5aa81704197db093d7a6142cf0",
          "sha256": "cb2f0277f0f8ae7c1abbcfa97a4bfb1711da8660ae0fafb078e4a45d35f6d71c",
          "sha1": "169bb1b4abdd278451079c653d778310171cd67c",
          "md5": "1e41e7c983f4c4985def8104e51316f9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-markdown-kotlin-0.3.0.1-sources.jar",
          "url": "prompt-markdown-0.3.0.1-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-js/0.3.0.1/prompt-markdown-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-js/0.3.0.1/prompt-markdown-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-js/0.3.0.1/prompt-markdown-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-markdown-jvm/0.3.0.1/prompt-markdown-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-markdown-jvm/0.3.0.1/prompt-markdown-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-markdown-jvm/0.3.0.1/prompt-markdown-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-wasm-js/0.3.0.1/prompt-markdown-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-wasm-js/0.3.0.1/prompt-markdown-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-markdown-wasm-js/0.3.0.1/prompt-markdown-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-markdown-wasm-js",
        "version": "0.3.0.1"
      }
    }
  ]
}
