{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-memory/0.3.0.2/agents-features-memory-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-features-memory",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.2.jar",
          "url": "agents-features-memory-jvm-0.3.0.2.jar",
          "size": 215249,
          "sha512": "62b881dd013c9fbebb859aca6f0199a31282e121144482ad314e4b82f5c0406972533759d68bb2865a281f1a2b4eb1b731711a731c3e12499eaf27474ab3d208",
          "sha256": "8b90c820268f3b209a5491426f9c2775410584bf9e88512b693b866978320846",
          "sha1": "2dd02c22e1fb333e4134a6678391c99702265146",
          "md5": "8501c10428c1f454245d28aa8e31fb86"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.2.jar",
          "url": "agents-features-memory-jvm-0.3.0.2.jar",
          "size": 215249,
          "sha512": "62b881dd013c9fbebb859aca6f0199a31282e121144482ad314e4b82f5c0406972533759d68bb2865a281f1a2b4eb1b731711a731c3e12499eaf27474ab3d208",
          "sha256": "8b90c820268f3b209a5491426f9c2775410584bf9e88512b693b866978320846",
          "sha1": "2dd02c22e1fb333e4134a6678391c99702265146",
          "md5": "8501c10428c1f454245d28aa8e31fb86"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.2-sources.jar",
          "url": "agents-features-memory-jvm-0.3.0.2-sources.jar",
          "size": 31295,
          "sha512": "e0f6b7c4c7eb79401cfe06c31f8a07b0e4e568c1e3116c5caf741699b7563622eb22e940535e7169583760148848859e60f2bdc4c6bd8a6b9a74019fdb8c742a",
          "sha256": "6bbddbdecb9cbcb196566232329ef716811a1427538304a9081f290653449a08",
          "sha1": "8086fa63aafdbdd2275b30bd02006941d82cf8e0",
          "md5": "4dc275a62440766e44112df3660d254d"
        }
      ]
    }
  ]
}
