{
  "formatVersion": "1.1",
  "component": {
    "url": "../../embeddings-llm/0.3.0.3/embeddings-llm-0.3.0.3.module",
    "group": "ai.koog",
    "module": "embeddings-llm",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-llm-jvm-0.3.0.3.jar",
          "url": "embeddings-llm-jvm-0.3.0.3.jar",
          "size": 4966,
          "sha512": "bae1739f4fb88148aba31df2f5d32465f1beb5d3e5668daa67372acc16e576cb15d4ec613073a839a77c2a09bc6bdebe8f61880c1f7296ff8e4b66edacab33cc",
          "sha256": "de073fcdf48659f77640b545f17ffde115a3c1557edf1c8a9ebabeeedc3188cd",
          "sha1": "e0893b370962ba9fce825f9f7096cebc12dc22b9",
          "md5": "97d373d352fdcc11d01e579ebde82478"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-llm-jvm-0.3.0.3.jar",
          "url": "embeddings-llm-jvm-0.3.0.3.jar",
          "size": 4966,
          "sha512": "bae1739f4fb88148aba31df2f5d32465f1beb5d3e5668daa67372acc16e576cb15d4ec613073a839a77c2a09bc6bdebe8f61880c1f7296ff8e4b66edacab33cc",
          "sha256": "de073fcdf48659f77640b545f17ffde115a3c1557edf1c8a9ebabeeedc3188cd",
          "sha1": "e0893b370962ba9fce825f9f7096cebc12dc22b9",
          "md5": "97d373d352fdcc11d01e579ebde82478"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "embeddings-llm-jvm-0.3.0.3-sources.jar",
          "url": "embeddings-llm-jvm-0.3.0.3-sources.jar",
          "size": 2783,
          "sha512": "d99ad3b05573252e3e4f0e0df656bc1b324e242ad6eaabcb27269629adbd9380785a0bbd1749c38b6300001ee11ed6bbbe313ef2ce18aa48fbe13bca05d37061",
          "sha256": "dc6b88c2d48470f108268f6247faf4abbcf61965e62d041183ea5c97c2102077",
          "sha1": "9b2a1d13f4429ef8ff967a44fd7b02a38680aab5",
          "md5": "3fb535fcc8f56099b1192018f2676884"
        }
      ]
    }
  ]
}
