{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-openai-client/0.3.0.2/prompt-executor-openai-client-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-executor-openai-client",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-wasm-js-0.3.0.2.klib",
          "url": "prompt-executor-openai-client-wasm-js-0.3.0.2.klib",
          "size": 204249,
          "sha512": "3d8d7668d56bc69d9722897a3d8f31034ce53667419fa511a9c4e31ea91522c7e2f5487a3908831c93052da3086989e29eba938946f4119f6d21ec8d6b3efcaa",
          "sha256": "57f31de9badea472c6136847a3e13dce41265333ba95016c02a62e4b026bba1d",
          "sha1": "0ec29e899fbe05404848f7bf50ae85d8ce0e3478",
          "md5": "92cbff73b1b138ab463047f031788a6a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-wasm-js-0.3.0.2.klib",
          "url": "prompt-executor-openai-client-wasm-js-0.3.0.2.klib",
          "size": 204249,
          "sha512": "3d8d7668d56bc69d9722897a3d8f31034ce53667419fa511a9c4e31ea91522c7e2f5487a3908831c93052da3086989e29eba938946f4119f6d21ec8d6b3efcaa",
          "sha256": "57f31de9badea472c6136847a3e13dce41265333ba95016c02a62e4b026bba1d",
          "sha1": "0ec29e899fbe05404848f7bf50ae85d8ce0e3478",
          "md5": "92cbff73b1b138ab463047f031788a6a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-executor-openai-client-wasm-js-0.3.0.2-sources.jar",
          "url": "prompt-executor-openai-client-wasm-js-0.3.0.2-sources.jar",
          "size": 20550,
          "sha512": "eb207455e0c11a904a85bc4567c06cae93de3a17c5046ffe95655b85c4de9f2223741f14793cebd1371d80bd6fc72ca205d85fab909cfe10f8a7bb0ff0f16a5e",
          "sha256": "d0fed419aa2f8cde848a4d225fdffc7885caf690740968b3fcfdea652ff84a90",
          "sha1": "e77d4b843dcfed216631a3d44b410b43d623b88f",
          "md5": "4604dee07dbc0e7e46f4e01503ef01bd"
        }
      ]
    }
  ]
}
