{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-agents/0.3.0.3/koog-agents-0.3.0.3.module",
    "group": "ai.koog",
    "module": "koog-agents",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-xml",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "vector-storage",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-debugger",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-memory",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-opentelemetry",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-snapshot",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-files",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-redis",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-cached",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.3.jar",
          "url": "koog-agents-jvm-0.3.0.3.jar",
          "size": 333,
          "sha512": "c830674c693ef3dc69baf84dd5417df93166f7129138de65d16db915c51145290ed56d63eaf896c0113a78a0522aef2eb7f4dd638e5faa342da203c2066db26e",
          "sha256": "ac089f699b8078dd02a3d9793140a050601e99f61a1e5697209be1ebda8bd509",
          "sha1": "ef6648b6b4238a84c1ea2f18ce9283b5a86161dd",
          "md5": "63a43b75d6c86c85b48365c940a34edd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-xml",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "vector-storage",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-debugger",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-memory",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-opentelemetry",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-snapshot",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-files",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-redis",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-cached",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.3.jar",
          "url": "koog-agents-jvm-0.3.0.3.jar",
          "size": 333,
          "sha512": "c830674c693ef3dc69baf84dd5417df93166f7129138de65d16db915c51145290ed56d63eaf896c0113a78a0522aef2eb7f4dd638e5faa342da203c2066db26e",
          "sha256": "ac089f699b8078dd02a3d9793140a050601e99f61a1e5697209be1ebda8bd509",
          "sha1": "ef6648b6b4238a84c1ea2f18ce9283b5a86161dd",
          "md5": "63a43b75d6c86c85b48365c940a34edd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.3-sources.jar",
          "url": "koog-agents-jvm-0.3.0.3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
