{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-executor-ollama-client",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-ollama-client-metadata-0.3.0.3.jar",
          "url": "prompt-executor-ollama-client-0.3.0.3.jar",
          "size": 12534,
          "sha512": "e847070255a101521a16e0f70c59b70d2f331446b00539637a267a64db13d2d02d22684e45767c12b7285c561dcdb56bf711d0eed764944bf42fc3b0634b5066",
          "sha256": "12bf7fdbb2a7f7aa2b365969c9f90fd0ba837dee64a3e60a2a029a604a21c401",
          "sha1": "06321f0698e6321bb11b98626c18710bebd38f34",
          "md5": "df830375eda5365b99481b24b10bc6fa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-executor-ollama-client-kotlin-0.3.0.3-sources.jar",
          "url": "prompt-executor-ollama-client-0.3.0.3-sources.jar",
          "size": 15350,
          "sha512": "6d7d0a2453bd9b6faa04ec2c1c5a97a89b9db722b10ff89324afd52440c0af360600417623041b1e59235fd6ad7214180cb3958d192265ff021709607574efa9",
          "sha256": "93f2082543856fb583c3d9ef343decb1c9690c9e818152c56da5bc2bfa85616f",
          "sha1": "4846536912f9326dc3a0d453a3e136c52a8bba46",
          "md5": "769d68498e73bbc1cc01071d75fb1c50"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-js/0.3.0.3/prompt-executor-ollama-client-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-js/0.3.0.3/prompt-executor-ollama-client-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-js/0.3.0.3/prompt-executor-ollama-client-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-jvm/0.3.0.3/prompt-executor-ollama-client-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-jvm/0.3.0.3/prompt-executor-ollama-client-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-jvm/0.3.0.3/prompt-executor-ollama-client-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-wasm-js/0.3.0.3/prompt-executor-ollama-client-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-wasm-js/0.3.0.3/prompt-executor-ollama-client-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-ollama-client-wasm-js/0.3.0.3/prompt-executor-ollama-client-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "prompt-executor-ollama-client-wasm-js",
        "version": "0.3.0.3"
      }
    }
  ]
}
