{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "agents-features-event-handler",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-metadata-0.3.0.2.jar",
          "url": "agents-features-event-handler-0.3.0.2.jar",
          "size": 5965,
          "sha512": "53c28a3cb228816694065f40c44c78caf825fce82ffde825ff6a37cd9572c09869a201a080ba4a68c542db6dccfd0fa04e8f19b5aab4e84de06875584273ac54",
          "sha256": "a81c31910761319425c9ecad0370dde8aa380f0bda4b0676573bfe5daa77a5ec",
          "sha1": "8464eb3a5655ac1add758176d61a1b68b33d01a2",
          "md5": "e5f238a2158aae011644fba45e8a27af"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "agents-features-event-handler-kotlin-0.3.0.2-sources.jar",
          "url": "agents-features-event-handler-0.3.0.2-sources.jar",
          "size": 8434,
          "sha512": "a654b29e6be6b215cb6327190e03f05e0be7b6b2bb62a1bad29f1d5e6c7356b0d95e7bfddb893d6b03ec69bb18f4cd753e001a38ba93ec66ae740cc9aaab0763",
          "sha256": "92a4655f88281d04dd0e3e2144029bda7e159da76dd07aa31da05d20a4bd28ec",
          "sha1": "d6152389d166e92c27ca36db6361d24b0a51afed",
          "md5": "e7e14b954f2355755d7d614722a7acfb"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-js/0.3.0.2/agents-features-event-handler-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-js/0.3.0.2/agents-features-event-handler-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-js/0.3.0.2/agents-features-event-handler-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-jvm/0.3.0.2/agents-features-event-handler-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-jvm/0.3.0.2/agents-features-event-handler-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-jvm/0.3.0.2/agents-features-event-handler-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-wasm-js/0.3.0.2/agents-features-event-handler-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-wasm-js/0.3.0.2/agents-features-event-handler-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-event-handler-wasm-js/0.3.0.2/agents-features-event-handler-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-features-event-handler-wasm-js",
        "version": "0.3.0.2"
      }
    }
  ]
}
