{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-memory/0.3.0.1/agents-features-memory-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-memory",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.1.jar",
          "url": "agents-features-memory-jvm-0.3.0.1.jar",
          "size": 215249,
          "sha512": "c64c3bf44b1e17fe58af97ea1024c7e6f7d825bcc53a1ff70ae301c54f3ac5003809828139597fb6a6db77a47d2f97b48435ff2f7471d1d5f90b52c2969038f4",
          "sha256": "63e0fee5f436285c01ccda66238f11c988ca50c577497bc3cacb63d09b3ac2d2",
          "sha1": "923ca893833525ff8505545cf32093136c4ab5e2",
          "md5": "665ce425a4c8ee89a11d6233b2d05159"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.1.jar",
          "url": "agents-features-memory-jvm-0.3.0.1.jar",
          "size": 215249,
          "sha512": "c64c3bf44b1e17fe58af97ea1024c7e6f7d825bcc53a1ff70ae301c54f3ac5003809828139597fb6a6db77a47d2f97b48435ff2f7471d1d5f90b52c2969038f4",
          "sha256": "63e0fee5f436285c01ccda66238f11c988ca50c577497bc3cacb63d09b3ac2d2",
          "sha1": "923ca893833525ff8505545cf32093136c4ab5e2",
          "md5": "665ce425a4c8ee89a11d6233b2d05159"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-memory-jvm-0.3.0.1-sources.jar",
          "size": 31295,
          "sha512": "e0f6b7c4c7eb79401cfe06c31f8a07b0e4e568c1e3116c5caf741699b7563622eb22e940535e7169583760148848859e60f2bdc4c6bd8a6b9a74019fdb8c742a",
          "sha256": "6bbddbdecb9cbcb196566232329ef716811a1427538304a9081f290653449a08",
          "sha1": "8086fa63aafdbdd2275b30bd02006941d82cf8e0",
          "md5": "4dc275a62440766e44112df3660d254d"
        }
      ]
    }
  ]
}
