{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-xml/0.3.0.1/prompt-xml-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-xml",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-js-0.3.0.1.klib",
          "url": "prompt-xml-js-0.3.0.1.klib",
          "size": 11372,
          "sha512": "10b18db6de8cce2509a9983f1abf7602f87489b78e16d5a50b70ccd565c6ce60802488ce3701098230b83f9fdb1c59d1693b1dd06acbf3964a731d8f875a7e53",
          "sha256": "e6a63714027ea055e117c10a29c15c04583a48786c8ead9d48710bc5b443491f",
          "sha1": "adf93497830979a87d949ec195101b650f369c5d",
          "md5": "b1c2eedb1ce4ba43b63a80382644c0f6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-js-0.3.0.1.klib",
          "url": "prompt-xml-js-0.3.0.1.klib",
          "size": 11372,
          "sha512": "10b18db6de8cce2509a9983f1abf7602f87489b78e16d5a50b70ccd565c6ce60802488ce3701098230b83f9fdb1c59d1693b1dd06acbf3964a731d8f875a7e53",
          "sha256": "e6a63714027ea055e117c10a29c15c04583a48786c8ead9d48710bc5b443491f",
          "sha1": "adf93497830979a87d949ec195101b650f369c5d",
          "md5": "b1c2eedb1ce4ba43b63a80382644c0f6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-xml-js-0.3.0.1-sources.jar",
          "url": "prompt-xml-js-0.3.0.1-sources.jar",
          "size": 2531,
          "sha512": "6d51a670528f215f3a2f2d83286b0acb452bc655ab3095ffc7c65db8fe4ff68360f451c4336d3c6413501b42fc02c771dc76fb51d7b9621c0530c87594688f9b",
          "sha256": "3abed046ad0da624dbd5c4682df923ea37f0bbb8a7498887ce7c61cb9ba92146",
          "sha1": "80e54d1333b6ecc149680e54aba3ba202f8146b3",
          "md5": "11c9dcc6cf24a6e053fd0390dbd9fb86"
        }
      ]
    }
  ]
}
