{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-google-client/0.3.0.4/prompt-executor-google-client-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-google-client",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.4.jar",
          "size": 187264,
          "sha512": "ed152d16ac8d791cef79af947f06437d3cefda2ef86bd8e377e3f4014e3fa14f3af319a10e81abc3708187c41e396795e942db0127c416ac462b2a5a638d50c5",
          "sha256": "57ba2998328807db204474e69c6cb7045832a6b76918a7da24c126f0e7af609e",
          "sha1": "d65edc1ab2d159c50df4ce01081f56eea730d1fb",
          "md5": "82999602512979b68934ce4d78dbdb36"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.4.jar",
          "size": 187264,
          "sha512": "ed152d16ac8d791cef79af947f06437d3cefda2ef86bd8e377e3f4014e3fa14f3af319a10e81abc3708187c41e396795e942db0127c416ac462b2a5a638d50c5",
          "sha256": "57ba2998328807db204474e69c6cb7045832a6b76918a7da24c126f0e7af609e",
          "sha1": "d65edc1ab2d159c50df4ce01081f56eea730d1fb",
          "md5": "82999602512979b68934ce4d78dbdb36"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.4-sources.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.4-sources.jar",
          "size": 15001,
          "sha512": "1832fca53d54ef62e602dcefee0bd35461b5e07e7cbbd440bfbf135cf61db1a02d3bc1d0cfc5d8979c86b21d6e6a963bb5b87fbc521f306063c1c72a1fa08465",
          "sha256": "ad98fb405f432489e2781cf812913e193f7e5884cc25c0d8a71c859523473504",
          "sha1": "ae954fc81d7e64df0c8399556332aed7d87c4acc",
          "md5": "5fc7597292e41917e07cda368632df93"
        }
      ]
    }
  ]
}
