{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "agents-features-debugger",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-metadata-0.3.0.3.jar",
          "url": "agents-features-debugger-0.3.0.3.jar",
          "size": 5147,
          "sha512": "c8e52777e935ceb079c1d5a600d66fb635cfa7e31a3b33cd5ce12e8d8e5811e007b6db1223e0c18830c995078ee0b12591bf11afd27f47939741bfd864f3102f",
          "sha256": "b1b319426c29693d7db0f0babd5e2361806a9b68148eaa45216544ef5e180989",
          "sha1": "1747a34265abaf29c5f280ff34acab512702b214",
          "md5": "314418254a6ca13b14a9aa0305e07bea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "agents-features-debugger-kotlin-0.3.0.3-sources.jar",
          "url": "agents-features-debugger-0.3.0.3-sources.jar",
          "size": 5770,
          "sha512": "212975e13af0489a04500156eebf74e2b6a4db02578fb1785b0fbf3eb425eb1d26485d2de9ff8b12f1951e0fe4a6b4e4f3e708bc81cb4ac18a69fca4d43ced42",
          "sha256": "114ff82a21116e9d30d7a55db3a12381e4404849c442704e730ba6ecffc6baa0",
          "sha1": "31ece54c85a797574f558fbde05e7ea3884fbf93",
          "md5": "f2f6b732f1663088decb690d0dd2e61e"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-js/0.3.0.3/agents-features-debugger-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-js/0.3.0.3/agents-features-debugger-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-js/0.3.0.3/agents-features-debugger-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-debugger-jvm/0.3.0.3/agents-features-debugger-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-debugger-jvm/0.3.0.3/agents-features-debugger-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-debugger-jvm/0.3.0.3/agents-features-debugger-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-wasm-js/0.3.0.3/agents-features-debugger-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-wasm-js/0.3.0.3/agents-features-debugger-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-debugger-wasm-js/0.3.0.3/agents-features-debugger-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-debugger-wasm-js",
        "version": "0.3.0.3"
      }
    }
  ]
}
