{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-tokenizer/0.3.0.3/prompt-tokenizer-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-tokenizer",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.3.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.3.jar",
          "size": 12349,
          "sha512": "45fd9509be5bc415fefb80b125190a3f9271a685a70acbbd8f60078efc4b3cab3fd91273f2670e70fd2b80177bb3ea47c1a4660f30283f5f825ac372fb271aae",
          "sha256": "5972ec7cc7240f6ddc3bafc25d41f52134a7b1b20a6b0b6b5753da5b475b7316",
          "sha1": "9c30af9bd862fa460e231cbf22c0cccf83a2478a",
          "md5": "908f48faac0d07f877be8cf3f50a5b10"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.3.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.3.jar",
          "size": 12349,
          "sha512": "45fd9509be5bc415fefb80b125190a3f9271a685a70acbbd8f60078efc4b3cab3fd91273f2670e70fd2b80177bb3ea47c1a4660f30283f5f825ac372fb271aae",
          "sha256": "5972ec7cc7240f6ddc3bafc25d41f52134a7b1b20a6b0b6b5753da5b475b7316",
          "sha1": "9c30af9bd862fa460e231cbf22c0cccf83a2478a",
          "md5": "908f48faac0d07f877be8cf3f50a5b10"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.3-sources.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.3-sources.jar",
          "size": 5324,
          "sha512": "9f20b03ab6292e425bc851b11683b9cc6ce0dddc3d6b6b4b042350ed5486fae56b2c116309542261cfa4869e16b5437b411d2d6b4318f65747484d3538ad780a",
          "sha256": "2dc6d3700773b4af3f73e9246fdce6d96535ffeb1534ae1d7c0410fe314453bb",
          "sha1": "4e09855b24b57f5baa052bb8ae81407de6f91891",
          "md5": "f8a904bee7024e89c1166a9ba9c72e34"
        }
      ]
    }
  ]
}
