{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.1/prompt-markdown-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.1.jar",
          "url": "prompt-markdown-jvm-0.3.0.1.jar",
          "size": 13470,
          "sha512": "e040c7bd43765dba4a17a4cc86fc04e545e222db0e182f13f1f49518a6a7984a80236e92e95651e99849ace8797db3ebf67450af32219ef52ff1f340fce1adda",
          "sha256": "fa616683e7e4daacc4dbc2d20e558e1401756395d2109a39b7c7f8c9482927de",
          "sha1": "56743c9e219c5b819fba406a4a5880ec011dbdde",
          "md5": "52dce5a29f4047713935067995725410"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.1.jar",
          "url": "prompt-markdown-jvm-0.3.0.1.jar",
          "size": 13470,
          "sha512": "e040c7bd43765dba4a17a4cc86fc04e545e222db0e182f13f1f49518a6a7984a80236e92e95651e99849ace8797db3ebf67450af32219ef52ff1f340fce1adda",
          "sha256": "fa616683e7e4daacc4dbc2d20e558e1401756395d2109a39b7c7f8c9482927de",
          "sha1": "56743c9e219c5b819fba406a4a5880ec011dbdde",
          "md5": "52dce5a29f4047713935067995725410"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.1-sources.jar",
          "url": "prompt-markdown-jvm-0.3.0.1-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
