{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-utils/0.3.0.2/agents-utils-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-utils",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.2.jar",
          "url": "agents-utils-jvm-0.3.0.2.jar",
          "size": 4969,
          "sha512": "d9713f4134651f345247c0faf0ee32dd355a6a4da1f33efb8c04b11f9e0dd414c470103ff43fde6d5a72f54a6ffae8fc214a7392a5595700aa539bcfc5a53e25",
          "sha256": "be8b388d46207836384cadd4f797a84e2e994034f2ac7b4653e135b83a0b6abf",
          "sha1": "b89f9b212b6be920c8bcc2c681b55bf777428c22",
          "md5": "442e6c8c3d4f138228cc5f8bed0d475f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.2.jar",
          "url": "agents-utils-jvm-0.3.0.2.jar",
          "size": 4969,
          "sha512": "d9713f4134651f345247c0faf0ee32dd355a6a4da1f33efb8c04b11f9e0dd414c470103ff43fde6d5a72f54a6ffae8fc214a7392a5595700aa539bcfc5a53e25",
          "sha256": "be8b388d46207836384cadd4f797a84e2e994034f2ac7b4653e135b83a0b6abf",
          "sha1": "b89f9b212b6be920c8bcc2c681b55bf777428c22",
          "md5": "442e6c8c3d4f138228cc5f8bed0d475f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.2-sources.jar",
          "url": "agents-utils-jvm-0.3.0.2-sources.jar",
          "size": 2969,
          "sha512": "86f164457f2d918a0a0f75759f6ba674892f4948aa9cfc8de490227c9d3d525171dd6b32374efde43fcf250bf88a47f989b0583eb3837eed96e442710a167eb5",
          "sha256": "5523d848b18d7ebd8e3a3bf631128a316301459167165553534f0294f205c36a",
          "sha1": "2adac0e68b127e0a6d496fe6a4109c9323a94ae8",
          "md5": "231e82d2c5dc2ddf78df6de56f243952"
        }
      ]
    }
  ]
}
