{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-llm/0.3.0.1/prompt-llm-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-llm",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.1.jar",
          "url": "prompt-llm-jvm-0.3.0.1.jar",
          "size": 68069,
          "sha512": "95a1e521e3b1389e8eac53399815ff7f01048d8fc9fd4e02dcec9215c8efeed2d6ace56b895e1a01161aee9720dfe58f194d40285faf46696927e4d8d1e5074c",
          "sha256": "eba12c8bc33a1a2a7ac77051848b0bc0a94f3d2c4e1fe8dc92d592942f375516",
          "sha1": "23c62ead3dfe1aa03d24a718c4f05cbcc15c4698",
          "md5": "2175ebd401a0eb616cd7b187ed87d484"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.1.jar",
          "url": "prompt-llm-jvm-0.3.0.1.jar",
          "size": 68069,
          "sha512": "95a1e521e3b1389e8eac53399815ff7f01048d8fc9fd4e02dcec9215c8efeed2d6ace56b895e1a01161aee9720dfe58f194d40285faf46696927e4d8d1e5074c",
          "sha256": "eba12c8bc33a1a2a7ac77051848b0bc0a94f3d2c4e1fe8dc92d592942f375516",
          "sha1": "23c62ead3dfe1aa03d24a718c4f05cbcc15c4698",
          "md5": "2175ebd401a0eb616cd7b187ed87d484"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.1-sources.jar",
          "url": "prompt-llm-jvm-0.3.0.1-sources.jar",
          "size": 7949,
          "sha512": "95b7ed253fb29721ddcd8d9a17792358fbf450ca9f2c0a57f7631e2f70bd68bd7213f6f2cdaabedea05a003bed32773c6b42e859b058cdfb5fc94f1609f35b9d",
          "sha256": "342e888aa7c5a5f0390ea59bcd8766053e8e041c297bb485adc9318c6d9cebd4",
          "sha1": "e33009c5bec30b7904c11964aae41de29ae291ab",
          "md5": "a6b582c3713406a2053a0079f19d4fd1"
        }
      ]
    }
  ]
}
