{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-event-handler/0.3.0.3/agents-features-event-handler-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-features-event-handler",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.3.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.3.jar",
          "size": 129785,
          "sha512": "6d19b0b8f949123ca9ddb78a7a12e928ee960f52154ff5319c6d4d1911e9b679fc97d626f4f4bf403ff8688c6e7f42b7d5dec1918921d3d3f452e48da20c62c4",
          "sha256": "35709755a9c669d2470f21392dbaab0d530418a39b9a1d3d1e0e0dfde824c478",
          "sha1": "77fed60751a132299be94a248f1db577472602b2",
          "md5": "8f3bca9bc4082e740b8a7c80b7720ea4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.3.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.3.jar",
          "size": 129785,
          "sha512": "6d19b0b8f949123ca9ddb78a7a12e928ee960f52154ff5319c6d4d1911e9b679fc97d626f4f4bf403ff8688c6e7f42b7d5dec1918921d3d3f452e48da20c62c4",
          "sha256": "35709755a9c669d2470f21392dbaab0d530418a39b9a1d3d1e0e0dfde824c478",
          "sha1": "77fed60751a132299be94a248f1db577472602b2",
          "md5": "8f3bca9bc4082e740b8a7c80b7720ea4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.3-sources.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.3-sources.jar",
          "size": 8434,
          "sha512": "a654b29e6be6b215cb6327190e03f05e0be7b6b2bb62a1bad29f1d5e6c7356b0d95e7bfddb893d6b03ec69bb18f4cd753e001a38ba93ec66ae740cc9aaab0763",
          "sha256": "92a4655f88281d04dd0e3e2144029bda7e159da76dd07aa31da05d20a4bd28ec",
          "sha1": "d6152389d166e92c27ca36db6361d24b0a51afed",
          "md5": "e7e14b954f2355755d7d614722a7acfb"
        }
      ]
    }
  ]
}
