{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-ext/0.3.0.3/agents-ext-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-ext",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.3.jar",
          "url": "agents-ext-jvm-0.3.0.3.jar",
          "size": 214025,
          "sha512": "a0a88396c936c658bac5ab17401d4e2f469296f540c62863edbc4a467986d78ad97e1ca1e93c30b75871dc7a66de9ae421b71f78046cb929ebbb9756689c0cf0",
          "sha256": "4ba4bc53e2127ba7f8a35d70536b426ff391c53355bc1d985a89659f11be6637",
          "sha1": "ca834bee79256c4e7184f3929aac5e19947ef9ed",
          "md5": "d572206073150544cd56d375aafe2f05"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.3.jar",
          "url": "agents-ext-jvm-0.3.0.3.jar",
          "size": 214025,
          "sha512": "a0a88396c936c658bac5ab17401d4e2f469296f540c62863edbc4a467986d78ad97e1ca1e93c30b75871dc7a66de9ae421b71f78046cb929ebbb9756689c0cf0",
          "sha256": "4ba4bc53e2127ba7f8a35d70536b426ff391c53355bc1d985a89659f11be6637",
          "sha1": "ca834bee79256c4e7184f3929aac5e19947ef9ed",
          "md5": "d572206073150544cd56d375aafe2f05"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.3-sources.jar",
          "url": "agents-ext-jvm-0.3.0.3-sources.jar",
          "size": 15660,
          "sha512": "d595d7273d7f55ffae4f6431b05057446610ef1cd669bf6df2207b6c135cd1e8def4450f90b71c8348c274614a914f787579848de16192cfc28ed81c879f1c38",
          "sha256": "022362051cc88c5d1d4303b9ff0601c3d8078c6222d0266e6c3080527246bdd3",
          "sha1": "d8614bf76dc191e67761ac9b0213f066d9b80460",
          "md5": "6cd796ed1435b716c8251eac651905a3"
        }
      ]
    }
  ]
}
