{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-openai-client/0.3.0.4/prompt-executor-openai-client-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-openai-client",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-openai-client-jvm-0.3.0.4.jar",
          "size": 331571,
          "sha512": "d592c5c129b8849a30f2c9bf0859d18ac66e0eb2ae6c7b356d12098386ca0e6b35475c1e3cb98103474a48c7b15ff92d4c4c37c6d8d367ff2cbf52e2f45e546b",
          "sha256": "71a1a69ab5f0bbfb83a2d794ca58340057b9c67ce09d4869f5d4816f2119c12e",
          "sha1": "cf0713bf9ee86dd266fb43d6b78e37fb6077bc9e",
          "md5": "9f34f27b32f6e1576a0d1a4fd52e4988"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openai-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-openai-client-jvm-0.3.0.4.jar",
          "size": 331571,
          "sha512": "d592c5c129b8849a30f2c9bf0859d18ac66e0eb2ae6c7b356d12098386ca0e6b35475c1e3cb98103474a48c7b15ff92d4c4c37c6d8d367ff2cbf52e2f45e546b",
          "sha256": "71a1a69ab5f0bbfb83a2d794ca58340057b9c67ce09d4869f5d4816f2119c12e",
          "sha1": "cf0713bf9ee86dd266fb43d6b78e37fb6077bc9e",
          "md5": "9f34f27b32f6e1576a0d1a4fd52e4988"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-openai-client-jvm-0.3.0.4-sources.jar",
          "url": "prompt-executor-openai-client-jvm-0.3.0.4-sources.jar",
          "size": 20550,
          "sha512": "eb207455e0c11a904a85bc4567c06cae93de3a17c5046ffe95655b85c4de9f2223741f14793cebd1371d80bd6fc72ca205d85fab909cfe10f8a7bb0ff0f16a5e",
          "sha256": "d0fed419aa2f8cde848a4d225fdffc7885caf690740968b3fcfdea652ff84a90",
          "sha1": "e77d4b843dcfed216631a3d44b410b43d623b88f",
          "md5": "4604dee07dbc0e7e46f4e01503ef01bd"
        }
      ]
    }
  ]
}
