{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-xml/0.3.0.3/prompt-xml-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-xml",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.3.jar",
          "url": "prompt-xml-jvm-0.3.0.3.jar",
          "size": 7318,
          "sha512": "f82a0533bd1257c8cefde7bd29fd6a359ffad5118b58c7cb42d7133c9ad4ee2aa9720c74e6e3d2be6293beb9a9214b1950e9d9afe0442f244204bd58d5896a4f",
          "sha256": "769ba9779b8416487f9fe606cec27641330c1a418e607b913ab27bc86bf68750",
          "sha1": "22d5495e3bedd597e16489e7c28adc6fdc70f2fe",
          "md5": "fc539b508c11968e79bf6998da955de3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.3.jar",
          "url": "prompt-xml-jvm-0.3.0.3.jar",
          "size": 7318,
          "sha512": "f82a0533bd1257c8cefde7bd29fd6a359ffad5118b58c7cb42d7133c9ad4ee2aa9720c74e6e3d2be6293beb9a9214b1950e9d9afe0442f244204bd58d5896a4f",
          "sha256": "769ba9779b8416487f9fe606cec27641330c1a418e607b913ab27bc86bf68750",
          "sha1": "22d5495e3bedd597e16489e7c28adc6fdc70f2fe",
          "md5": "fc539b508c11968e79bf6998da955de3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.3-sources.jar",
          "url": "prompt-xml-jvm-0.3.0.3-sources.jar",
          "size": 2531,
          "sha512": "6d51a670528f215f3a2f2d83286b0acb452bc655ab3095ffc7c65db8fe4ff68360f451c4336d3c6413501b42fc02c771dc76fb51d7b9621c0530c87594688f9b",
          "sha256": "3abed046ad0da624dbd5c4682df923ea37f0bbb8a7498887ce7c61cb9ba92146",
          "sha1": "80e54d1333b6ecc149680e54aba3ba202f8146b3",
          "md5": "11c9dcc6cf24a6e053fd0390dbd9fb86"
        }
      ]
    }
  ]
}
