{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-llm/0.3.0.2/prompt-llm-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-llm",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.2.jar",
          "url": "prompt-llm-jvm-0.3.0.2.jar",
          "size": 68069,
          "sha512": "4411932ac0e3528207ee6f2245bd23e15b5f2ddef802b17055cf2eed0efb380c6e3f34484d383bf97d64a4517d79d34de5784020fe9f982f6d4f35892bdd9aac",
          "sha256": "31cdb5f154b449b0227c7bfeb6be315afde74495ffa7372f5f26a70f1c4ebde2",
          "sha1": "8ef2fdfb61199eff24fdb5aad3a15855948137f3",
          "md5": "b48e4afce1ad4bda078d3cab5cd2f2c4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.2.jar",
          "url": "prompt-llm-jvm-0.3.0.2.jar",
          "size": 68069,
          "sha512": "4411932ac0e3528207ee6f2245bd23e15b5f2ddef802b17055cf2eed0efb380c6e3f34484d383bf97d64a4517d79d34de5784020fe9f982f6d4f35892bdd9aac",
          "sha256": "31cdb5f154b449b0227c7bfeb6be315afde74495ffa7372f5f26a70f1c4ebde2",
          "sha1": "8ef2fdfb61199eff24fdb5aad3a15855948137f3",
          "md5": "b48e4afce1ad4bda078d3cab5cd2f2c4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-llm-jvm-0.3.0.2-sources.jar",
          "url": "prompt-llm-jvm-0.3.0.2-sources.jar",
          "size": 7949,
          "sha512": "95b7ed253fb29721ddcd8d9a17792358fbf450ca9f2c0a57f7631e2f70bd68bd7213f6f2cdaabedea05a003bed32773c6b42e859b058cdfb5fc94f1609f35b9d",
          "sha256": "342e888aa7c5a5f0390ea59bcd8766053e8e041c297bb485adc9318c6d9cebd4",
          "sha1": "e33009c5bec30b7904c11964aae41de29ae291ab",
          "md5": "a6b582c3713406a2053a0079f19d4fd1"
        }
      ]
    }
  ]
}
