{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-agents/0.3.0.2/koog-agents-0.3.0.2.module",
    "group": "ai.koog",
    "module": "koog-agents",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-xml",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "vector-storage",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-debugger",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-memory",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-opentelemetry",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-snapshot",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-tokenizer",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-files",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-redis",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-cached",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.2.jar",
          "url": "koog-agents-jvm-0.3.0.2.jar",
          "size": 335,
          "sha512": "08aa6bc3bb99326f3e99f91a49c22390b834b302c46ecb83265b84b15cff0512c1470babe439613b20b08a3eb646372d14e2beed7b30ed6fc27f7552ebfea9aa",
          "sha256": "d8d0eda75f09b7c8f6db40f4866c9092127d7cdc87267d1c98fb89d407f00d6c",
          "sha1": "237226822443b76eae91b93a903a4546a218d43d",
          "md5": "6be31d08f9800b656ba9006c63692dc3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-xml",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "vector-storage",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-debugger",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-event-handler",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-memory",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-opentelemetry",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-snapshot",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-tokenizer",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-features-trace",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-files",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-redis",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-cached",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-bedrock-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-ollama-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openrouter-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.2.jar",
          "url": "koog-agents-jvm-0.3.0.2.jar",
          "size": 335,
          "sha512": "08aa6bc3bb99326f3e99f91a49c22390b834b302c46ecb83265b84b15cff0512c1470babe439613b20b08a3eb646372d14e2beed7b30ed6fc27f7552ebfea9aa",
          "sha256": "d8d0eda75f09b7c8f6db40f4866c9092127d7cdc87267d1c98fb89d407f00d6c",
          "sha1": "237226822443b76eae91b93a903a4546a218d43d",
          "md5": "6be31d08f9800b656ba9006c63692dc3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koog-agents-jvm-0.3.0.2-sources.jar",
          "url": "koog-agents-jvm-0.3.0.2-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
