{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-structure/0.3.0.4/prompt-structure-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-structure",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.4.jar",
          "url": "prompt-structure-jvm-0.3.0.4.jar",
          "size": 102999,
          "sha512": "3512060882a811ed9b799620dd55349f9c6cd9c0fb84e9d15cb2072808168bcf32c8932bf24aa75c51162a2fd728919076c0af37b5d4b57d9ec7f34efa9ca3a2",
          "sha256": "3a7f94400e61edc23ea7bf078c3dbe56a395bfa7f48bdbcfda99cd46bc7be57a",
          "sha1": "0ef1b322358f54105c6c0ad225230e01f1ccad98",
          "md5": "25f84f4d7216438be5989b72e0684fc7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.4.jar",
          "url": "prompt-structure-jvm-0.3.0.4.jar",
          "size": 102999,
          "sha512": "3512060882a811ed9b799620dd55349f9c6cd9c0fb84e9d15cb2072808168bcf32c8932bf24aa75c51162a2fd728919076c0af37b5d4b57d9ec7f34efa9ca3a2",
          "sha256": "3a7f94400e61edc23ea7bf078c3dbe56a395bfa7f48bdbcfda99cd46bc7be57a",
          "sha1": "0ef1b322358f54105c6c0ad225230e01f1ccad98",
          "md5": "25f84f4d7216438be5989b72e0684fc7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.4-sources.jar",
          "url": "prompt-structure-jvm-0.3.0.4-sources.jar",
          "size": 27083,
          "sha512": "5250c66d20748c0b806880f3bcadd10974d9fce61b8170c456beb544c28b4c99d625e52e20cf528ee112d777c668ef9b927cf9b287681b93b34c8de1da6d1545",
          "sha256": "ea31e982ba60a38f96019e99d6f2a722a314af16a605d1f4bc51761110633d6a",
          "sha1": "aa01e369cc1be7f8d1ddf432020ec37b319b1e48",
          "md5": "ac7eebd2009db0043d906d30f7ddfc99"
        }
      ]
    }
  ]
}
