{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-tokenizer/0.3.0.3/agents-features-tokenizer-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-features-tokenizer",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-wasm-js-0.3.0.3.klib",
          "url": "agents-features-tokenizer-wasm-js-0.3.0.3.klib",
          "size": 9465,
          "sha512": "c34fa856a72daa52adc841d92070be91d55cdefcbfce19b77a2350d13d611260a05a45b08c73bc9d13bc136163beb59e678c9bd435dbf0725aee847c63b2d78e",
          "sha256": "27559519d917df9f7a29c3f2dbd730e4b69ff9a06e3cb8f0dafe748f64e66a30",
          "sha1": "38d81b6f7bb2ce3285b0a0578ef16a463729dd28",
          "md5": "e4e173f1e04ad5360c601c24218fac3a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-wasm-js-0.3.0.3.klib",
          "url": "agents-features-tokenizer-wasm-js-0.3.0.3.klib",
          "size": 9465,
          "sha512": "c34fa856a72daa52adc841d92070be91d55cdefcbfce19b77a2350d13d611260a05a45b08c73bc9d13bc136163beb59e678c9bd435dbf0725aee847c63b2d78e",
          "sha256": "27559519d917df9f7a29c3f2dbd730e4b69ff9a06e3cb8f0dafe748f64e66a30",
          "sha1": "38d81b6f7bb2ce3285b0a0578ef16a463729dd28",
          "md5": "e4e173f1e04ad5360c601c24218fac3a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "agents-features-tokenizer-wasm-js-0.3.0.3-sources.jar",
          "url": "agents-features-tokenizer-wasm-js-0.3.0.3-sources.jar",
          "size": 4408,
          "sha512": "971fd1dcbbf34e351e5973cce924aa7af2fbfb01872a7476a60547b7c51cddc73f5bdbf0dfc86d203a6fc62c18894d33dfe7ad4bba33e7dc2178b0d773d45b73",
          "sha256": "f4a8dba2f14c54d1ee0842b49bfd48a93017528e79727bbf5b74304dd0d41c21",
          "sha1": "ca5e50b9cdd1b782ff14f94f3e93c081f4fc4220",
          "md5": "52b3d625bed4a02e0aafba87682b43d5"
        }
      ]
    }
  ]
}
