{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.3/prompt-markdown-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.3.jar",
          "url": "prompt-markdown-jvm-0.3.0.3.jar",
          "size": 13468,
          "sha512": "6ea83c1d84cc713973f1f02fa9a142e740da3d45526aa8df765e700aa2c7e3c2ad5bf3b5b79dcf03bdbfc06e3985e5c1ccc64e0c60158357f2735c2fdb9c3309",
          "sha256": "825403bbee11166259f80eb01fae9fd8b0f556970ff8a5d7ef2137d7308eb03e",
          "sha1": "3fce36cc49e853003647dc5f19205ba3dbc6899e",
          "md5": "8a278312292369dec5002107ee4035fd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.3.jar",
          "url": "prompt-markdown-jvm-0.3.0.3.jar",
          "size": 13468,
          "sha512": "6ea83c1d84cc713973f1f02fa9a142e740da3d45526aa8df765e700aa2c7e3c2ad5bf3b5b79dcf03bdbfc06e3985e5c1ccc64e0c60158357f2735c2fdb9c3309",
          "sha256": "825403bbee11166259f80eb01fae9fd8b0f556970ff8a5d7ef2137d7308eb03e",
          "sha1": "3fce36cc49e853003647dc5f19205ba3dbc6899e",
          "md5": "8a278312292369dec5002107ee4035fd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.3-sources.jar",
          "url": "prompt-markdown-jvm-0.3.0.3-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
