{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-tokenizer/0.3.0.4/agents-features-tokenizer-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-features-tokenizer",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.4.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.4.jar",
          "size": 10521,
          "sha512": "e52dd93903d59c3a4ce2ea709bfed563ccad3ed53a9737c2cdf19d78ecf10ee7d8f1ca4701e5f702a022b024fdb9921a58491b302d15a6ae2a4b6faf01606471",
          "sha256": "74d9969b65aaff1842ee89b230e60ba5854fc216bf9bfd47583dac3d4b0e983c",
          "sha1": "a8d6572f316a2fe1f0ced833f577bb46614e7d92",
          "md5": "6e216de2628d6fd563224147aa6e8c82"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.4.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.4.jar",
          "size": 10521,
          "sha512": "e52dd93903d59c3a4ce2ea709bfed563ccad3ed53a9737c2cdf19d78ecf10ee7d8f1ca4701e5f702a022b024fdb9921a58491b302d15a6ae2a4b6faf01606471",
          "sha256": "74d9969b65aaff1842ee89b230e60ba5854fc216bf9bfd47583dac3d4b0e983c",
          "sha1": "a8d6572f316a2fe1f0ced833f577bb46614e7d92",
          "md5": "6e216de2628d6fd563224147aa6e8c82"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-tokenizer-jvm-0.3.0.4-sources.jar",
          "url": "agents-features-tokenizer-jvm-0.3.0.4-sources.jar",
          "size": 4408,
          "sha512": "971fd1dcbbf34e351e5973cce924aa7af2fbfb01872a7476a60547b7c51cddc73f5bdbf0dfc86d203a6fc62c18894d33dfe7ad4bba33e7dc2178b0d773d45b73",
          "sha256": "f4a8dba2f14c54d1ee0842b49bfd48a93017528e79727bbf5b74304dd0d41c21",
          "sha1": "ca5e50b9cdd1b782ff14f94f3e93c081f4fc4220",
          "md5": "52b3d625bed4a02e0aafba87682b43d5"
        }
      ]
    }
  ]
}
