{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-tokenizer/0.3.0.4/prompt-tokenizer-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-tokenizer",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-js-0.3.0.4.klib",
          "url": "prompt-tokenizer-js-0.3.0.4.klib",
          "size": 16961,
          "sha512": "24c45cf724f90bd1a0ad312460cd94f3491a022a2d4b014b6f4f2c5533dce54845ae815b2767e0265f7d34fbc4ad6dedfaf4543fcd1ed721e8118948e0411b9a",
          "sha256": "b0777612a3fb84317c34e862121bb673e9253a398b737d508112d9f39f562f14",
          "sha1": "4a2ce6e0bbbc30a601639bff5c2ff1b29ad218b0",
          "md5": "226ea8c86dcfbbfd6a1f46580b923641"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-js-0.3.0.4.klib",
          "url": "prompt-tokenizer-js-0.3.0.4.klib",
          "size": 16961,
          "sha512": "24c45cf724f90bd1a0ad312460cd94f3491a022a2d4b014b6f4f2c5533dce54845ae815b2767e0265f7d34fbc4ad6dedfaf4543fcd1ed721e8118948e0411b9a",
          "sha256": "b0777612a3fb84317c34e862121bb673e9253a398b737d508112d9f39f562f14",
          "sha1": "4a2ce6e0bbbc30a601639bff5c2ff1b29ad218b0",
          "md5": "226ea8c86dcfbbfd6a1f46580b923641"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-tokenizer-js-0.3.0.4-sources.jar",
          "url": "prompt-tokenizer-js-0.3.0.4-sources.jar",
          "size": 5324,
          "sha512": "9f20b03ab6292e425bc851b11683b9cc6ce0dddc3d6b6b4b042350ed5486fae56b2c116309542261cfa4869e16b5437b411d2d6b4318f65747484d3538ad780a",
          "sha256": "2dc6d3700773b4af3f73e9246fdce6d96535ffeb1534ae1d7c0410fe314453bb",
          "sha1": "4e09855b24b57f5baa052bb8ae81407de6f91891",
          "md5": "f8a904bee7024e89c1166a9ba9c72e34"
        }
      ]
    }
  ]
}
