{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-clients/0.3.0.1/prompt-executor-clients-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-clients",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-js-0.3.0.1.klib",
          "url": "prompt-executor-clients-js-0.3.0.1.klib",
          "size": 10380,
          "sha512": "79f83b35f4c28b78291d9b5fea100563469eeb66a67ffad4191ebd9906787e3ae3feb063986f48ddf271f373078d70c52e2d6c8592edd25e38a8b1c45494ea87",
          "sha256": "c4a54ef1a13159428f0fe399a1e6a38c7a9809986ef704a796b5fa856747a377",
          "sha1": "c24d12727fa7b22d87e018ac94cf66ad57197578",
          "md5": "b893126279c464bfe3d26fd8b14cf308"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-js-0.3.0.1.klib",
          "url": "prompt-executor-clients-js-0.3.0.1.klib",
          "size": 10380,
          "sha512": "79f83b35f4c28b78291d9b5fea100563469eeb66a67ffad4191ebd9906787e3ae3feb063986f48ddf271f373078d70c52e2d6c8592edd25e38a8b1c45494ea87",
          "sha256": "c4a54ef1a13159428f0fe399a1e6a38c7a9809986ef704a796b5fa856747a377",
          "sha1": "c24d12727fa7b22d87e018ac94cf66ad57197578",
          "md5": "b893126279c464bfe3d26fd8b14cf308"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-executor-clients-js-0.3.0.1-sources.jar",
          "url": "prompt-executor-clients-js-0.3.0.1-sources.jar",
          "size": 4120,
          "sha512": "b80e745e87e6e2428a6ea4a7d6d4a8f4d07f97ae4cfd5e4db5c8ffee462488811f147550f5944466967470b2465c737843c7f0e631929579fee2b574644f24c6",
          "sha256": "09854c5f38280755c271810c08c7185302b9d6335ab431da7a76bbb34625ec2c",
          "sha1": "95f21fd5197ac0ede003b47fdd194126ea0a5fb3",
          "md5": "a70b31f0a2829a2bf8581f02ff98ab95"
        }
      ]
    }
  ]
}
