{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-bedrock-client/0.3.0.1/prompt-executor-bedrock-client-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-bedrock-client",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.1.jar",
          "size": 290673,
          "sha512": "858265ccb1a6ec02b5907deb56fd4d861c71ddead293d6f663140a9446a5d8446ebc9838f6360a76de448e725423915252fe2d69a8aad0b22d1323dd9a058fe3",
          "sha256": "2b4813b65a75bc973041a93d455e4d863293c1c005e96be50fff1173ea4e3f7b",
          "sha1": "4bfe04e518d42ca70cab9816a079a86df393294e",
          "md5": "b49b02857c7080120d017dc8c26f02b4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "bedrockruntime",
          "version": {
            "requires": "1.4.119"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.1.jar",
          "size": 290673,
          "sha512": "858265ccb1a6ec02b5907deb56fd4d861c71ddead293d6f663140a9446a5d8446ebc9838f6360a76de448e725423915252fe2d69a8aad0b22d1323dd9a058fe3",
          "sha256": "2b4813b65a75bc973041a93d455e4d863293c1c005e96be50fff1173ea4e3f7b",
          "sha1": "4bfe04e518d42ca70cab9816a079a86df393294e",
          "md5": "b49b02857c7080120d017dc8c26f02b4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-bedrock-client-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-bedrock-client-jvm-0.3.0.1-sources.jar",
          "size": 21720,
          "sha512": "9491a6d22dbb050efc7c66dd6556b4b1c1966c44eb025cf8ec7459f3c35683c2542ee5c314ef771081cdb6fa5411e259627b3bd273f1a68f0383db6f5f46cb2c",
          "sha256": "6f6760b0034fe7d0a45718664d16df8414ef65470134e82b428ab4859618de73",
          "sha1": "122e4131eb414dc1162c07c1f4f21c428dfec868",
          "md5": "59bf77a0e01412f82fade43bc23b0278"
        }
      ]
    }
  ]
}
