{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-files/0.3.0.4/prompt-cache-files-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-cache-files",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.4.jar",
          "url": "prompt-cache-files-jvm-0.3.0.4.jar",
          "size": 18448,
          "sha512": "ecaf480ed3eb6c0d8b8a80472006fb990165157828cc5ba36c0d6527bc1b913c351409f6628e9ae8afa160df5f57f61b2d1cc20c6fe4083b409864184d94f159",
          "sha256": "52a6e975fd5fc1f88dfa8909c1434f129f2fb8e1ec633c3acdbc7f89f29db92e",
          "sha1": "9eba9007b1c52298f615f8769a72d9e9de80113c",
          "md5": "56a1317755c78b270ffdd372e2efc9b1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.4.jar",
          "url": "prompt-cache-files-jvm-0.3.0.4.jar",
          "size": 18448,
          "sha512": "ecaf480ed3eb6c0d8b8a80472006fb990165157828cc5ba36c0d6527bc1b913c351409f6628e9ae8afa160df5f57f61b2d1cc20c6fe4083b409864184d94f159",
          "sha256": "52a6e975fd5fc1f88dfa8909c1434f129f2fb8e1ec633c3acdbc7f89f29db92e",
          "sha1": "9eba9007b1c52298f615f8769a72d9e9de80113c",
          "md5": "56a1317755c78b270ffdd372e2efc9b1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.4-sources.jar",
          "url": "prompt-cache-files-jvm-0.3.0.4-sources.jar",
          "size": 2970,
          "sha512": "225e701a8d054eb310e1f54889e8e68fdcb0aaf51e702409a08c8162aafefdff3698b29b2da15a9a9bfd484569ac06dbc1f7d291735abd98ca8ffe1074ce00ad",
          "sha256": "24caa2d9e7873d46b6f06398ea09dc2d9fb7e061fa6f3e12a20947d60b5737e2",
          "sha1": "8feee901ecb03e2ac8da3c1ead9a9076a3eb1a66",
          "md5": "2fe549439e3f4bc97428a3f378038020"
        }
      ]
    }
  ]
}
