{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-model/0.3.0.3/prompt-executor-model-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-executor-model",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.3.jar",
          "url": "prompt-executor-model-jvm-0.3.0.3.jar",
          "size": 8141,
          "sha512": "3aa5a6a8879fee49439ee78fafacedb4344790a3d67c5a6b6eee58786ecd5568f7b5c6fd045aebaa7d9fe8a78dc7190671daa486c3aab21dff056f6ff668499e",
          "sha256": "7570976adddad865c675f29c2143d999b16d71f5d236280017e988c2bf482799",
          "sha1": "6605220835d99e568f17d363ed2f0f58bd4979ec",
          "md5": "139e58314d0e7f389254686faaf25ec5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.3.jar",
          "url": "prompt-executor-model-jvm-0.3.0.3.jar",
          "size": 8141,
          "sha512": "3aa5a6a8879fee49439ee78fafacedb4344790a3d67c5a6b6eee58786ecd5568f7b5c6fd045aebaa7d9fe8a78dc7190671daa486c3aab21dff056f6ff668499e",
          "sha256": "7570976adddad865c675f29c2143d999b16d71f5d236280017e988c2bf482799",
          "sha1": "6605220835d99e568f17d363ed2f0f58bd4979ec",
          "md5": "139e58314d0e7f389254686faaf25ec5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-model-jvm-0.3.0.3-sources.jar",
          "url": "prompt-executor-model-jvm-0.3.0.3-sources.jar",
          "size": 3514,
          "sha512": "16b0e0a6912cd480510b84e491f3fff08d119d9f89c91c53bc46351d4f42b736f5286e6408220b7f96b45d09ec61d0fe8f056138fd222a7ede0396131573af50",
          "sha256": "2a9769c146eac511a329e8c581ae4c3da804cefacd34bc99a51c1cc2b4aaa5bf",
          "sha1": "2fc5a4e0bd3ba88a22b192cb807d74809ebc089e",
          "md5": "1fff4c6fda3d72f3132461a2bd5425e0"
        }
      ]
    }
  ]
}
