{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-structure/0.3.0.2/prompt-structure-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-structure",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.2.jar",
          "url": "prompt-structure-jvm-0.3.0.2.jar",
          "size": 102998,
          "sha512": "d4942daf0bc86c636a06fa086bf6dcb1860e4c1ba78c8650fc6d2d4641fd8fc1443bc2c93735a3d2130888cd77217ec000fa6054d915ea5f78da37c59523bf31",
          "sha256": "a479d843d6a12a436d3850c0698ec9d514fe54f54442ced37a59e075b8c48518",
          "sha1": "800d73abeb18218fe7c09e3efd3b91528cdb9957",
          "md5": "27d17cbcb332b65a59cb137595a94784"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.2.jar",
          "url": "prompt-structure-jvm-0.3.0.2.jar",
          "size": 102998,
          "sha512": "d4942daf0bc86c636a06fa086bf6dcb1860e4c1ba78c8650fc6d2d4641fd8fc1443bc2c93735a3d2130888cd77217ec000fa6054d915ea5f78da37c59523bf31",
          "sha256": "a479d843d6a12a436d3850c0698ec9d514fe54f54442ced37a59e075b8c48518",
          "sha1": "800d73abeb18218fe7c09e3efd3b91528cdb9957",
          "md5": "27d17cbcb332b65a59cb137595a94784"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.2-sources.jar",
          "url": "prompt-structure-jvm-0.3.0.2-sources.jar",
          "size": 27083,
          "sha512": "5250c66d20748c0b806880f3bcadd10974d9fce61b8170c456beb544c28b4c99d625e52e20cf528ee112d777c668ef9b927cf9b287681b93b34c8de1da6d1545",
          "sha256": "ea31e982ba60a38f96019e99d6f2a722a314af16a605d1f4bc51761110633d6a",
          "sha1": "aa01e369cc1be7f8d1ddf432020ec37b319b1e48",
          "md5": "ac7eebd2009db0043d906d30f7ddfc99"
        }
      ]
    }
  ]
}
