{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koog-ktor/0.3.0.1/koog-ktor-0.3.0.1.module",
    "group": "ai.koog",
    "module": "koog-ktor",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.1.jar",
          "url": "koog-ktor-jvm-0.3.0.1.jar",
          "size": 67495,
          "sha512": "dd7e1b4f90081fbe28172c0fc1ab056c338b0f7f9fd9ab4707746c3c3235c297dcbe955e2986d5c924cebe0cfd8f23fcd30f23743e5462c512f351e612a948d2",
          "sha256": "c62700765146dfa08c289168403a6e135a8d9c508d09bcb97b428cb52e051cb7",
          "sha1": "dd4757a9cb1cd893293dc83154426544975f8a0c",
          "md5": "e30f033d3aed57a35f85b8b963e11b76"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-mcp",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.1.jar",
          "url": "koog-ktor-jvm-0.3.0.1.jar",
          "size": 67495,
          "sha512": "dd7e1b4f90081fbe28172c0fc1ab056c338b0f7f9fd9ab4707746c3c3235c297dcbe955e2986d5c924cebe0cfd8f23fcd30f23743e5462c512f351e612a948d2",
          "sha256": "c62700765146dfa08c289168403a6e135a8d9c508d09bcb97b428cb52e051cb7",
          "sha1": "dd4757a9cb1cd893293dc83154426544975f8a0c",
          "md5": "e30f033d3aed57a35f85b8b963e11b76"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koog-ktor-jvm-0.3.0.1-sources.jar",
          "url": "koog-ktor-jvm-0.3.0.1-sources.jar",
          "size": 18184,
          "sha512": "2ce30654581889b1de588c32e98bf110656e94af8ee24ab7e6dd69cfe1bb7853b0c4bb8b6acdce99bd9c17912f7947d09712d9f4e73cc69b70180a2fb3557f96",
          "sha256": "bec4ade9a93f5da6d32b87975a041c4e3f3d58b321a39fec98e1c8ac6122aae3",
          "sha1": "c4e18eed216dfcb529d1c29b1a5c3a265d40b825",
          "md5": "8c588c83735ca65e5b5ac4641b817b33"
        }
      ]
    }
  ]
}
