{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-redis/0.3.0.1/prompt-cache-redis-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-cache-redis",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.1.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.1.jar",
          "size": 18570,
          "sha512": "b07a359626ea68b1f079fa1de7e8109161904f8af9827360e160ccff9551154e63d953876189dcfa28e45aba4100a85579e44f58421ed4f6848e21e2e316b6b6",
          "sha256": "6f7f3c2ce40d9997e6f827aa6834150356090e35a2f157c6b894920bf4215937",
          "sha1": "4804a73ada71505a62eb5bb766279b739a60fcde",
          "md5": "b1a47462aaf6cb1b1caecddf4a00a02d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.5.5.RELEASE"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.1.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.1.jar",
          "size": 18570,
          "sha512": "b07a359626ea68b1f079fa1de7e8109161904f8af9827360e160ccff9551154e63d953876189dcfa28e45aba4100a85579e44f58421ed4f6848e21e2e316b6b6",
          "sha256": "6f7f3c2ce40d9997e6f827aa6834150356090e35a2f157c6b894920bf4215937",
          "sha1": "4804a73ada71505a62eb5bb766279b739a60fcde",
          "md5": "b1a47462aaf6cb1b1caecddf4a00a02d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-redis-jvm-0.3.0.1-sources.jar",
          "url": "prompt-cache-redis-jvm-0.3.0.1-sources.jar",
          "size": 3026,
          "sha512": "f05e22eff9f0abd76db04cd5f374599fcf2cc9aa9cc1a10daa89b593dc634cfb2ae69fae06446466bbedd9619c79241614e6f77888a07396042220d46e31f492",
          "sha256": "c9684cbc1d850747a00bdcaf3c5d4755eeeb170204f6f48c3d7e8765178ca6d5",
          "sha1": "ce4cc57ec800eb1932568b1d9979907dd561ac29",
          "md5": "8d6f6b7f434e64840e118577df1a4d15"
        }
      ]
    }
  ]
}
