{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-executor-llms",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-metadata-0.3.0.4.jar",
          "url": "prompt-executor-llms-0.3.0.4.jar",
          "size": 3902,
          "sha512": "1bbf3d092b1418f6d3a5492eba164a5e406ba0128f5785c143f6f0836060f2ab29052bf93be07a1c40d0c896c59b1dfb3fbdf30586e08bfd53fd080a037aa458",
          "sha256": "35ca483b51becd611e80779daf3090ef9d1604b4c0c67dca4441e2a3bd7cafd8",
          "sha1": "07d52ba5233742906a95a1baaacad191ecb7e589",
          "md5": "fa761424a75abbb74c34422a9f606cf4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-executor-llms-kotlin-0.3.0.4-sources.jar",
          "url": "prompt-executor-llms-0.3.0.4-sources.jar",
          "size": 4662,
          "sha512": "a2abccd591a749f639d52684fbc65a7b96f8a0c1c214ae427f0ac87759e2e83b13beed6cbbd4561d96ab91dfa66c9a1a47e0bbe5c63f51a7c5209e0e6b8716c6",
          "sha256": "4e770f73bfb17387fa9e05bdc70731a08c3edde3741e2a12a7de7e097f810725",
          "sha1": "e8449b0d6bfa6915d7002b94fa833b675ddeb23e",
          "md5": "5427be1e4d7344e38e3c534142e91e13"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-js/0.3.0.4/prompt-executor-llms-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-js/0.3.0.4/prompt-executor-llms-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-js/0.3.0.4/prompt-executor-llms-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-jvm/0.3.0.4/prompt-executor-llms-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-jvm/0.3.0.4/prompt-executor-llms-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-jvm/0.3.0.4/prompt-executor-llms-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-wasm-js/0.3.0.4/prompt-executor-llms-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-wasm-js/0.3.0.4/prompt-executor-llms-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-llms-wasm-js/0.3.0.4/prompt-executor-llms-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "prompt-executor-llms-wasm-js",
        "version": "0.3.0.4"
      }
    }
  ]
}
