{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-structure/0.3.0.1/prompt-structure-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-structure",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.1.jar",
          "url": "prompt-structure-jvm-0.3.0.1.jar",
          "size": 102997,
          "sha512": "3a549f233c1c878abb8c2d8674173362d391dabf7f412b10a8fa26278138636af87bef9eb2f68e326b0be3a4f72754cac00c17e8ffc9390e3342e79c1f61c5ee",
          "sha256": "ba5d52d2b1c80263fd0c100b408831b0ee780e63255587cfd9db81674c4dd76a",
          "sha1": "c8a55149e5e3ad1c4884a659b7a5ee35706a166e",
          "md5": "796e695baae2c81f7618a7eda9b2a586"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.1.jar",
          "url": "prompt-structure-jvm-0.3.0.1.jar",
          "size": 102997,
          "sha512": "3a549f233c1c878abb8c2d8674173362d391dabf7f412b10a8fa26278138636af87bef9eb2f68e326b0be3a4f72754cac00c17e8ffc9390e3342e79c1f61c5ee",
          "sha256": "ba5d52d2b1c80263fd0c100b408831b0ee780e63255587cfd9db81674c4dd76a",
          "sha1": "c8a55149e5e3ad1c4884a659b7a5ee35706a166e",
          "md5": "796e695baae2c81f7618a7eda9b2a586"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-structure-jvm-0.3.0.1-sources.jar",
          "url": "prompt-structure-jvm-0.3.0.1-sources.jar",
          "size": 27083,
          "sha512": "5250c66d20748c0b806880f3bcadd10974d9fce61b8170c456beb544c28b4c99d625e52e20cf528ee112d777c668ef9b927cf9b287681b93b34c8de1da6d1545",
          "sha256": "ea31e982ba60a38f96019e99d6f2a722a314af16a605d1f4bc51761110633d6a",
          "sha1": "aa01e369cc1be7f8d1ddf432020ec37b319b1e48",
          "md5": "ac7eebd2009db0043d906d30f7ddfc99"
        }
      ]
    }
  ]
}
