{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-model/0.3.0.3/prompt-cache-model-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-cache-model",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.3.jar",
          "url": "prompt-cache-model-jvm-0.3.0.3.jar",
          "size": 26846,
          "sha512": "6139910006eb36d18f0feb36093100c0bf05684bbdc604b0ba520d4930e327090f8a57a17fad534e2f0a25ae19f13bbc833ff111e7d59810ac06dfffc4ba7dca",
          "sha256": "b57391f055a97770dd3da33afb210a55e8799cb64932fb44b3cd6ce9ceca6712",
          "sha1": "5e7e4257c35adddff85387f9630805e34fb8619a",
          "md5": "fb49507befbb4fab8c6638b121f3f578"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.3.jar",
          "url": "prompt-cache-model-jvm-0.3.0.3.jar",
          "size": 26846,
          "sha512": "6139910006eb36d18f0feb36093100c0bf05684bbdc604b0ba520d4930e327090f8a57a17fad534e2f0a25ae19f13bbc833ff111e7d59810ac06dfffc4ba7dca",
          "sha256": "b57391f055a97770dd3da33afb210a55e8799cb64932fb44b3cd6ce9ceca6712",
          "sha1": "5e7e4257c35adddff85387f9630805e34fb8619a",
          "md5": "fb49507befbb4fab8c6638b121f3f578"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.3-sources.jar",
          "url": "prompt-cache-model-jvm-0.3.0.3-sources.jar",
          "size": 5387,
          "sha512": "921ded8a17f300ee79282cb0c5208cbf7983bafb2ce29900e9275ae2cacc19a05cf2b0fd6e58754673a6d0438ec288f1ab7754943f452018e9bedbf12964e86a",
          "sha256": "70ef07d5f664bd89cd2a358e2b7f721c939f4e414bef1a74825a90f9d6f215f7",
          "sha1": "efa4b7ea08c4aff3efc74dc6249dcd0eb6d5e15a",
          "md5": "4f1231cef25bed1632442ae8ddfa0e47"
        }
      ]
    }
  ]
}
