{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-model/0.3.0.4/prompt-cache-model-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-cache-model",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-js-0.3.0.4.klib",
          "url": "prompt-cache-model-js-0.3.0.4.klib",
          "size": 26179,
          "sha512": "92aab3141514c5a27023cc3cbdd85edf4a163c62cc68e361d47e9ae032533a8477880c0f400a68eb1fc8b8a9a890896379264e74c38e155c5153d2315cd3ccbf",
          "sha256": "aa07b716f81cf3a8747a58ed1e828b4792b52e3103f599d89a2565bc81b2ee13",
          "sha1": "720213694c7f6c7979602d71f2d952e68df15f4b",
          "md5": "013d3c8ac0a10db977c576a3b0633f80"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-js-0.3.0.4.klib",
          "url": "prompt-cache-model-js-0.3.0.4.klib",
          "size": 26179,
          "sha512": "92aab3141514c5a27023cc3cbdd85edf4a163c62cc68e361d47e9ae032533a8477880c0f400a68eb1fc8b8a9a890896379264e74c38e155c5153d2315cd3ccbf",
          "sha256": "aa07b716f81cf3a8747a58ed1e828b4792b52e3103f599d89a2565bc81b2ee13",
          "sha1": "720213694c7f6c7979602d71f2d952e68df15f4b",
          "md5": "013d3c8ac0a10db977c576a3b0633f80"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-cache-model-js-0.3.0.4-sources.jar",
          "url": "prompt-cache-model-js-0.3.0.4-sources.jar",
          "size": 5387,
          "sha512": "921ded8a17f300ee79282cb0c5208cbf7983bafb2ce29900e9275ae2cacc19a05cf2b0fd6e58754673a6d0438ec288f1ab7754943f452018e9bedbf12964e86a",
          "sha256": "70ef07d5f664bd89cd2a358e2b7f721c939f4e414bef1a74825a90f9d6f215f7",
          "sha1": "efa4b7ea08c4aff3efc74dc6249dcd0eb6d5e15a",
          "md5": "4f1231cef25bed1632442ae8ddfa0e47"
        }
      ]
    }
  ]
}
