{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "rag-base",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-metadata-0.3.0.1.jar",
          "url": "rag-base-0.3.0.1.jar",
          "size": 11605,
          "sha512": "0165126c20240602fd45d33c7f8024904aee14fc68772ab2c61834122abd9702a666ea161a2522bb3eeebe70b9107cc9bc8c36ffbfedf8baf9abd250fea3521e",
          "sha256": "f1d72032bad7e47e774d867f7339b9b47413560ab6bd8b5ce3e959b0993f2925",
          "sha1": "896f633de18acbe4538ef838608cebed2593b353",
          "md5": "e0593087d48390625808cf50c9c6a501"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "rag-base-kotlin-0.3.0.1-sources.jar",
          "url": "rag-base-0.3.0.1-sources.jar",
          "size": 17585,
          "sha512": "bd56de8af7061bf8ab7c9186b03d4d2a71a0687554f22fe3d2038147785d76d1a792ff8a066b86abb9a5b1afb058c6d96496252d0ae81d63e4d6d41a118a17c2",
          "sha256": "69533d8d5e6c0e08c81fcf8e7d84a21177aad3e7d40c66de3335419fdfe3d656",
          "sha1": "482e17c8bb8042c664a7bc5b153ae06a63ac9b16",
          "md5": "d092141bacf38f14ebf5349d68860d89"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rag-base-js/0.3.0.1/rag-base-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rag-base-js/0.3.0.1/rag-base-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rag-base-js/0.3.0.1/rag-base-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rag-base-jvm/0.3.0.1/rag-base-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rag-base-jvm/0.3.0.1/rag-base-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rag-base-jvm/0.3.0.1/rag-base-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../rag-base-wasm-js/0.3.0.1/rag-base-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../rag-base-wasm-js/0.3.0.1/rag-base-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../rag-base-wasm-js/0.3.0.1/rag-base-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "rag-base-wasm-js",
        "version": "0.3.0.1"
      }
    }
  ]
}
