{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "agents-features-tokenizer",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-tokenizer-metadata-0.3.0.3.jar",
          "url": "agents-features-tokenizer-0.3.0.3.jar",
          "size": 2943,
          "sha512": "982bb82a36dd1a744645b7b280d07e7440a1e9d43d9383841677c31be5197d2098a6484f4efc05599e137d3a359dbcd98e3c0f7cae4be2b05aeb99880f55981a",
          "sha256": "a65c7b47501c4daaf87a3ecb90311d52eeef8bb5eb48de3e986377124bd58ecf",
          "sha1": "23ae8977a3600a2b4a06a982b193d4b28534dd28",
          "md5": "e92fe4d6e3d2bf3ce3eb62829affc153"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "agents-features-tokenizer-kotlin-0.3.0.3-sources.jar",
          "url": "agents-features-tokenizer-0.3.0.3-sources.jar",
          "size": 4408,
          "sha512": "971fd1dcbbf34e351e5973cce924aa7af2fbfb01872a7476a60547b7c51cddc73f5bdbf0dfc86d203a6fc62c18894d33dfe7ad4bba33e7dc2178b0d773d45b73",
          "sha256": "f4a8dba2f14c54d1ee0842b49bfd48a93017528e79727bbf5b74304dd0d41c21",
          "sha1": "ca5e50b9cdd1b782ff14f94f3e93c081f4fc4220",
          "md5": "52b3d625bed4a02e0aafba87682b43d5"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-js/0.3.0.3/agents-features-tokenizer-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-js/0.3.0.3/agents-features-tokenizer-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-js/0.3.0.3/agents-features-tokenizer-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-jvm/0.3.0.3/agents-features-tokenizer-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-jvm/0.3.0.3/agents-features-tokenizer-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-jvm/0.3.0.3/agents-features-tokenizer-jvm-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-jvm",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-wasm-js/0.3.0.3/agents-features-tokenizer-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-wasm-js/0.3.0.3/agents-features-tokenizer-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-wasm-js",
        "version": "0.3.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-tokenizer-wasm-js/0.3.0.3/agents-features-tokenizer-wasm-js-0.3.0.3.module",
        "group": "ai.koog",
        "module": "agents-features-tokenizer-wasm-js",
        "version": "0.3.0.3"
      }
    }
  ]
}
