{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-ext/0.3.0.4/agents-ext-0.3.0.4.module",
    "group": "ai.koog",
    "module": "agents-ext",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.4.jar",
          "url": "agents-ext-jvm-0.3.0.4.jar",
          "size": 214027,
          "sha512": "e882832ecb952cd5d573400637855bd5666b526f39224eaac3b06e4d9864cfe5da3f34910080a9aa0d0c1e82926d2d08e42cba2d1bde9cd60d4029fb7b207e1f",
          "sha256": "55a363310c5c4286f3d109e400ebcefd7deb9ab39817ced15805437d08d52230",
          "sha1": "91cd6f5b61a284264a33db56f3d04fb48eb0f0c6",
          "md5": "c7c9705e8572819aa23395247e39c5b2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.4.jar",
          "url": "agents-ext-jvm-0.3.0.4.jar",
          "size": 214027,
          "sha512": "e882832ecb952cd5d573400637855bd5666b526f39224eaac3b06e4d9864cfe5da3f34910080a9aa0d0c1e82926d2d08e42cba2d1bde9cd60d4029fb7b207e1f",
          "sha256": "55a363310c5c4286f3d109e400ebcefd7deb9ab39817ced15805437d08d52230",
          "sha1": "91cd6f5b61a284264a33db56f3d04fb48eb0f0c6",
          "md5": "c7c9705e8572819aa23395247e39c5b2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-ext-jvm-0.3.0.4-sources.jar",
          "url": "agents-ext-jvm-0.3.0.4-sources.jar",
          "size": 15660,
          "sha512": "d595d7273d7f55ffae4f6431b05057446610ef1cd669bf6df2207b6c135cd1e8def4450f90b71c8348c274614a914f787579848de16192cfc28ed81c879f1c38",
          "sha256": "022362051cc88c5d1d4303b9ff0601c3d8078c6222d0266e6c3080527246bdd3",
          "sha1": "d8614bf76dc191e67761ac9b0213f066d9b80460",
          "md5": "6cd796ed1435b716c8251eac651905a3"
        }
      ]
    }
  ]
}
