{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "embeddings-llm",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "embeddings-llm-metadata-0.3.0.2.jar",
          "url": "embeddings-llm-0.3.0.2.jar",
          "size": 2958,
          "sha512": "d95de7bb8c4da3e160da74f2c0b3432f089a8b6ebb755e54a9c3881001789e607c8eac7f6f00170a3d0e67cb6a28aeffbff5e0fa09ecfdbcac150d0b6011d31e",
          "sha256": "fb04ec7df9c60b76f7f69ff8cab0fce878a2b6fb9d7f482c4cad29093f8c2496",
          "sha1": "8337491ef61c31b14c07600711da8e43f2198e2e",
          "md5": "8f48c74c92ef5aea3210f3e9a3f9fdd2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "embeddings-llm-kotlin-0.3.0.2-sources.jar",
          "url": "embeddings-llm-0.3.0.2-sources.jar",
          "size": 2783,
          "sha512": "d99ad3b05573252e3e4f0e0df656bc1b324e242ad6eaabcb27269629adbd9380785a0bbd1749c38b6300001ee11ed6bbbe313ef2ce18aa48fbe13bca05d37061",
          "sha256": "dc6b88c2d48470f108268f6247faf4abbcf61965e62d041183ea5c97c2102077",
          "sha1": "9b2a1d13f4429ef8ff967a44fd7b02a38680aab5",
          "md5": "3fb535fcc8f56099b1192018f2676884"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-js/0.3.0.2/embeddings-llm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-js/0.3.0.2/embeddings-llm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-js/0.3.0.2/embeddings-llm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embeddings-llm-jvm/0.3.0.2/embeddings-llm-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embeddings-llm-jvm/0.3.0.2/embeddings-llm-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embeddings-llm-jvm/0.3.0.2/embeddings-llm-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-wasm-js/0.3.0.2/embeddings-llm-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-wasm-js/0.3.0.2/embeddings-llm-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embeddings-llm-wasm-js/0.3.0.2/embeddings-llm-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "embeddings-llm-wasm-js",
        "version": "0.3.0.2"
      }
    }
  ]
}
