{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-xml/0.3.0.4/prompt-xml-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-xml",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.4.jar",
          "url": "prompt-xml-jvm-0.3.0.4.jar",
          "size": 7320,
          "sha512": "cb337a1b2a5c40e76d993360d0fa2c9fae1068af84cfd34d32771f5ba4f28d9302b2b99feaefc0fe83ee336fe891b627b759c1b9a77b5f91dc9efde498c543e6",
          "sha256": "880a1995a5b5495e267073923fffcf04f3a52d4a42825be175ec4a5a3c5efdd9",
          "sha1": "5b933c6606d78099fd700fbe994bff40aec208aa",
          "md5": "60e676a807f47cc7dfaa6838557b368d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.4.jar",
          "url": "prompt-xml-jvm-0.3.0.4.jar",
          "size": 7320,
          "sha512": "cb337a1b2a5c40e76d993360d0fa2c9fae1068af84cfd34d32771f5ba4f28d9302b2b99feaefc0fe83ee336fe891b627b759c1b9a77b5f91dc9efde498c543e6",
          "sha256": "880a1995a5b5495e267073923fffcf04f3a52d4a42825be175ec4a5a3c5efdd9",
          "sha1": "5b933c6606d78099fd700fbe994bff40aec208aa",
          "md5": "60e676a807f47cc7dfaa6838557b368d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.4-sources.jar",
          "url": "prompt-xml-jvm-0.3.0.4-sources.jar",
          "size": 2531,
          "sha512": "6d51a670528f215f3a2f2d83286b0acb452bc655ab3095ffc7c65db8fe4ff68360f451c4336d3c6413501b42fc02c771dc76fb51d7b9621c0530c87594688f9b",
          "sha256": "3abed046ad0da624dbd5c4682df923ea37f0bbb8a7498887ce7c61cb9ba92146",
          "sha1": "80e54d1333b6ecc149680e54aba3ba202f8146b3",
          "md5": "11c9dcc6cf24a6e053fd0390dbd9fb86"
        }
      ]
    }
  ]
}
