{
  "formatVersion": "1.1",
  "component": {
    "url": "../../vector-storage/0.3.0.1/vector-storage-0.3.0.1.module",
    "group": "ai.koog",
    "module": "vector-storage",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.1.jar",
          "url": "vector-storage-jvm-0.3.0.1.jar",
          "size": 53335,
          "sha512": "149513f9f6a63ba8251879cd4f6a7259549d9dd3a9bdd031db96d418b3af08c2e1fc815e7863f3eb894bfe166e80d8d298e87f1ff29c321c7d28ec6df1a1a292",
          "sha256": "f4262231c4ba977b5d3b10751235ba0a9536a736859bfee12d12bdc97d4eb4a7",
          "sha1": "a31349c5525fb98739ff19a6cd00fbc57b91d42d",
          "md5": "0aa491aa37d8849234026e6a3294821d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.1.jar",
          "url": "vector-storage-jvm-0.3.0.1.jar",
          "size": 53335,
          "sha512": "149513f9f6a63ba8251879cd4f6a7259549d9dd3a9bdd031db96d418b3af08c2e1fc815e7863f3eb894bfe166e80d8d298e87f1ff29c321c7d28ec6df1a1a292",
          "sha256": "f4262231c4ba977b5d3b10751235ba0a9536a736859bfee12d12bdc97d4eb4a7",
          "sha1": "a31349c5525fb98739ff19a6cd00fbc57b91d42d",
          "md5": "0aa491aa37d8849234026e6a3294821d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.1-sources.jar",
          "url": "vector-storage-jvm-0.3.0.1-sources.jar",
          "size": 9535,
          "sha512": "642543700c43474042857bc9e43c898519697815245213a476671dfeca8c8eed6f977b2079d4069d903ed08e25deca7b90c051b227696ab15f8213419d1b70c6",
          "sha256": "32ce7d7b209bb9b9444351e44a212bb9c081c8f7224e9b7094c774c331cebc95",
          "sha1": "589ba1df5e485fa3c2b15a2a983e471fd3eb734e",
          "md5": "fd7a65689a0264a649b0400125653678"
        }
      ]
    }
  ]
}
