{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.4/prompt-markdown-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.4.jar",
          "url": "prompt-markdown-jvm-0.3.0.4.jar",
          "size": 13470,
          "sha512": "718007a1c4eb91a52572dc05a9c3d3d9c641e77ca854ef25833efba22f320501296055367e847c9b2f6f152bc2fa3bd19ed5375afe2602f216294e129689323f",
          "sha256": "3c0c0766ab09867ee0c193b086da6677a6bf1834095dbe88443b41100b64ea8b",
          "sha1": "5386164589ecd450ecadeeb384965deb46bb0b98",
          "md5": "a513667a4b2a65d62a1d417e95938783"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.4.jar",
          "url": "prompt-markdown-jvm-0.3.0.4.jar",
          "size": 13470,
          "sha512": "718007a1c4eb91a52572dc05a9c3d3d9c641e77ca854ef25833efba22f320501296055367e847c9b2f6f152bc2fa3bd19ed5375afe2602f216294e129689323f",
          "sha256": "3c0c0766ab09867ee0c193b086da6677a6bf1834095dbe88443b41100b64ea8b",
          "sha1": "5386164589ecd450ecadeeb384965deb46bb0b98",
          "md5": "a513667a4b2a65d62a1d417e95938783"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-markdown-jvm-0.3.0.4-sources.jar",
          "url": "prompt-markdown-jvm-0.3.0.4-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
