{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-utils/0.3.0.3/agents-utils-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-utils",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.3.jar",
          "url": "agents-utils-jvm-0.3.0.3.jar",
          "size": 4967,
          "sha512": "daed907f4bb387988ceda62e9447e38ea01df61b0e4a6594efc32443a4a14f172b6cb5f42fff4700a43de3f6e437e95ce8d4885b89e9e69e50a23c301e871ed0",
          "sha256": "f03e237752dfa6e68fffbe426015719d00f4c2ad51c7d93afb8e58a85dde462c",
          "sha1": "d192721ec8800d4d76a74d1a4b3f7acd01129113",
          "md5": "894359058735b0a2693304817573365a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.3.jar",
          "url": "agents-utils-jvm-0.3.0.3.jar",
          "size": 4967,
          "sha512": "daed907f4bb387988ceda62e9447e38ea01df61b0e4a6594efc32443a4a14f172b6cb5f42fff4700a43de3f6e437e95ce8d4885b89e9e69e50a23c301e871ed0",
          "sha256": "f03e237752dfa6e68fffbe426015719d00f4c2ad51c7d93afb8e58a85dde462c",
          "sha1": "d192721ec8800d4d76a74d1a4b3f7acd01129113",
          "md5": "894359058735b0a2693304817573365a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-utils-jvm-0.3.0.3-sources.jar",
          "url": "agents-utils-jvm-0.3.0.3-sources.jar",
          "size": 2969,
          "sha512": "86f164457f2d918a0a0f75759f6ba674892f4948aa9cfc8de490227c9d3d525171dd6b32374efde43fcf250bf88a47f989b0583eb3837eed96e442710a167eb5",
          "sha256": "5523d848b18d7ebd8e3a3bf631128a316301459167165553534f0294f205c36a",
          "sha1": "2adac0e68b127e0a6d496fe6a4109c9323a94ae8",
          "md5": "231e82d2c5dc2ddf78df6de56f243952"
        }
      ]
    }
  ]
}
