{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.3/prompt-markdown-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-js-0.3.0.3.klib",
          "url": "prompt-markdown-js-0.3.0.3.klib",
          "size": 15831,
          "sha512": "0faea0783807575faec0402995fc2a5546b8c0ec904f0dea325a023ebd4a081317abab54d1eb6be38b2a1a68a13851cb1831109c09bd09ce29a3dc772736c9cf",
          "sha256": "14971c5db13861ae797f8fb6a4165195a18f597d2ff800b4031729069038532f",
          "sha1": "fe6b9221bb3ca5333ac249b9df486ed567f36083",
          "md5": "9f5911267a505de3bbb9b756d866f45f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-js-0.3.0.3.klib",
          "url": "prompt-markdown-js-0.3.0.3.klib",
          "size": 15831,
          "sha512": "0faea0783807575faec0402995fc2a5546b8c0ec904f0dea325a023ebd4a081317abab54d1eb6be38b2a1a68a13851cb1831109c09bd09ce29a3dc772736c9cf",
          "sha256": "14971c5db13861ae797f8fb6a4165195a18f597d2ff800b4031729069038532f",
          "sha1": "fe6b9221bb3ca5333ac249b9df486ed567f36083",
          "md5": "9f5911267a505de3bbb9b756d866f45f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-markdown-js-0.3.0.3-sources.jar",
          "url": "prompt-markdown-js-0.3.0.3-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
