{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-anthropic-client/0.3.0.3/prompt-executor-anthropic-client-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-executor-anthropic-client",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-anthropic-client-jvm-0.3.0.3.jar",
          "url": "prompt-executor-anthropic-client-jvm-0.3.0.3.jar",
          "size": 186512,
          "sha512": "ebddf3bc37cdacd99af65a8bc6dcbb51520b299b0d2d12e0c32915ed019d6753effe0ef728498844bd4be9b623816bfe84b50bf41d0d925380f9b3f8659bc633",
          "sha256": "d5bdc1bbc23e447049c45271616b6d2d935310319ddb5fdd337fe4835337bdfb",
          "sha1": "a6fb1b88cc20ce54d9658c0c00d8a925ab07c895",
          "md5": "c51d24f1c95ffbb85f5198fc924424ba"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-anthropic-client-jvm-0.3.0.3.jar",
          "url": "prompt-executor-anthropic-client-jvm-0.3.0.3.jar",
          "size": 186512,
          "sha512": "ebddf3bc37cdacd99af65a8bc6dcbb51520b299b0d2d12e0c32915ed019d6753effe0ef728498844bd4be9b623816bfe84b50bf41d0d925380f9b3f8659bc633",
          "sha256": "d5bdc1bbc23e447049c45271616b6d2d935310319ddb5fdd337fe4835337bdfb",
          "sha1": "a6fb1b88cc20ce54d9658c0c00d8a925ab07c895",
          "md5": "c51d24f1c95ffbb85f5198fc924424ba"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-anthropic-client-jvm-0.3.0.3-sources.jar",
          "url": "prompt-executor-anthropic-client-jvm-0.3.0.3-sources.jar",
          "size": 12398,
          "sha512": "63525d36536fbb788fa2deba57142cd227dbc6fe633001b65ac42cad3ca0285d61cfb5db55bb0609b4abb580b24e22974ba6fea1bc08c6f748abac26c857de61",
          "sha256": "5fc9215714e4ffd086d6155ab84500298f78a37251e2435595a9a17e7d8a49ef",
          "sha1": "2ca1afe1b8a336eca96147582c6f4957251d82b8",
          "md5": "a02462cb6e35f7ab60e703c32725ed64"
        }
      ]
    }
  ]
}
