{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-snapshot/0.3.0.1/agents-features-snapshot-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-snapshot",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.1.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.1.jar",
          "size": 57653,
          "sha512": "77bc2558ce780ba92bdf202a0e9dbe915c80b49e8056d64d2cc780fc9b33139d7d1a54b73e4cf05cb0563107e26e5219da15abf5363d5d1e9227cb0efe2f2f56",
          "sha256": "bf037c92b3e30c3d00263195e04b4bfa450b2c0123b44f7aa34cdda66195ed16",
          "sha1": "bfbec40b98ce7418323c402a3a506e788e6ec334",
          "md5": "c271792267a27d1ba0c90fe9907e315c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.1.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.1.jar",
          "size": 57653,
          "sha512": "77bc2558ce780ba92bdf202a0e9dbe915c80b49e8056d64d2cc780fc9b33139d7d1a54b73e4cf05cb0563107e26e5219da15abf5363d5d1e9227cb0efe2f2f56",
          "sha256": "bf037c92b3e30c3d00263195e04b4bfa450b2c0123b44f7aa34cdda66195ed16",
          "sha1": "bfbec40b98ce7418323c402a3a506e788e6ec334",
          "md5": "c271792267a27d1ba0c90fe9907e315c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.1-sources.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.1-sources.jar",
          "size": 11197,
          "sha512": "2003e6fe0cad57845d79b981e1c2934dbd6acd6f29b14f8391004f1dda3858399d7d6bd307fbf2db98f8c68a58131c46eef1944cc3f861c8897ffca2aa7605c4",
          "sha256": "98314cf24bce5f5e05a1260175af747987a48e04f9fbd4973b9dd92d02a8b5a8",
          "sha1": "7f856949d85590a48a6f787cb4da52fa2de74578",
          "md5": "b56a49d290cc1679eb4b590fbec6de18"
        }
      ]
    }
  ]
}
