{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rag-base/0.3.0.3/rag-base-0.3.0.3.module",
    "group": "ai.koog",
    "module": "rag-base",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.3.jar",
          "url": "rag-base-jvm-0.3.0.3.jar",
          "size": 157442,
          "sha512": "06acf0a070ae1d5dbee5bfd80d775c6b042e807f7a72818cc1e19d901f006fdc87605c918f89d1d3138347ab7a8cb2c6ccde1801652460401bfaaff6d4fa472f",
          "sha256": "cf812e3894cda21d2492f653f1eaec5c6de4c89df64f87d7fc91ce9067eb14a7",
          "sha1": "857ad1930e6ff57299243cdffafab2c1853a81d8",
          "md5": "3d0cf4a03df2885b04f41af236eaa052"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.3.jar",
          "url": "rag-base-jvm-0.3.0.3.jar",
          "size": 157442,
          "sha512": "06acf0a070ae1d5dbee5bfd80d775c6b042e807f7a72818cc1e19d901f006fdc87605c918f89d1d3138347ab7a8cb2c6ccde1801652460401bfaaff6d4fa472f",
          "sha256": "cf812e3894cda21d2492f653f1eaec5c6de4c89df64f87d7fc91ce9067eb14a7",
          "sha1": "857ad1930e6ff57299243cdffafab2c1853a81d8",
          "md5": "3d0cf4a03df2885b04f41af236eaa052"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.3-sources.jar",
          "url": "rag-base-jvm-0.3.0.3-sources.jar",
          "size": 24985,
          "sha512": "7679b841ae8c6f1a135225a11f557ccf9b0e6b5c5ed2efbf2e985dc24eed805585e11d14ba16e3fd0f9b1c7d9b5a8a6ae710cabefe77841acc1574ce5e38ed61",
          "sha256": "a679b8ca7924d6ad80dc51bd14200bf4a4e1f333ef56ef8dcad4ef7f3369a055",
          "sha1": "03b2c803b36179ce93c37e9ca98e6ff71b219ea4",
          "md5": "e25fef9e71c9a6d3215bbc163378fc0c"
        }
      ]
    }
  ]
}
