{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-xml/0.3.0.2/prompt-xml-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-xml",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.2.jar",
          "url": "prompt-xml-jvm-0.3.0.2.jar",
          "size": 7320,
          "sha512": "d482f78b5b493a7de9a2c2d575c07db604d7d4fca13b019914cdecb40b6540f2ff764da828adabb2e1710154cd798f9b34427e79f172f29e1f6bf2d1027de5a6",
          "sha256": "1813cf1c878dab2d2ec9d05da0bc966db207e911a92f880bf409ea99fe544fdc",
          "sha1": "c1da3642f45e5c2813a136f3cc6b801f6d9df36f",
          "md5": "15e5767041e2c86e3c7253c1460c253a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.2.jar",
          "url": "prompt-xml-jvm-0.3.0.2.jar",
          "size": 7320,
          "sha512": "d482f78b5b493a7de9a2c2d575c07db604d7d4fca13b019914cdecb40b6540f2ff764da828adabb2e1710154cd798f9b34427e79f172f29e1f6bf2d1027de5a6",
          "sha256": "1813cf1c878dab2d2ec9d05da0bc966db207e911a92f880bf409ea99fe544fdc",
          "sha1": "c1da3642f45e5c2813a136f3cc6b801f6d9df36f",
          "md5": "15e5767041e2c86e3c7253c1460c253a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-xml-jvm-0.3.0.2-sources.jar",
          "url": "prompt-xml-jvm-0.3.0.2-sources.jar",
          "size": 2531,
          "sha512": "6d51a670528f215f3a2f2d83286b0acb452bc655ab3095ffc7c65db8fe4ff68360f451c4336d3c6413501b42fc02c771dc76fb51d7b9621c0530c87594688f9b",
          "sha256": "3abed046ad0da624dbd5c4682df923ea37f0bbb8a7498887ce7c61cb9ba92146",
          "sha1": "80e54d1333b6ecc149680e54aba3ba202f8146b3",
          "md5": "11c9dcc6cf24a6e053fd0390dbd9fb86"
        }
      ]
    }
  ]
}
