{
  "formatVersion": "1.1",
  "component": {
    "url": "../../vector-storage/0.3.0.4/vector-storage-0.3.0.4.module",
    "group": "ai.koog",
    "module": "vector-storage",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.4.jar",
          "url": "vector-storage-jvm-0.3.0.4.jar",
          "size": 53335,
          "sha512": "6a7085f77ea9713507bbba7f0e33f72ef56e898e842dfcca2bb6f1c82799662be8082c44db7464741457e1a17883ea29620ccb9e3be1df369863a08c71814f9a",
          "sha256": "9adf36d3b8333271db1e0363575f6821f9b240c64bcf9f8cd9449c0467de6082",
          "sha1": "53f7e9dc5872dc925ba8d494854572ab5322d09b",
          "md5": "ebaf7099549f7e4ab5f5bf3c5a1cdda9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.4.jar",
          "url": "vector-storage-jvm-0.3.0.4.jar",
          "size": 53335,
          "sha512": "6a7085f77ea9713507bbba7f0e33f72ef56e898e842dfcca2bb6f1c82799662be8082c44db7464741457e1a17883ea29620ccb9e3be1df369863a08c71814f9a",
          "sha256": "9adf36d3b8333271db1e0363575f6821f9b240c64bcf9f8cd9449c0467de6082",
          "sha1": "53f7e9dc5872dc925ba8d494854572ab5322d09b",
          "md5": "ebaf7099549f7e4ab5f5bf3c5a1cdda9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vector-storage-jvm-0.3.0.4-sources.jar",
          "url": "vector-storage-jvm-0.3.0.4-sources.jar",
          "size": 9535,
          "sha512": "642543700c43474042857bc9e43c898519697815245213a476671dfeca8c8eed6f977b2079d4069d903ed08e25deca7b90c051b227696ab15f8213419d1b70c6",
          "sha256": "32ce7d7b209bb9b9444351e44a212bb9c081c8f7224e9b7094c774c331cebc95",
          "sha1": "589ba1df5e485fa3c2b15a2a983e471fd3eb734e",
          "md5": "fd7a65689a0264a649b0400125653678"
        }
      ]
    }
  ]
}
