{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-openrouter-client/0.3.0.1/prompt-executor-openrouter-client-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-openrouter-client",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.1.jar",
          "size": 185253,
          "sha512": "2d8eeb6edfdbb1ebc8af268ea28cc49b6ddbe4e9c5e1e9aef3e5a35e406f98ddde2f538a29eb0fa1c6b63ee33343a63d52099ceda8fdd0703bc273811a475266",
          "sha256": "51413cfa3bb4db9b0bb48da3fd96129529158e928862d6a7ecd8c2fb8dfaa61c",
          "sha1": "474c1e9587ef7a0d01778ae78d358758e62fb342",
          "md5": "8e67aff9455e7bf556b33eb536250410"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.1.jar",
          "size": 185253,
          "sha512": "2d8eeb6edfdbb1ebc8af268ea28cc49b6ddbe4e9c5e1e9aef3e5a35e406f98ddde2f538a29eb0fa1c6b63ee33343a63d52099ceda8fdd0703bc273811a475266",
          "sha256": "51413cfa3bb4db9b0bb48da3fd96129529158e928862d6a7ecd8c2fb8dfaa61c",
          "sha1": "474c1e9587ef7a0d01778ae78d358758e62fb342",
          "md5": "8e67aff9455e7bf556b33eb536250410"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.1-sources.jar",
          "size": 9666,
          "sha512": "8780e09969e7600327e01a51806e8f36ece928dcc2aaa0dfaf32b083098e24ea1cd7263ae0641d2c8a8f63860991bcc06faec18191249c4a612bb8048bbf8fc4",
          "sha256": "871b0b05567c7dcd6604017dc419912afee30d84a0a3dbbfa6e021611900d0a4",
          "sha1": "06752161d5fbfba252833c5be8d09e270d0fa301",
          "md5": "f25d534714e235a370fddbe1aa0569b5"
        }
      ]
    }
  ]
}
