{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-event-handler/0.3.0.2/agents-features-event-handler-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-features-event-handler",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.2.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.2.jar",
          "size": 129784,
          "sha512": "90ee0d2e24b51435126c6d5abbd9ac6be39c899f8516da046076a3cf974ad2443a7745114ca62de34005c8098773c936b43f6fba00b601fa48d0da65df09317a",
          "sha256": "7ce0eeb2ddf6d20ae7c4b7e735d759d1a64d03f5a7b23dba4a2d0fc91f47b8a0",
          "sha1": "dabfa52d96d187c63495cdc339580254478a30ed",
          "md5": "929ccf47674e54d666f59eb14b1e85fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.2.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.2.jar",
          "size": 129784,
          "sha512": "90ee0d2e24b51435126c6d5abbd9ac6be39c899f8516da046076a3cf974ad2443a7745114ca62de34005c8098773c936b43f6fba00b601fa48d0da65df09317a",
          "sha256": "7ce0eeb2ddf6d20ae7c4b7e735d759d1a64d03f5a7b23dba4a2d0fc91f47b8a0",
          "sha1": "dabfa52d96d187c63495cdc339580254478a30ed",
          "md5": "929ccf47674e54d666f59eb14b1e85fb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-event-handler-jvm-0.3.0.2-sources.jar",
          "url": "agents-features-event-handler-jvm-0.3.0.2-sources.jar",
          "size": 8434,
          "sha512": "a654b29e6be6b215cb6327190e03f05e0be7b6b2bb62a1bad29f1d5e6c7356b0d95e7bfddb893d6b03ec69bb18f4cd753e001a38ba93ec66ae740cc9aaab0763",
          "sha256": "92a4655f88281d04dd0e3e2144029bda7e159da76dd07aa31da05d20a4bd28ec",
          "sha1": "d6152389d166e92c27ca36db6361d24b0a51afed",
          "md5": "e7e14b954f2355755d7d614722a7acfb"
        }
      ]
    }
  ]
}
