{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-tokenizer/0.3.0.1/prompt-tokenizer-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-tokenizer",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.1.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.1.jar",
          "size": 12351,
          "sha512": "a3998204bd8f73c05976b8e8098865d6c30fb1ec178fc97d3c9acd4ec0e44f38eff12d924a8bee49bb1aa976063319b6e9835595dde5872ed199b161f8933e8e",
          "sha256": "f6e86c695718b20525a02cedea6418fc3cecd2b4c7743931019ee4eaa8c068ad",
          "sha1": "a1205f5e0491bf1f9fcd0bd68f63c32172444ff4",
          "md5": "546920b91330f899ae0dca75be42410b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.1.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.1.jar",
          "size": 12351,
          "sha512": "a3998204bd8f73c05976b8e8098865d6c30fb1ec178fc97d3c9acd4ec0e44f38eff12d924a8bee49bb1aa976063319b6e9835595dde5872ed199b161f8933e8e",
          "sha256": "f6e86c695718b20525a02cedea6418fc3cecd2b4c7743931019ee4eaa8c068ad",
          "sha1": "a1205f5e0491bf1f9fcd0bd68f63c32172444ff4",
          "md5": "546920b91330f899ae0dca75be42410b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-tokenizer-jvm-0.3.0.1-sources.jar",
          "url": "prompt-tokenizer-jvm-0.3.0.1-sources.jar",
          "size": 5324,
          "sha512": "9f20b03ab6292e425bc851b11683b9cc6ce0dddc3d6b6b4b042350ed5486fae56b2c116309542261cfa4869e16b5437b411d2d6b4318f65747484d3538ad780a",
          "sha256": "2dc6d3700773b4af3f73e9246fdce6d96535ffeb1534ae1d7c0410fe314453bb",
          "sha1": "4e09855b24b57f5baa052bb8ae81407de6f91891",
          "md5": "f8a904bee7024e89c1166a9ba9c72e34"
        }
      ]
    }
  ]
}
