{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-markdown/0.3.0.4/prompt-markdown-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-markdown",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-wasm-js-0.3.0.4.klib",
          "url": "prompt-markdown-wasm-js-0.3.0.4.klib",
          "size": 15824,
          "sha512": "9c1d20a8b34a09a93baddc5474c4fcdc91f202dcfea84c6d5bf8aee46e384761b9e1484d1ce033462dd02d7bc9df6398c5365fb1f4e3c1033d0a65945196893e",
          "sha256": "a1ace0b097f5f6d5bc721989ca1c219cb5f968158fb8947ad0fb66b1b8bd4d7f",
          "sha1": "a4d82182f16cd55dd9fa0ab30bfcb765477ee7b9",
          "md5": "03f2677666b932609ade15241f7e4012"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-markdown-wasm-js-0.3.0.4.klib",
          "url": "prompt-markdown-wasm-js-0.3.0.4.klib",
          "size": 15824,
          "sha512": "9c1d20a8b34a09a93baddc5474c4fcdc91f202dcfea84c6d5bf8aee46e384761b9e1484d1ce033462dd02d7bc9df6398c5365fb1f4e3c1033d0a65945196893e",
          "sha256": "a1ace0b097f5f6d5bc721989ca1c219cb5f968158fb8947ad0fb66b1b8bd4d7f",
          "sha1": "a4d82182f16cd55dd9fa0ab30bfcb765477ee7b9",
          "md5": "03f2677666b932609ade15241f7e4012"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "prompt-markdown-wasm-js-0.3.0.4-sources.jar",
          "url": "prompt-markdown-wasm-js-0.3.0.4-sources.jar",
          "size": 4267,
          "sha512": "ccab80e2a3f1566b010fdb222cc4325954687262c540f7a3c21413985c576a578a71ba94f8f7aa5868ac11b64e1fda31bfde53dc7f9102c09137c049cbb42c81",
          "sha256": "648d680f756a60a0114c5ea1ba38292614619c8b812ad64e4d64036c8e9cc357",
          "sha1": "a3c275080defc9cd88c1774ca5d262dca4e29be2",
          "md5": "09163b7ee2278c073c8580b3ef374e61"
        }
      ]
    }
  ]
}
