{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "koog-spring-boot-starter",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-spring-boot-starter-0.3.0.1.jar",
          "url": "koog-spring-boot-starter-0.3.0.1.jar",
          "size": 8399,
          "sha512": "b3bb0c27eef4015df7ef19555367e460c08c1336218c400185bd6153c66f7959521377c99d8fc388f94930f1e4bf3561ca93a336c1a6986371052b1850142056",
          "sha256": "a9b13a3ba505928c4f71aa844308fa8eeba9bff422485969e20506e4555c272c",
          "sha1": "0564b42de32891f5666707e1c5054b794cfd40d3",
          "md5": "4b0363a1e106fc755dcae2fea0590960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koog-spring-boot-starter-0.3.0.1.jar",
          "url": "koog-spring-boot-starter-0.3.0.1.jar",
          "size": 8399,
          "sha512": "b3bb0c27eef4015df7ef19555367e460c08c1336218c400185bd6153c66f7959521377c99d8fc388f94930f1e4bf3561ca93a336c1a6986371052b1850142056",
          "sha256": "a9b13a3ba505928c4f71aa844308fa8eeba9bff422485969e20506e4555c272c",
          "sha1": "0564b42de32891f5666707e1c5054b794cfd40d3",
          "md5": "4b0363a1e106fc755dcae2fea0590960"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "koog-spring-boot-starter-0.3.0.1-sources.jar",
          "url": "koog-spring-boot-starter-0.3.0.1-sources.jar",
          "size": 4294,
          "sha512": "cb3ccc067205be0795cc274cf51cf3407c7867ae4133c0b22d56cd3a764deedf1de1fa252e7ab9d0161ba4e847d041c489987199127c143241f7aa481fd21430",
          "sha256": "2e5a15487fd3922f2e93a8c5577a21a8f43cf05d89bf7b7cb500bfdf5665c3ed",
          "sha1": "299e3114367c11ac3989eca28e68d61a035a73e0",
          "md5": "a4bfd475ea4f699a5713db44e8b7ad42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "koog-spring-boot-starter-0.3.0.1-javadoc.jar",
          "url": "koog-spring-boot-starter-0.3.0.1-javadoc.jar",
          "size": 261,
          "sha512": "18548edb04afd9e192aff77cb6da6d1bb9b7331227630bbb849e068eef592e6401bab6ce03373c52f23b5d29bfa7b1f342cd1c805026e188a710b9a7ccc409d3",
          "sha256": "a97d8dfb51ff99e46d3c6803340e4ae150d8d373d82620398316832624cd0295",
          "sha1": "87332646627aae449cbfc3d9786fc7de0a9d03e3",
          "md5": "8e50d373b3a19293631967751c631ac5"
        }
      ]
    }
  ]
}
