{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "prompt-executor-model",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-model-metadata-0.3.0.1.jar",
          "url": "prompt-executor-model-0.3.0.1.jar",
          "size": 3257,
          "sha512": "ec1a0aa28692bf9b1293944f93b000a780e2421a17cd14801e5afa5453337bd4ce5a12c5e56a625139759e5c35437d281ed99cd8d17fac9bb4164d79db855aeb",
          "sha256": "a0ff25a1764957bf510507ce729d7d7b1e0c32e532234da14dab0d0f5aff1879",
          "sha1": "befe85cbd9b3e9f65bd572908c2f895517766b16",
          "md5": "d6bad488d68742c935413b025277a742"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "prompt-executor-model-kotlin-0.3.0.1-sources.jar",
          "url": "prompt-executor-model-0.3.0.1-sources.jar",
          "size": 3514,
          "sha512": "16b0e0a6912cd480510b84e491f3fff08d119d9f89c91c53bc46351d4f42b736f5286e6408220b7f96b45d09ec61d0fe8f056138fd222a7ede0396131573af50",
          "sha256": "2a9769c146eac511a329e8c581ae4c3da804cefacd34bc99a51c1cc2b4aaa5bf",
          "sha1": "2fc5a4e0bd3ba88a22b192cb807d74809ebc089e",
          "md5": "1fff4c6fda3d72f3132461a2bd5425e0"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-js/0.3.0.1/prompt-executor-model-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-js/0.3.0.1/prompt-executor-model-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-js/0.3.0.1/prompt-executor-model-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-model-jvm/0.3.0.1/prompt-executor-model-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-model-jvm/0.3.0.1/prompt-executor-model-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../prompt-executor-model-jvm/0.3.0.1/prompt-executor-model-jvm-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-jvm",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-wasm-js/0.3.0.1/prompt-executor-model-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-wasm-js/0.3.0.1/prompt-executor-model-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-wasm-js",
        "version": "0.3.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../prompt-executor-model-wasm-js/0.3.0.1/prompt-executor-model-wasm-js-0.3.0.1.module",
        "group": "ai.koog",
        "module": "prompt-executor-model-wasm-js",
        "version": "0.3.0.1"
      }
    }
  ]
}
