{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-files/0.3.0.2/prompt-cache-files-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-cache-files",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.2.jar",
          "url": "prompt-cache-files-jvm-0.3.0.2.jar",
          "size": 18448,
          "sha512": "24ab3024e9aa7a934c437400d92bc79494bc35423a95c1c3db36a946db01c54dcc48308970ee4a3285144d01c8564694056551fe0c4f23c1c5b2b86936d137fb",
          "sha256": "a18d1e735e1f11336611b2e8bc3b994473abd309ed5b24a67d4349a053900981",
          "sha1": "e6f06fcf0f6ba50cfe75107d5a9ebd7c60c80cf5",
          "md5": "1c407bd9dc486483d2f66d437e128935"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.2.jar",
          "url": "prompt-cache-files-jvm-0.3.0.2.jar",
          "size": 18448,
          "sha512": "24ab3024e9aa7a934c437400d92bc79494bc35423a95c1c3db36a946db01c54dcc48308970ee4a3285144d01c8564694056551fe0c4f23c1c5b2b86936d137fb",
          "sha256": "a18d1e735e1f11336611b2e8bc3b994473abd309ed5b24a67d4349a053900981",
          "sha1": "e6f06fcf0f6ba50cfe75107d5a9ebd7c60c80cf5",
          "md5": "1c407bd9dc486483d2f66d437e128935"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-files-jvm-0.3.0.2-sources.jar",
          "url": "prompt-cache-files-jvm-0.3.0.2-sources.jar",
          "size": 2970,
          "sha512": "225e701a8d054eb310e1f54889e8e68fdcb0aaf51e702409a08c8162aafefdff3698b29b2da15a9a9bfd484569ac06dbc1f7d291735abd98ca8ffe1074ce00ad",
          "sha256": "24caa2d9e7873d46b6f06398ea09dc2d9fb7e061fa6f3e12a20947d60b5737e2",
          "sha1": "8feee901ecb03e2ac8da3c1ead9a9076a3eb1a66",
          "md5": "2fe549439e3f4bc97428a3f378038020"
        }
      ]
    }
  ]
}
