{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-cached/0.3.0.2/prompt-executor-cached-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-executor-cached",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.2.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.2.jar",
          "size": 12360,
          "sha512": "e8be7fe93bbeb5e8bd30182ab9f75d4259aba437d3ca5ddbe1e95cdffcf2f133a3191e699c1d8d1ff675bebb2551b1eaa46919032c622945205ac90c007d9923",
          "sha256": "d21e6c8a94b51b2859c249f2fc260345f706f7390706a42e672f0cb49e7624a5",
          "sha1": "3c45d6aa3670d8cea0072535fe87c5fdaac40040",
          "md5": "a53e65a36994637b9c14501dd2bd3589"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.2.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.2.jar",
          "size": 12360,
          "sha512": "e8be7fe93bbeb5e8bd30182ab9f75d4259aba437d3ca5ddbe1e95cdffcf2f133a3191e699c1d8d1ff675bebb2551b1eaa46919032c622945205ac90c007d9923",
          "sha256": "d21e6c8a94b51b2859c249f2fc260345f706f7390706a42e672f0cb49e7624a5",
          "sha1": "3c45d6aa3670d8cea0072535fe87c5fdaac40040",
          "md5": "a53e65a36994637b9c14501dd2bd3589"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.2-sources.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.2-sources.jar",
          "size": 2987,
          "sha512": "83fb175f7c5495efd1d75b37fdad7e535cf4b6f811457abddcffd72acc454df23b2f7f5de2b86209a3bfaccf5728baf1024629be687ce09870323cc926c504c1",
          "sha256": "2afedb0e077a9c559c6eefe9819c4c7479c1aaeb6728083a112a5d2eea90b035",
          "sha1": "7e59a6e29654ab3bbe8e5d6655a036588c4ce23c",
          "md5": "cdd8a853879b856cfdd0a954821f1362"
        }
      ]
    }
  ]
}
