{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-model/0.3.0.2/prompt-cache-model-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-cache-model",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.2.jar",
          "url": "prompt-cache-model-jvm-0.3.0.2.jar",
          "size": 26846,
          "sha512": "e4f300490d249a6c6b2f5f6fba61c44767deb526d13ea441239651fae46aa8b19cc8653ade492a4a42e8aa2813085bec5226427f29eb411d2c59d882f616c5dc",
          "sha256": "a05bfc1fb4ef443d1b339ead3c9ebde7585324e54727adaea24e414c5b2a0aa2",
          "sha1": "756bb5000fec0d853c2e545debafd6d1c7287465",
          "md5": "e9a5051534f9b55bdeeed84179da9591"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.2.jar",
          "url": "prompt-cache-model-jvm-0.3.0.2.jar",
          "size": 26846,
          "sha512": "e4f300490d249a6c6b2f5f6fba61c44767deb526d13ea441239651fae46aa8b19cc8653ade492a4a42e8aa2813085bec5226427f29eb411d2c59d882f616c5dc",
          "sha256": "a05bfc1fb4ef443d1b339ead3c9ebde7585324e54727adaea24e414c5b2a0aa2",
          "sha1": "756bb5000fec0d853c2e545debafd6d1c7287465",
          "md5": "e9a5051534f9b55bdeeed84179da9591"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.2-sources.jar",
          "url": "prompt-cache-model-jvm-0.3.0.2-sources.jar",
          "size": 5387,
          "sha512": "921ded8a17f300ee79282cb0c5208cbf7983bafb2ce29900e9275ae2cacc19a05cf2b0fd6e58754673a6d0438ec288f1ab7754943f452018e9bedbf12964e86a",
          "sha256": "70ef07d5f664bd89cd2a358e2b7f721c939f4e414bef1a74825a90f9d6f215f7",
          "sha1": "efa4b7ea08c4aff3efc74dc6249dcd0eb6d5e15a",
          "md5": "4f1231cef25bed1632442ae8ddfa0e47"
        }
      ]
    }
  ]
}
