{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-model/0.3.0.1/prompt-model-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-model",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-model-jvm-0.3.0.1.jar",
          "url": "prompt-model-jvm-0.3.0.1.jar",
          "size": 242046,
          "sha512": "e936444843ca5504c841b45b7bc50404ddc976cb071cc4c3cd816c464d3cc07ecf5d254f75dd342922c0ae31b7574e96de039b7a7127a374a01456418a718265",
          "sha256": "5504e85c7d5c91fd87a341d72d44857c73748c189b9226ff60fc4e12a475faa2",
          "sha1": "24c98e066f5ac3f4d1b9e1cd542f2b4173f21b4f",
          "md5": "53d3a52f011395561e7ec797ab4001f7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-model-jvm-0.3.0.1.jar",
          "url": "prompt-model-jvm-0.3.0.1.jar",
          "size": 242046,
          "sha512": "e936444843ca5504c841b45b7bc50404ddc976cb071cc4c3cd816c464d3cc07ecf5d254f75dd342922c0ae31b7574e96de039b7a7127a374a01456418a718265",
          "sha256": "5504e85c7d5c91fd87a341d72d44857c73748c189b9226ff60fc4e12a475faa2",
          "sha1": "24c98e066f5ac3f4d1b9e1cd542f2b4173f21b4f",
          "md5": "53d3a52f011395561e7ec797ab4001f7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-model-jvm-0.3.0.1-sources.jar",
          "url": "prompt-model-jvm-0.3.0.1-sources.jar",
          "size": 23155,
          "sha512": "4fb60df4474fc8703f047ea4db25124816fa04b6d76e26f896b69518933837680e323e80244a6a6502861f90e1fe67db43827e0299aab733163645a5a523221a",
          "sha256": "89c8cd95a871324e1479da14338271fb0a2988273b418ddb15fe98b3661371ad",
          "sha1": "658cd777d8ce3b4aacc0f7f45f13ef1206e29bc2",
          "md5": "018220825a68820ac0cd76ea2a88065f"
        }
      ]
    }
  ]
}
