{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-memory/0.3.0.3/agents-features-memory-0.3.0.3.module",
    "group": "ai.koog",
    "module": "agents-features-memory",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.3.jar",
          "url": "agents-features-memory-jvm-0.3.0.3.jar",
          "size": 215248,
          "sha512": "29cffa84cc8a721dc8a4797e56ee7217585715254720d9a223331ca265b98ae4237b7b2144cc90341d51bdab3653bbe35a9835243174b8a617cd4b7d287d0bfd",
          "sha256": "cc500830994cbc4d0b4fb1a01a403eae8672160ed9994dae1c9070a5541d8b96",
          "sha1": "d5acedd72afc7fc01ed2bce7316232725b712148",
          "md5": "33f4c5e3ed8a90bf80d9fbe151dcc0a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.3.jar",
          "url": "agents-features-memory-jvm-0.3.0.3.jar",
          "size": 215248,
          "sha512": "29cffa84cc8a721dc8a4797e56ee7217585715254720d9a223331ca265b98ae4237b7b2144cc90341d51bdab3653bbe35a9835243174b8a617cd4b7d287d0bfd",
          "sha256": "cc500830994cbc4d0b4fb1a01a403eae8672160ed9994dae1c9070a5541d8b96",
          "sha1": "d5acedd72afc7fc01ed2bce7316232725b712148",
          "md5": "33f4c5e3ed8a90bf80d9fbe151dcc0a5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-memory-jvm-0.3.0.3-sources.jar",
          "url": "agents-features-memory-jvm-0.3.0.3-sources.jar",
          "size": 31295,
          "sha512": "e0f6b7c4c7eb79401cfe06c31f8a07b0e4e568c1e3116c5caf741699b7563622eb22e940535e7169583760148848859e60f2bdc4c6bd8a6b9a74019fdb8c742a",
          "sha256": "6bbddbdecb9cbcb196566232329ef716811a1427538304a9081f290653449a08",
          "sha1": "8086fa63aafdbdd2275b30bd02006941d82cf8e0",
          "md5": "4dc275a62440766e44112df3660d254d"
        }
      ]
    }
  ]
}
