{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-trace/0.3.0.1/agents-features-trace-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-trace",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-trace-js-0.3.0.1.klib",
          "url": "agents-features-trace-js-0.3.0.1.klib",
          "size": 32899,
          "sha512": "c414f6c4aad9725d01c987c26da2516de3b5b1bf1a1ba60a4a36509994da2f41a230d7f79e11804183246b5c6ce7e86007f888fc52c4697e8dd49240adf68207",
          "sha256": "0caa555ff47c5426633b60f15a0f5009c8a1dbc3a0d5acd79a1e08d8546bf0f8",
          "sha1": "ce97432bf7e4cf8df2625d19b1db2f88a7aa77a0",
          "md5": "7eaa59768844985fd8c352feb86149e0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-trace-js-0.3.0.1.klib",
          "url": "agents-features-trace-js-0.3.0.1.klib",
          "size": 32899,
          "sha512": "c414f6c4aad9725d01c987c26da2516de3b5b1bf1a1ba60a4a36509994da2f41a230d7f79e11804183246b5c6ce7e86007f888fc52c4697e8dd49240adf68207",
          "sha256": "0caa555ff47c5426633b60f15a0f5009c8a1dbc3a0d5acd79a1e08d8546bf0f8",
          "sha1": "ce97432bf7e4cf8df2625d19b1db2f88a7aa77a0",
          "md5": "7eaa59768844985fd8c352feb86149e0"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "agents-features-trace-js-0.3.0.1-sources.jar",
          "url": "agents-features-trace-js-0.3.0.1-sources.jar",
          "size": 9836,
          "sha512": "7b8b2889e49cb36ce538ddb0938f5321e6b2c4b4c9bb0998e83e1e9d297ac234d1e10718055bc25e0980576b09bf26c46a830b256a9235a40aefcd3dd57f72d7",
          "sha256": "4bcb3eb91e7079a5bd9805c278e9e571972766456edfe917af4fc1fcf945d413",
          "sha1": "c0869ced325f4ae9a728ea0b3e5398ebb0889a2c",
          "md5": "d123321153ff3e45492743625eac70e8"
        }
      ]
    }
  ]
}
