{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-tools/0.3.0.1/agents-tools-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-tools",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.1.jar",
          "url": "agents-tools-jvm-0.3.0.1.jar",
          "size": 109552,
          "sha512": "d1b99549b6cbe0cc713efd7b9a817f413325283cbbecf616fc8d2c97b9408e18f724c53f34dada42943b5fdc4765a018dc10aa63a373b9b77753e6b43cbb3c6f",
          "sha256": "bd709a522d460ca7910a317b6776b4a8b373bd37f791f55e6f64d79a7502c26c",
          "sha1": "ec083b66678ef24ef9a2c0f3cde700046ff2a6de",
          "md5": "bcefb12ec949b8d37b97d92c66ed20a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.1.jar",
          "url": "agents-tools-jvm-0.3.0.1.jar",
          "size": 109552,
          "sha512": "d1b99549b6cbe0cc713efd7b9a817f413325283cbbecf616fc8d2c97b9408e18f724c53f34dada42943b5fdc4765a018dc10aa63a373b9b77753e6b43cbb3c6f",
          "sha256": "bd709a522d460ca7910a317b6776b4a8b373bd37f791f55e6f64d79a7502c26c",
          "sha1": "ec083b66678ef24ef9a2c0f3cde700046ff2a6de",
          "md5": "bcefb12ec949b8d37b97d92c66ed20a5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.1-sources.jar",
          "url": "agents-tools-jvm-0.3.0.1-sources.jar",
          "size": 22831,
          "sha512": "763a30d6f6bf267e150690e69012e02157318d4f60918a4470c02a5976c16f405441c952a985ded56a2e698e49089677291ebf810466152980c88a4118f19ad3",
          "sha256": "37f035852a915127179c2267c7759d6a0621adb071b4509feebdcd77dbaec0dd",
          "sha1": "4b9f6d44aacb516fd3ee08fc526c87c17e1c84e3",
          "md5": "9a7253419da328075860ba0d191ff77d"
        }
      ]
    }
  ]
}
