{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-openrouter-client/0.3.0.4/prompt-executor-openrouter-client-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-openrouter-client",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.4.jar",
          "size": 185253,
          "sha512": "a6cbac0aa9d87f7c9b6d06b7980b8975cce49c9dca4f1eefb11c974f7ccede699fcecf353daf38748583e2ee5ca63773518e3056a4b6d4cf8f5893b88b9561fc",
          "sha256": "54aec954019034d71cfc0579303586d4d1aa5fa10ccd1cb31c4690865c328ce2",
          "sha1": "c13bad76d3cfd1e7329d548eece43756777fec9e",
          "md5": "47570e413e4d1a464fc384e2d3fcf054"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-anthropic-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-google-client",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.4.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.4.jar",
          "size": 185253,
          "sha512": "a6cbac0aa9d87f7c9b6d06b7980b8975cce49c9dca4f1eefb11c974f7ccede699fcecf353daf38748583e2ee5ca63773518e3056a4b6d4cf8f5893b88b9561fc",
          "sha256": "54aec954019034d71cfc0579303586d4d1aa5fa10ccd1cb31c4690865c328ce2",
          "sha1": "c13bad76d3cfd1e7329d548eece43756777fec9e",
          "md5": "47570e413e4d1a464fc384e2d3fcf054"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-openrouter-client-jvm-0.3.0.4-sources.jar",
          "url": "prompt-executor-openrouter-client-jvm-0.3.0.4-sources.jar",
          "size": 9666,
          "sha512": "8780e09969e7600327e01a51806e8f36ece928dcc2aaa0dfaf32b083098e24ea1cd7263ae0641d2c8a8f63860991bcc06faec18191249c4a612bb8048bbf8fc4",
          "sha256": "871b0b05567c7dcd6604017dc419912afee30d84a0a3dbbfa6e021611900d0a4",
          "sha1": "06752161d5fbfba252833c5be8d09e270d0fa301",
          "md5": "f25d534714e235a370fddbe1aa0569b5"
        }
      ]
    }
  ]
}
