{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-google-client/0.3.0.3/prompt-executor-google-client-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-executor-google-client",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.3.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.3.jar",
          "size": 187263,
          "sha512": "c4e85206edb6129d1e9e64c4580c0f7cd3b5a3556022a40ac84ef3692aa9b456d57cf6f42fa658f2810419ae259a338b0f6ab70e0e60a26f0992af4564d368dd",
          "sha256": "914c172a8b0dce6968dc8fe9e445c9bf6832467f345d120c5ac96e5990e90e70",
          "sha1": "710f7d311db82526d63784a181f366ee04fd6d33",
          "md5": "baaf67d990050ef274b9c5fc5b2e3514"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-utils",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-structure",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.3.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.3.jar",
          "size": 187263,
          "sha512": "c4e85206edb6129d1e9e64c4580c0f7cd3b5a3556022a40ac84ef3692aa9b456d57cf6f42fa658f2810419ae259a338b0f6ab70e0e60a26f0992af4564d368dd",
          "sha256": "914c172a8b0dce6968dc8fe9e445c9bf6832467f345d120c5ac96e5990e90e70",
          "sha1": "710f7d311db82526d63784a181f366ee04fd6d33",
          "md5": "baaf67d990050ef274b9c5fc5b2e3514"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-google-client-jvm-0.3.0.3-sources.jar",
          "url": "prompt-executor-google-client-jvm-0.3.0.3-sources.jar",
          "size": 15001,
          "sha512": "1832fca53d54ef62e602dcefee0bd35461b5e07e7cbbd440bfbf135cf61db1a02d3bc1d0cfc5d8979c86b21d6e6a963bb5b87fbc521f306063c1c72a1fa08465",
          "sha256": "ad98fb405f432489e2781cf812913e193f7e5884cc25c0d8a71c859523473504",
          "sha1": "ae954fc81d7e64df0c8399556332aed7d87c4acc",
          "md5": "5fc7597292e41917e07cda368632df93"
        }
      ]
    }
  ]
}
