{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-snapshot/0.3.0.2/agents-features-snapshot-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-features-snapshot",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.2.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.2.jar",
          "size": 57654,
          "sha512": "3bd166f7cf9cbf9ffd80e8c1c34935ddf5decf5699c961cd3e37acf21f1f69b3c26656d0305de603c7b637c9ac9c0b0a981b774882dd90ccf80295e27acd28a9",
          "sha256": "9f9c0ebb15a6fe8e3922d44f5de9f7bae0c7e10a6945242c53a51d394f9d7840",
          "sha1": "1c798e23524c63a7f6d286f3d1212bd4206f8ec5",
          "md5": "6dbf2f24532f77cf80f0bfb823bd92df"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.2.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.2.jar",
          "size": 57654,
          "sha512": "3bd166f7cf9cbf9ffd80e8c1c34935ddf5decf5699c961cd3e37acf21f1f69b3c26656d0305de603c7b637c9ac9c0b0a981b774882dd90ccf80295e27acd28a9",
          "sha256": "9f9c0ebb15a6fe8e3922d44f5de9f7bae0c7e10a6945242c53a51d394f9d7840",
          "sha1": "1c798e23524c63a7f6d286f3d1212bd4206f8ec5",
          "md5": "6dbf2f24532f77cf80f0bfb823bd92df"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-snapshot-jvm-0.3.0.2-sources.jar",
          "url": "agents-features-snapshot-jvm-0.3.0.2-sources.jar",
          "size": 11197,
          "sha512": "2003e6fe0cad57845d79b981e1c2934dbd6acd6f29b14f8391004f1dda3858399d7d6bd307fbf2db98f8c68a58131c46eef1944cc3f861c8897ffca2aa7605c4",
          "sha256": "98314cf24bce5f5e05a1260175af747987a48e04f9fbd4973b9dd92d02a8b5a8",
          "sha1": "7f856949d85590a48a6f787cb4da52fa2de74578",
          "md5": "b56a49d290cc1679eb4b590fbec6de18"
        }
      ]
    }
  ]
}
