{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-debugger/0.3.0.2/agents-features-debugger-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-features-debugger",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.2.jar",
          "url": "agents-features-debugger-jvm-0.3.0.2.jar",
          "size": 40097,
          "sha512": "dd77d0c09f35882a6d9cb8fa94f71f10340cb12fa791300bc7f33a38bf4bdd20708786750a0259f72fd1916e384f05dcccc4852014d5eeeb62c9c73c461ced4b",
          "sha256": "682064789aa8f31de42699151d4deebbf41de58b7877faaf54752efb77d30647",
          "sha1": "98d24c2277e62bc7d132b784115dfc6466fb11b2",
          "md5": "0d3bcd13a331e2bedf827c3f4af3b021"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sse",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.2.jar",
          "url": "agents-features-debugger-jvm-0.3.0.2.jar",
          "size": 40097,
          "sha512": "dd77d0c09f35882a6d9cb8fa94f71f10340cb12fa791300bc7f33a38bf4bdd20708786750a0259f72fd1916e384f05dcccc4852014d5eeeb62c9c73c461ced4b",
          "sha256": "682064789aa8f31de42699151d4deebbf41de58b7877faaf54752efb77d30647",
          "sha1": "98d24c2277e62bc7d132b784115dfc6466fb11b2",
          "md5": "0d3bcd13a331e2bedf827c3f4af3b021"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-features-debugger-jvm-0.3.0.2-sources.jar",
          "url": "agents-features-debugger-jvm-0.3.0.2-sources.jar",
          "size": 7023,
          "sha512": "5dc2afba255c6b20c5ef4f439fc42ab379e82c73fe64c5a626e0d6a08db014a22151a622ec2a61926d133b5e6eeceb1fc575bd7b0254c32668ada5e3a1044581",
          "sha256": "8220f7a766e96e9077393e7054d4d4d7858a79f21d46c9d8ad582b68930b054b",
          "sha1": "ddd2f5ef0a82df38ef51e06e88cdfe7584cd7d41",
          "md5": "2872ec13c1db303e6b83643968219a92"
        }
      ]
    }
  ]
}
