{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "agents-test",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-ext",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-openai-client",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms-all",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-tokenizer",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-test-metadata-0.3.0.2.jar",
          "url": "agents-test-0.3.0.2.jar",
          "size": 13722,
          "sha512": "6265e5ca3982ebf3c1c09deaf4032bfe34857cdeb22253789236a278e3de93356dec92600ada113a2a8115c016479cd8f572ac53160199ea5a0620a3dec65117",
          "sha256": "5f8ccfe8c675053ce24516616c2d1f0ee6659aacc83b510b33ba101b707fc02f",
          "sha1": "da438a6eb72b6c0a750ab70ac41b282e7d405d10",
          "md5": "163d52683f6ed18a6d57e842cad5f854"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "agents-test-kotlin-0.3.0.2-sources.jar",
          "url": "agents-test-0.3.0.2-sources.jar",
          "size": 34436,
          "sha512": "f37da862af4d39d3f7e4ebc60a8ce90e7a35162f472a4e338e6c014e7faac38201f253f12ed048de26322e1d34696525fb6f21c0dbab8382c9693a0629acbf87",
          "sha256": "80296dc35349fb55bb35514324a2e70c7779a1eee86e42062cd20e1b75c7a66d",
          "sha1": "635f47b02cfa78c97303355d2403de33ed350207",
          "md5": "ee786d25e45d56873f3f2d1ec01b588d"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-test-js/0.3.0.2/agents-test-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-test-js/0.3.0.2/agents-test-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-test-js/0.3.0.2/agents-test-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-test-jvm/0.3.0.2/agents-test-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-test-jvm/0.3.0.2/agents-test-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-test-jvm/0.3.0.2/agents-test-jvm-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-jvm",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-test-wasm-js/0.3.0.2/agents-test-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-test-wasm-js/0.3.0.2/agents-test-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-wasm-js",
        "version": "0.3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-test-wasm-js/0.3.0.2/agents-test-wasm-js-0.3.0.2.module",
        "group": "ai.koog",
        "module": "agents-test-wasm-js",
        "version": "0.3.0.2"
      }
    }
  ]
}
