{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.koog",
    "module": "agents-features-memory",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-metadata-0.3.0.4.jar",
          "url": "agents-features-memory-0.3.0.4.jar",
          "size": 15261,
          "sha512": "59e26b3280b45f42d33bb4d62c5d1c8c79f7547a407375aa24e196bbfcc27614cf4cb475d3e42932cac3e348132fd68dfb1cd146e688c213f74cf6eae6dabdaa",
          "sha256": "db9f0e04e356e5b9cec66afe0ce50274533bc1a2f3a946f397484fa8908a08f3",
          "sha1": "7978e99a3f4033884d1e56834f486de1cdb2f421",
          "md5": "dccd92af9802b68253d5c5c2d40726c9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "agents-features-memory-kotlin-0.3.0.4-sources.jar",
          "url": "agents-features-memory-0.3.0.4-sources.jar",
          "size": 28478,
          "sha512": "3c2148c3f2e662dfcdcff91b78b9ed393315d3eca59b6ca14b4070541eae558f46d1b92e2c8dfc864b1dbeb90b5f3b272f27fb16ae3dc111bd90d5b7409148ee",
          "sha256": "e857bc00ac21cfd890375c9249356aaa44c76d2df704780a1e4562daf19f8044",
          "sha1": "768ab9053f933c03398d91cb1545291418ddbc92",
          "md5": "91afd9c88d3167d892c9f00229a4d428"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-js/0.3.0.4/agents-features-memory-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-js/0.3.0.4/agents-features-memory-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-js/0.3.0.4/agents-features-memory-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-memory-jvm/0.3.0.4/agents-features-memory-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-memory-jvm/0.3.0.4/agents-features-memory-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../agents-features-memory-jvm/0.3.0.4/agents-features-memory-jvm-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-jvm",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-wasm-js/0.3.0.4/agents-features-memory-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-wasm-js/0.3.0.4/agents-features-memory-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-wasm-js",
        "version": "0.3.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../agents-features-memory-wasm-js/0.3.0.4/agents-features-memory-wasm-js-0.3.0.4.module",
        "group": "ai.koog",
        "module": "agents-features-memory-wasm-js",
        "version": "0.3.0.4"
      }
    }
  ]
}
