{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-clients/0.3.0.2/prompt-executor-clients-0.3.0.2.module",
    "group": "ai.koog",
    "module": "prompt-executor-clients",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.2.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.2.jar",
          "size": 10601,
          "sha512": "d89a543362b5bf756c725de1ae95618f5424146fb222886a2b6f403d03f1e114fd287d0bb6247f6abd5de3379cce02d698f7e852e8820b31e40756cc54c1bf7b",
          "sha256": "92812a506dc481a9edc536fe835e5abe40573cc278b1c3a9c502cc61a65cf5bb",
          "sha1": "d03c0552f38d2627b96c82d82b6d0248ec3e3900",
          "md5": "f0764709a9ad790de111f576a92426e1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.2.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.2.jar",
          "size": 10601,
          "sha512": "d89a543362b5bf756c725de1ae95618f5424146fb222886a2b6f403d03f1e114fd287d0bb6247f6abd5de3379cce02d698f7e852e8820b31e40756cc54c1bf7b",
          "sha256": "92812a506dc481a9edc536fe835e5abe40573cc278b1c3a9c502cc61a65cf5bb",
          "sha1": "d03c0552f38d2627b96c82d82b6d0248ec3e3900",
          "md5": "f0764709a9ad790de111f576a92426e1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.2-sources.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.2-sources.jar",
          "size": 5674,
          "sha512": "6d62a79cbe627934a4a90e04c5296326ccca92506e50406b27e660006af69dbf0573be5ed3b3612b6f36d573e411533896b542db67f7da99e6a733b17fc7f4d6",
          "sha256": "237aa52cf7dfed42175b31f6191105db97b283d3cdac2168af95993e42d92846",
          "sha1": "f489eeeeba1511db3f3740ff7d193365be875176",
          "md5": "496b1fc79cd5722c972328adb1ead6ae"
        }
      ]
    }
  ]
}
