{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-llms/0.3.0.3/prompt-executor-llms-0.3.0.3.module",
    "group": "ai.koog",
    "module": "prompt-executor-llms",
    "version": "0.3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-js-0.3.0.3.klib",
          "url": "prompt-executor-llms-js-0.3.0.3.klib",
          "size": 16423,
          "sha512": "184861c0f5f0e7199d5bbf21d881868b91a6bd0300ec6a92b5d8efc68df04e1bf5e06b3cbbb323019470b18099f00b6c8384de6f10353c4cdb4c28b374f0ca2f",
          "sha256": "4d2c2b6c42ccddea392a3d4be5cf6cf0e28a2ff69df3c795662c2b137f7ce410",
          "sha1": "24ce5c7aa4787e300f72f006b93f6b85b0cb26a5",
          "md5": "3ccd911417b06f692c33d62cf4c685b9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-llms-js-0.3.0.3.klib",
          "url": "prompt-executor-llms-js-0.3.0.3.klib",
          "size": 16423,
          "sha512": "184861c0f5f0e7199d5bbf21d881868b91a6bd0300ec6a92b5d8efc68df04e1bf5e06b3cbbb323019470b18099f00b6c8384de6f10353c4cdb4c28b374f0ca2f",
          "sha256": "4d2c2b6c42ccddea392a3d4be5cf6cf0e28a2ff69df3c795662c2b137f7ce410",
          "sha1": "24ce5c7aa4787e300f72f006b93f6b85b0cb26a5",
          "md5": "3ccd911417b06f692c33d62cf4c685b9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "prompt-executor-llms-js-0.3.0.3-sources.jar",
          "url": "prompt-executor-llms-js-0.3.0.3-sources.jar",
          "size": 4662,
          "sha512": "a2abccd591a749f639d52684fbc65a7b96f8a0c1c214ae427f0ac87759e2e83b13beed6cbbd4561d96ab91dfa66c9a1a47e0bbe5c63f51a7c5209e0e6b8716c6",
          "sha256": "4e770f73bfb17387fa9e05bdc70731a08c3edde3741e2a12a7de7e097f810725",
          "sha1": "e8449b0d6bfa6915d7002b94fa833b675ddeb23e",
          "md5": "5427be1e4d7344e38e3c534142e91e13"
        }
      ]
    }
  ]
}
