{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-cached/0.3.0.1/prompt-executor-cached-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-cached",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.1.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.1.jar",
          "size": 12360,
          "sha512": "8d2eaca4ebd9a38acb171f4a77a12a2b88290458311aa6da52889ef9601a28b35c604c65877c8b8d8231eee72da56ab1e7cf5ee05326d9b6530801b38670ecf3",
          "sha256": "5e22c91ebf7c9d88ae8566e9fc986ce6fcb6eece070acd1f1bfd4628c580c41b",
          "sha1": "485315fdc9909eb7f3a922bb5ad4dd751f2d81b6",
          "md5": "412fd274cdc1808feb5b4c456c90a996"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "prompt-cache-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.1.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.1.jar",
          "size": 12360,
          "sha512": "8d2eaca4ebd9a38acb171f4a77a12a2b88290458311aa6da52889ef9601a28b35c604c65877c8b8d8231eee72da56ab1e7cf5ee05326d9b6530801b38670ecf3",
          "sha256": "5e22c91ebf7c9d88ae8566e9fc986ce6fcb6eece070acd1f1bfd4628c580c41b",
          "sha1": "485315fdc9909eb7f3a922bb5ad4dd751f2d81b6",
          "md5": "412fd274cdc1808feb5b4c456c90a996"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-cached-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-cached-jvm-0.3.0.1-sources.jar",
          "size": 2987,
          "sha512": "83fb175f7c5495efd1d75b37fdad7e535cf4b6f811457abddcffd72acc454df23b2f7f5de2b86209a3bfaccf5728baf1024629be687ce09870323cc926c504c1",
          "sha256": "2afedb0e077a9c559c6eefe9819c4c7479c1aaeb6728083a112a5d2eea90b035",
          "sha1": "7e59a6e29654ab3bbe8e5d6655a036588c4ce23c",
          "md5": "cdd8a853879b856cfdd0a954821f1362"
        }
      ]
    }
  ]
}
