{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-ollama-client/0.3.0.1/prompt-executor-ollama-client-0.3.0.1.module",
    "group": "ai.koog",
    "module": "prompt-executor-ollama-client",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-ollama-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-ollama-client-jvm-0.3.0.1.jar",
          "size": 178640,
          "sha512": "1917f3b25527dfd7556fb10ec9a565e62c550b03db6bbd0a6204ccd3da89413fd4cd5c82bed7bb4c6b4b5c0ad48921742c4882d5229803e7dee31c8577f476ed",
          "sha256": "8f7e87ffe60ba963b8209cfa8f52fdd8ab79a4d1aff185d1f65187d4959d71a3",
          "sha1": "68abe76ff2aa9f7c4a74e55c2300b91f49bb9a85",
          "md5": "89d77ab897f40a1f8b7fcf8e04bfc7f4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-llm",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-clients",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-llms",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "embeddings-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-ollama-client-jvm-0.3.0.1.jar",
          "url": "prompt-executor-ollama-client-jvm-0.3.0.1.jar",
          "size": 178640,
          "sha512": "1917f3b25527dfd7556fb10ec9a565e62c550b03db6bbd0a6204ccd3da89413fd4cd5c82bed7bb4c6b4b5c0ad48921742c4882d5229803e7dee31c8577f476ed",
          "sha256": "8f7e87ffe60ba963b8209cfa8f52fdd8ab79a4d1aff185d1f65187d4959d71a3",
          "sha1": "68abe76ff2aa9f7c4a74e55c2300b91f49bb9a85",
          "md5": "89d77ab897f40a1f8b7fcf8e04bfc7f4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-ollama-client-jvm-0.3.0.1-sources.jar",
          "url": "prompt-executor-ollama-client-jvm-0.3.0.1-sources.jar",
          "size": 16584,
          "sha512": "4e05a446613ef1f5a97362391ed1cdf23370025d6b50b463f99cc1abfbe994595fa35664d2274fe6fb57e6bef739590b229ac173af35112e2ce007a2827bd7e7",
          "sha256": "b50e1b102409702b13e9c437e1b7965b3158f4dfdfb3016c74e55fa361c5d63e",
          "sha1": "832275fdc0d275273f0d713fdb3ad56089bceac0",
          "md5": "1426a5929f5fd46a215a0328d5c7b283"
        }
      ]
    }
  ]
}
