{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-features-memory/0.3.0.1/agents-features-memory-0.3.0.1.module",
    "group": "ai.koog",
    "module": "agents-features-memory",
    "version": "0.3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-js-0.3.0.1.klib",
          "url": "agents-features-memory-js-0.3.0.1.klib",
          "size": 114771,
          "sha512": "a6e0ffd96f89037089f4f3f64ce38d41271c96453ec6b31f1072ffe5f899b0423c009c1310edfabf3ea740a1cd3775cf581c4bb8d92ec944d7ef852f237113e1",
          "sha256": "e434ec0dbdbc3a21aa93b397d8c53817bfc40e35eb53ee0598c6dbdb46d7020d",
          "sha1": "7c0af0982f414d154ebbbbb19947390952243678",
          "md5": "0cefe8ed90025e3f6b69a12bc2f42e32"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-core",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-markdown",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "ai.koog",
          "module": "rag-base",
          "version": {
            "requires": "0.3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-features-memory-js-0.3.0.1.klib",
          "url": "agents-features-memory-js-0.3.0.1.klib",
          "size": 114771,
          "sha512": "a6e0ffd96f89037089f4f3f64ce38d41271c96453ec6b31f1072ffe5f899b0423c009c1310edfabf3ea740a1cd3775cf581c4bb8d92ec944d7ef852f237113e1",
          "sha256": "e434ec0dbdbc3a21aa93b397d8c53817bfc40e35eb53ee0598c6dbdb46d7020d",
          "sha1": "7c0af0982f414d154ebbbbb19947390952243678",
          "md5": "0cefe8ed90025e3f6b69a12bc2f42e32"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "agents-features-memory-js-0.3.0.1-sources.jar",
          "url": "agents-features-memory-js-0.3.0.1-sources.jar",
          "size": 28478,
          "sha512": "3c2148c3f2e662dfcdcff91b78b9ed393315d3eca59b6ca14b4070541eae558f46d1b92e2c8dfc864b1dbeb90b5f3b272f27fb16ae3dc111bd90d5b7409148ee",
          "sha256": "e857bc00ac21cfd890375c9249356aaa44c76d2df704780a1e4562daf19f8044",
          "sha1": "768ab9053f933c03398d91cb1545291418ddbc92",
          "md5": "91afd9c88d3167d892c9f00229a4d428"
        }
      ]
    }
  ]
}
