{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-cache-model/0.3.0.4/prompt-cache-model-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-cache-model",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.4.jar",
          "url": "prompt-cache-model-jvm-0.3.0.4.jar",
          "size": 26846,
          "sha512": "6a0f971f366fe45e71bbe30f1b17eb25ebbae74f86d295c118e89ece88e42557d50783d0e27bc61e7bfdcabdbfdfbac0042e026f32228a64b8eb12e23c25c846",
          "sha256": "144ca2408cecf8d04ed43ea5eda3d30af7c3120ecedae3ff61781bf16c343506",
          "sha1": "d833934aea9f3f15c9ac2d8b48e979a1b97ae4cf",
          "md5": "3055cdbd91bf9e74d2c3aa63315952a9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.4.jar",
          "url": "prompt-cache-model-jvm-0.3.0.4.jar",
          "size": 26846,
          "sha512": "6a0f971f366fe45e71bbe30f1b17eb25ebbae74f86d295c118e89ece88e42557d50783d0e27bc61e7bfdcabdbfdfbac0042e026f32228a64b8eb12e23c25c846",
          "sha256": "144ca2408cecf8d04ed43ea5eda3d30af7c3120ecedae3ff61781bf16c343506",
          "sha1": "d833934aea9f3f15c9ac2d8b48e979a1b97ae4cf",
          "md5": "3055cdbd91bf9e74d2c3aa63315952a9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-cache-model-jvm-0.3.0.4-sources.jar",
          "url": "prompt-cache-model-jvm-0.3.0.4-sources.jar",
          "size": 5387,
          "sha512": "921ded8a17f300ee79282cb0c5208cbf7983bafb2ce29900e9275ae2cacc19a05cf2b0fd6e58754673a6d0438ec288f1ab7754943f452018e9bedbf12964e86a",
          "sha256": "70ef07d5f664bd89cd2a358e2b7f721c939f4e414bef1a74825a90f9d6f215f7",
          "sha1": "efa4b7ea08c4aff3efc74dc6249dcd0eb6d5e15a",
          "md5": "4f1231cef25bed1632442ae8ddfa0e47"
        }
      ]
    }
  ]
}
