{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rag-base/0.3.0.2/rag-base-0.3.0.2.module",
    "group": "ai.koog",
    "module": "rag-base",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.2.jar",
          "url": "rag-base-jvm-0.3.0.2.jar",
          "size": 157444,
          "sha512": "e69de59e5a34c10027525d96bb86153a9f0550bdc41e3bbfbbffa522c1201a60260d241fefa6a9ba23d914ebbc1da7a2df025b8db8b663ffe705b0f83fdba5bd",
          "sha256": "a8a6d362bbf321f7bb9f7b38e895773eb128a910e7ab5ae21d352aec7143e982",
          "sha1": "addd76bec6f67dc449da59df2dddd2eb1be1cf6e",
          "md5": "8c3e32d036f052da9e2b1dc25912c2fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.2.jar",
          "url": "rag-base-jvm-0.3.0.2.jar",
          "size": 157444,
          "sha512": "e69de59e5a34c10027525d96bb86153a9f0550bdc41e3bbfbbffa522c1201a60260d241fefa6a9ba23d914ebbc1da7a2df025b8db8b663ffe705b0f83fdba5bd",
          "sha256": "a8a6d362bbf321f7bb9f7b38e895773eb128a910e7ab5ae21d352aec7143e982",
          "sha1": "addd76bec6f67dc449da59df2dddd2eb1be1cf6e",
          "md5": "8c3e32d036f052da9e2b1dc25912c2fb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rag-base-jvm-0.3.0.2-sources.jar",
          "url": "rag-base-jvm-0.3.0.2-sources.jar",
          "size": 24985,
          "sha512": "7679b841ae8c6f1a135225a11f557ccf9b0e6b5c5ed2efbf2e985dc24eed805585e11d14ba16e3fd0f9b1c7d9b5a8a6ae710cabefe77841acc1574ce5e38ed61",
          "sha256": "a679b8ca7924d6ad80dc51bd14200bf4a4e1f333ef56ef8dcad4ef7f3369a055",
          "sha1": "03b2c803b36179ce93c37e9ca98e6ff71b219ea4",
          "md5": "e25fef9e71c9a6d3215bbc163378fc0c"
        }
      ]
    }
  ]
}
