{
  "formatVersion": "1.1",
  "component": {
    "url": "../../prompt-executor-clients/0.3.0.4/prompt-executor-clients-0.3.0.4.module",
    "group": "ai.koog",
    "module": "prompt-executor-clients",
    "version": "0.3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.4.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.4.jar",
          "size": 10601,
          "sha512": "c4999004d8e8b44af0045980682cb0a9323407b01789aefa94dfd84cbfd04baf6a009095ffaa1a46e5c681ec5f63f8a1641b20c6e491861f84f21e6a25ec4a01",
          "sha256": "c7322139b2a13460f4b59568c0b57ba93251103457e13c01629fa3d8c66f53ee",
          "sha1": "76cb843e7d12c538b0623a37ab0a6a81f02d8f45",
          "md5": "c1c93a2a49bc57d46e70fab5b2fad596"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "ai.koog",
          "module": "prompt-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "agents-tools",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "ai.koog",
          "module": "prompt-executor-model",
          "version": {
            "requires": "0.3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.4.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.4.jar",
          "size": 10601,
          "sha512": "c4999004d8e8b44af0045980682cb0a9323407b01789aefa94dfd84cbfd04baf6a009095ffaa1a46e5c681ec5f63f8a1641b20c6e491861f84f21e6a25ec4a01",
          "sha256": "c7322139b2a13460f4b59568c0b57ba93251103457e13c01629fa3d8c66f53ee",
          "sha1": "76cb843e7d12c538b0623a37ab0a6a81f02d8f45",
          "md5": "c1c93a2a49bc57d46e70fab5b2fad596"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "prompt-executor-clients-jvm-0.3.0.4-sources.jar",
          "url": "prompt-executor-clients-jvm-0.3.0.4-sources.jar",
          "size": 5674,
          "sha512": "6d62a79cbe627934a4a90e04c5296326ccca92506e50406b27e660006af69dbf0573be5ed3b3612b6f36d573e411533896b542db67f7da99e6a733b17fc7f4d6",
          "sha256": "237aa52cf7dfed42175b31f6191105db97b283d3cdac2168af95993e42d92846",
          "sha1": "f489eeeeba1511db3f3740ff7d193365be875176",
          "md5": "496b1fc79cd5722c972328adb1ead6ae"
        }
      ]
    }
  ]
}
