{
  "formatVersion": "1.1",
  "component": {
    "url": "../../agents-tools/0.3.0.2/agents-tools-0.3.0.2.module",
    "group": "ai.koog",
    "module": "agents-tools",
    "version": "0.3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.2.jar",
          "url": "agents-tools-jvm-0.3.0.2.jar",
          "size": 109552,
          "sha512": "c2911fe9ff260c03c0940cbcae8842dfd678a0e151937fa70647929468b67b10d62363b3146860239bd4a4b1ba47e4570e1d23a1c2463272c5bf26d157865905",
          "sha256": "6710400ecbe42475ab8505f6bed2fab9041eaec3f81bb63dc7d8a626af875825",
          "sha1": "daef0ceb9e04c35ed4f79ebb845a30f9e8eccea2",
          "md5": "e0accb7890d9b0f3a0a090d61a8d58c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.2.jar",
          "url": "agents-tools-jvm-0.3.0.2.jar",
          "size": 109552,
          "sha512": "c2911fe9ff260c03c0940cbcae8842dfd678a0e151937fa70647929468b67b10d62363b3146860239bd4a4b1ba47e4570e1d23a1c2463272c5bf26d157865905",
          "sha256": "6710400ecbe42475ab8505f6bed2fab9041eaec3f81bb63dc7d8a626af875825",
          "sha1": "daef0ceb9e04c35ed4f79ebb845a30f9e8eccea2",
          "md5": "e0accb7890d9b0f3a0a090d61a8d58c5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "agents-tools-jvm-0.3.0.2-sources.jar",
          "url": "agents-tools-jvm-0.3.0.2-sources.jar",
          "size": 22831,
          "sha512": "763a30d6f6bf267e150690e69012e02157318d4f60918a4470c02a5976c16f405441c952a985ded56a2e698e49089677291ebf810466152980c88a4118f19ad3",
          "sha256": "37f035852a915127179c2267c7759d6a0621adb071b4509feebdcd77dbaec0dd",
          "sha1": "4b9f6d44aacb516fd3ee08fc526c87c17e1c84e3",
          "md5": "9a7253419da328075860ba0d191ff77d"
        }
      ]
    }
  ]
}
